//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 03:19:46 PM CET 
//


package bpm.gateway.core.tsbn.affaires;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PHA" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ACT" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="EPI_OBS" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="ID_OBS" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                                     &lt;attribute name="SRC_INFO" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="PEC_OBS" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="ID_OBS" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                                     &lt;attribute name="SRC_INFO" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="ID_PEC" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="DEC_REF" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="ID_DEC" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="MOY_REF" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="ID_MOY" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ETAB_REF" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="ID_ETAB" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                                     &lt;attribute name="TYP_REP_ETAB" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="ID_ACT" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                           &lt;attribute name="DAT_DEB_ACT" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="DAT_FIN_ACT" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="TYP_ACT" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="TPS_TEL_IN" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="TPS_TEL_OUT" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="TPS_RAD_IN" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="TPS_RAD_OUT" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID_PHA" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                 &lt;attribute name="ID_AGT" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="DAT_DEB" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="DAT_FIN" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="TYP_PHA" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CTX" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DEC" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MOY" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="ID_MOY" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                           &lt;attribute name="COD_INSEE_DEP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="TYP_LIEU_DEP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="CAT_LIEU_DEP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="COO_DEP_X" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="COO_DEP_Y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="COD_INSEE_DEST" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="TYP_LIEU_DEST" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="CAT_LIEU_DEST" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="COO_DEST_X" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="COO_DEST_Y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="COD_INSEE_BASE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="TYP_LIEU_BASE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="CAT_LIEU_BASE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="COO_BASE_X" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="COO_BASE_Y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="GARDE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="FLG_ACCEPT" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="MOT_REFUS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="TYP_MOY" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="MOT_ENG" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="DAT_ACCEPT" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="DAT_DEP" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="DAT_ARR" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="DAT_BIL" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="ID_EQU" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                           &lt;attribute name="EQU_LAB" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ID_VEC" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                           &lt;attribute name="ID_AGT" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                           &lt;attribute name="ID_BASE" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID_DEC" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                 &lt;attribute name="ID_AGT_CRE" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                 &lt;attribute name="ID_AGT_ANN" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                 &lt;attribute name="DAT_DEC" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="TYP_DEC" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="DAT_ANN" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="MOT_ANN" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PEC" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ACTE" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="ID_OBS" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                           &lt;attribute name="ID_AGT" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                           &lt;attribute name="COD_INSEE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="CAT_LIEU" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="TYP_LIEU" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="COO_X" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="COO_Y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="CAT_ACTE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="DIAG" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="ID_OBS" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                           &lt;attribute name="ID_CIM10" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                           &lt;attribute name="ID_AGENT" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                           &lt;attribute name="DAT_DIAG" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="DIAG" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="FLG_DIAG_PRINCIPAL" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="FLG_DIAG_COMORBIDITE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="TRA" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="ID_TRA" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                           &lt;attribute name="ID_RNK" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                           &lt;attribute name="ID_MOY" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                           &lt;attribute name="ID_EQU" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ID_MOY_MED" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                           &lt;attribute name="ID_EQU_MED" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ID_ETAB_DEP" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                           &lt;attribute name="ID_ETAB_DEST" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                           &lt;attribute name="COD_INSEE_DEP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="CAT_LIEU_DEP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="TYP_LIEU_DEP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="COO_DEP_X" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="COO_DEP_Y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="COD_INSEE_DEST" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="CAT_LIEU_DEST" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="TYP_LIEU_DEST" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="COO_DEST_X" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="COO_DEST_Y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="DAT_DEP" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="DAT_ARR" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="FLG_MED" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID_PEC" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                 &lt;attribute name="ID_PAT" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                 &lt;attribute name="CAT_PEC" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="DAT_DEB" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="DAT_FIN" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="DAT_DEB_MED" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="DAT_FIN_MED" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="FLG_MED" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="FLG_TRA" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="MOT_NON_TRA" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EPI_APP" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="ID_EPI" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                 &lt;attribute name="ID_APP" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="ID_EPI" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="COD_INSEE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TYP_LIEU" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CAT_LIEU" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ID_ETAB" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="COO_X" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="COO_Y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="DAT_DEB" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="DAT_FIN" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="MOT_REC" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="GRA" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CAT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pha",
    "dec",
    "pec",
    "epiapp"
})
public class EPI {

    @Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idEpi == null) ? 0 : idEpi.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null)
			return false;
		if(!(obj instanceof EPI))
			return false;
		EPI other = (EPI) obj;
		if(idEpi == null) {
			if(other.idEpi != null)
				return false;
		}
		else if(!idEpi.equals(other.idEpi))
			return false;
		return true;
	}

	@XmlElement(name = "PHA", required = true)
    protected List<PHA> pha;
    @XmlElement(name = "DEC")
    protected List<DEC> dec;
    @XmlElement(name = "PEC")
    protected List<PEC> pec;
    @XmlElement(name = "EPI_APP", required = true)
    protected List<EPIAPP> epiapp;
    @XmlAttribute(name = "ID_EPI", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String idEpi;
    @XmlAttribute(name = "COD_INSEE")
    protected String codinsee;
    @XmlAttribute(name = "TYP_LIEU")
    protected String typlieu;
    @XmlAttribute(name = "CAT_LIEU")
    protected String catlieu;
    @XmlAttribute(name = "ID_ETAB")
    @XmlSchemaType(name = "anySimpleType")
    protected String idetab;
    @XmlAttribute(name = "COO_X")
    protected BigDecimal coox;
    @XmlAttribute(name = "COO_Y")
    protected BigDecimal cooy;
    @XmlAttribute(name = "DAT_DEB", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datdeb;
    @XmlAttribute(name = "DAT_FIN", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datfin;
    @XmlAttribute(name = "MOT_REC")
    protected String motrec;
    @XmlAttribute(name = "GRA")
    protected String gra;
    @XmlAttribute(name = "CAT")
    protected String cat;
    @XmlAttribute(name = "AGT_CRE")
    protected String agtcre;
    @XmlAttribute(name = "APP_CRE")
    protected String appcre;

    /**
     * Gets the value of the pha property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pha property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPHA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PHA }
     * 
     * 
     */
    public List<PHA> getPha() {
        if (pha == null) {
            pha = new ArrayList<PHA>();
        }
        return this.pha;
    }
    
    public void setPha(List<PHA> pha) {
    	this.pha = pha;
    }

    /**
     * Gets the value of the dec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDEC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DEC }
     * 
     * 
     */
    public List<DEC> getDec() {
        if (dec == null) {
            dec = new ArrayList<DEC>();
        }
        return this.dec;
    }
    
    public void setDec(List<DEC> dec) {
    	this.dec = dec;
    }

    /**
     * Gets the value of the pec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPEC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PEC }
     * 
     * 
     */
    public List<PEC> getPec() {
        if (pec == null) {
            pec = new ArrayList<PEC>();
        }
        return this.pec;
    }
    
    public void setPec(List<PEC> pec) {
    	this.pec = pec;
    }

    /**
     * Gets the value of the epiapp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the epiapp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEPIAPP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EPIAPP }
     * 
     * 
     */
    public List<EPIAPP> getEpiapp() {
        if (epiapp == null) {
            epiapp = new ArrayList<EPIAPP>();
        }
        return this.epiapp;
    }
    
    public void setEpiapp(List<EPIAPP> epiapp) {
    	this.epiapp = epiapp;
    }

    /**
     * Gets the value of the idepi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdEpi() {
        return idEpi;
    }

    /**
     * Sets the value of the idepi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdEpi(String value) {
        this.idEpi = value;
    }

    /**
     * Gets the value of the codinsee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODINSEE() {
        return codinsee;
    }

    /**
     * Sets the value of the codinsee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODINSEE(String value) {
        this.codinsee = value;
    }

    /**
     * Gets the value of the typlieu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTYPLIEU() {
        return typlieu;
    }

    /**
     * Sets the value of the typlieu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTYPLIEU(String value) {
        this.typlieu = value;
    }

    /**
     * Gets the value of the catlieu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCATLIEU() {
        return catlieu;
    }

    /**
     * Sets the value of the catlieu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCATLIEU(String value) {
        this.catlieu = value;
    }

    /**
     * Gets the value of the idetab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDETAB() {
        return idetab;
    }

    /**
     * Sets the value of the idetab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDETAB(String value) {
        this.idetab = value;
    }

    /**
     * Gets the value of the coox property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCOOX() {
        return coox;
    }

    /**
     * Sets the value of the coox property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCOOX(BigDecimal value) {
        this.coox = value;
    }

    /**
     * Gets the value of the cooy property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCOOY() {
        return cooy;
    }

    /**
     * Sets the value of the cooy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCOOY(BigDecimal value) {
        this.cooy = value;
    }

    /**
     * Gets the value of the datdeb property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getDatdeb() {
        return toDate(datdeb);
    }

    /**
     * Sets the value of the datdeb property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatdeb(XMLGregorianCalendar value) {
        this.datdeb = value;
    }
    
    //Not used, for hibernate
    public void setDatdeb(Date value) { }

    /**
     * Gets the value of the datfin property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getDatfin() {
        return toDate(datfin);
    }

    /**
     * Sets the value of the datfin property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatfin(XMLGregorianCalendar value) {
        this.datfin = value;
    }
    
    //Not used, for hibernate
    public void setDatfin(Date value) { }

    /**
     * Gets the value of the motrec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOTREC() {
        return motrec;
    }

    /**
     * Sets the value of the motrec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOTREC(String value) {
        this.motrec = value;
    }

    /**
     * Gets the value of the gra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGRA() {
        return gra;
    }

    /**
     * Sets the value of the gra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGRA(String value) {
        this.gra = value;
    }

    /**
     * Gets the value of the cat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAT() {
        return cat;
    }

    /**
     * Sets the value of the cat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAT(String value) {
        this.cat = value;
    }

    public String getAGTCRE() {
        return agtcre;
    }

    public void setAGTCRE(String value) {
        this.agtcre = value;
    }

    public String getAPPCRE() {
        return appcre;
    }

    public void setAPPCRE(String value) {
        this.appcre = value;
    }

    private Date toDate(XMLGregorianCalendar calendar){
        if(calendar == null) {
            return null;
        }
        return calendar.toGregorianCalendar().getTime();
    }

	public void setIdSamu(String idSamu) {
		if (pha != null) {
			for (PHA ph : pha) {
				ph.setIdSamu(idSamu);
			}
		}

		if (dec != null) {
			for (DEC de : dec) {
				de.setIdSamu(idSamu);
			}
		}
		
		if (pec != null) {
			for (PEC pe : pec) {
				pe.setIdSamu(idSamu);
			}
		}
		
		if (epiapp != null) {
			for (EPIAPP epiAp : epiapp) {
				epiAp.setIdSamu(idSamu);
			}
		}
		
		String currentId = getIdEpi();
		
		String prefix = idSamu + "-";
		if (!currentId.startsWith(prefix)) {
			setIdEpi(prefix + currentId);
		}
		
		String appCree = getAPPCRE();
		if (!appCree.startsWith(prefix)) {
			setAPPCRE(prefix + appCree);
		}
	}

}
