//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.25 at 10:35:23 AM CEST 
//


package bpm.gateway.core.tsbn.affaires;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ID_ETAB" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="ID_TRA" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="MOT_ENG" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MOT_ENG_ADD" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MOT_REFUS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class ETABTRA {
	
	@XmlTransient
	private int id;
	
    @Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idetab == null) ? 0 : idetab.hashCode());
		result = prime * result + ((idtra == null) ? 0 : idtra.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		
		if(obj == null)
			return false;
		
		if(!(obj instanceof ETABTRA))
			return false;
		
		ETABTRA other = (ETABTRA) obj;
		if(idetab == null) {
			if(other.idetab != null)
				return false;
		}
		else if(!idetab.equals(other.idetab))
			return false;
		
		if(idtra == null) {
			if(other.idtra != null)
				return false;
		}
		else if(!idtra.equals(other.idtra))
			return false;
		
		return true;
	}

    @XmlAttribute(name = "ID_ETAB")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object idetab;
    @XmlAttribute(name = "ID_TRA")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object idtra;
    @XmlAttribute(name = "MOT_ENG")
    protected String moteng;
    @XmlAttribute(name = "MOT_ENG_ADD")
    protected String motengadd;
    @XmlAttribute(name = "MOT_REFUS")
    protected String motrefus;
	
	public int getId() {
		return id;
	}
	
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Gets the value of the idetab property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIdetab() {
        return idetab != null ? ((ETAB) idetab).getIdEtab() : "";
    }

    /**
     * Sets the value of the idetab property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIdetab(Object value) {
        if(!(value instanceof String)) {
    		this.idetab = value;
    	}
    }

    /**
     * Gets the value of the idtra property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIdtra() {
        return idtra != null ? ((TRA) idtra).getIdTra() : "";
    }

    /**
     * Sets the value of the idtra property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIdtra(Object value) {
        if(!(value instanceof String)) {
    		this.idtra = value;
    	}
    }

    /**
     * Gets the value of the moteng property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOTENG() {
        return moteng;
    }

    /**
     * Sets the value of the moteng property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOTENG(String value) {
        this.moteng = value;
    }

    /**
     * Gets the value of the motengadd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOTENGADD() {
        return motengadd;
    }

    /**
     * Sets the value of the motengadd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOTENGADD(String value) {
        this.motengadd = value;
    }

    /**
     * Gets the value of the motrefus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOTREFUS() {
        return motrefus;
    }

    /**
     * Sets the value of the motrefus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOTREFUS(String value) {
        this.motrefus = value;
    }

	public void setIdSamu(String idSamu) {
		//DO nothing
	}

}
