//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.04 at 11:03:05 AM CEST 
//

package bpm.gateway.core.veolia.abonnes;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

import bpm.gateway.core.veolia.VEHelper;

/**
 * <p>
 * Java class for diametresCompteurListe.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="diametresCompteurListe">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="15"/>
 *     &lt;enumeration value="20"/>
 *     &lt;enumeration value="30"/>
 *     &lt;enumeration value="40"/>
 *     &lt;enumeration value="60"/>
 *     &lt;enumeration value="80"/>
 *     &lt;enumeration value="100"/>
 *     &lt;enumeration value="150"/>
 *     &lt;enumeration value="99999"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "diametresCompteurListe")
@XmlEnum
public enum DiametresCompteurListe {

	@XmlEnumValue("15")
	V_15("15"), 
	@XmlEnumValue("20")
	V_20("20"), 
	@XmlEnumValue("30")
	V_30("30"), 
	@XmlEnumValue("40")
	V_40("40"), 
	@XmlEnumValue("60")
	V_60("60"), 
	@XmlEnumValue("80")
	V_80("80"), 
	@XmlEnumValue("100")
	V_100("100"), 
	@XmlEnumValue("150")
	V_150("150"), 
	@XmlEnumValue("99999")
	V_99999("99999"), 
	@XmlEnumValue("NR")
	NR("NR");
	private final String value;

	DiametresCompteurListe(String v) {
		value = v;
	}
	
    public static String getValue(String table, String champ, DiametresCompteurListe v) {
    	if (v == null) {
    		throw new IllegalArgumentException("Table " + table + " - Champs " + champ + " - Valeur 'Null' ou non permise pour la liste.");
    	}
    	return v.value;
    }

	public static DiametresCompteurListe fromValue(String table, String champ, String v) {
		if (v == null) {
    		System.out.println("Table " + table + " - Champs " + champ + " - Valeur 'Null' non permise.");
    		return DiametresCompteurListe.NR;
    	}

		for (DiametresCompteurListe c : DiametresCompteurListe.values()) {
			if (VEHelper.checkEnum(c.value, v)) {
				return c;
			}
		}
		System.out.println("Table " + table + " - Champs " + champ + " - Mauvaise valeur '" + v + "'");
		return DiametresCompteurListe.NR;
	}

}
