//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.04 at 11:03:05 AM CEST 
//


package bpm.gateway.core.veolia.abonnes;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

import bpm.gateway.core.veolia.VEHelper;


/**
 * <p>Java class for modesGestionListe.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="modesGestionListe">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Régie"/>
 *     &lt;enumeration value="Régie avec prestation de service"/>
 *     &lt;enumeration value="Gérance"/>
 *     &lt;enumeration value="Affermage"/>
 *     &lt;enumeration value="Concession"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "modesGestionListe")
@XmlEnum
public enum ModesGestionListe {

    @XmlEnumValue("R\u00e9gie")
    REGIE("R\u00e9gie"),
    @XmlEnumValue("R\u00e9gie avec prestation de service")
    REGIE_AVEC_PRESTATION_DE_SERVICE("R\u00e9gie avec prestation de service"),
    @XmlEnumValue("G\u00e9rance")
    GERANCE("G\u00e9rance"),
    @XmlEnumValue("Affermage")
    AFFERMAGE("Affermage"),
    @XmlEnumValue("Concession")
    CONCESSION("Concession"),
    @XmlEnumValue("NR")
    NR("NR");
    private final String value;

    ModesGestionListe(String v) {
        value = v;
    }
	
    public static String getValue(String table, String champ, ModesGestionListe v) {
    	if (v == null) {
    		throw new IllegalArgumentException("Table " + table + " - Champs " + champ + " - Valeur 'Null' ou non permise pour la liste.");
    	}
    	return v.value;
    }

    public static ModesGestionListe fromValue(String table, String champ, String v) {
    	if (v == null) {
    		System.out.println("Table " + table + " - Champs " + champ + " - Valeur 'Null' non permise.");
    		return ModesGestionListe.NR;
    	}
    	
        for (ModesGestionListe c: ModesGestionListe.values()) {
        	if (VEHelper.checkEnum(c.value, v)) {
        		return c;
        	}
        }
		System.out.println("Table " + table + " - Champs " + champ + " - Mauvaise valeur '" + v + "'");
		return ModesGestionListe.NR;
    }

}
