//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.04 at 11:03:05 AM CEST 
//


package bpm.gateway.core.veolia.abonnes;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

import bpm.gateway.core.veolia.VEHelper;


/**
 * <p>Java class for prisesChargeFSLListe.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="prisesChargeFSLListe">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FSL"/>
 *     &lt;enumeration value="BDF"/>
 *     &lt;enumeration value="RJ"/>
 *     &lt;enumeration value="rien"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "prisesChargeFSLListe")
@XmlEnum
public enum PrisesChargeFSLListe {

    FSL("FSL"),
    BDF("BDF"),
    RJ("RJ"),
    @XmlEnumValue("rien")
    RIEN("rien");
    private final String value;

    PrisesChargeFSLListe(String v) {
        value = v;
    }
	
    public static String getValue(String table, String champ, TypesRemisesImpayesListe v) {
    	if (v == null) {
    		throw new IllegalArgumentException("Table " + table + " - Champs " + champ + " - Valeur 'Null' ou non permise pour la liste.");
    	}
    	return v.name();
    }

    public static PrisesChargeFSLListe fromValue(String v) {
        for (PrisesChargeFSLListe c: PrisesChargeFSLListe.values()) {
        	if (VEHelper.checkEnum(c.value, v)) {
        		return c;
        	}
        }
        throw new IllegalArgumentException(v);
    }

}
