//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.04 at 11:03:05 AM CEST 
//


package bpm.gateway.core.veolia.abonnes;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

import bpm.gateway.core.veolia.VEHelper;


/**
 * <p>Java class for typologiesPointsFournitureListe.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typologiesPointsFournitureListe">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="R"/>
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="X"/>
 *     &lt;enumeration value="D"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="P"/>
 *     &lt;enumeration value="A"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "typologiesPointsFournitureListe")
@XmlEnum
public enum TypologiesPointsFournitureListe {

    I("I"),
    R("R"),
    G("G"),
    X("X"),
    D("D"),
    C("C"),
    P("P"),
    A("A"),
    NR("NR");
	private final String value;

	TypologiesPointsFournitureListe(String v) {
		value = v;
	}

    public static String getValue(String table, String champ, TypologiesPointsFournitureListe v) {
    	if (v == null) {
    		throw new IllegalArgumentException("Table " + table + " - Champs " + champ + " - Valeur 'Null' ou non permise pour la liste.");
    	}
    	return v != null ? v.value : null;
    }

    public static TypologiesPointsFournitureListe fromValue(String table, String champ, String v) {
    	if (v == null) {
    		System.out.println("Table " + table + " - Champs " + champ + " - Valeur 'Null' non permise.");
    		return TypologiesPointsFournitureListe.NR;
    	}

        for (TypologiesPointsFournitureListe c: TypologiesPointsFournitureListe.values()) {
        	if (VEHelper.checkEnum(c.value, v)) {
				return c;
			}
        }
		System.out.println("Table " + table + " - Champs " + champ + " - Mauvaise valeur '" + v + "'");
		return TypologiesPointsFournitureListe.NR;
    }

}
