//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:47:34 AM CET 
//


package bpm.gateway.core.veolia.patrimoine;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

import bpm.gateway.core.veolia.VEHelper;


/**
 * <p>Java class for fluidesPompesListe.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="fluidesPompesListe">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Boues"/>
 *     &lt;enumeration value="Eau chargée"/>
 *     &lt;enumeration value="Eau claire"/>
 *     &lt;enumeration value="Fluide acide"/>
 *     &lt;enumeration value="Fluide basique"/>
 *     &lt;enumeration value="Fluide process"/>
 *     &lt;enumeration value="Graisses"/>
 *     &lt;enumeration value="Sables"/>
 *     &lt;enumeration value="NR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "fluidesPompesListe")
@XmlEnum
public enum FluidesPompesListe {

    @XmlEnumValue("Boues")
    BOUES("Boues"),
    @XmlEnumValue("Eau charg\u00e9e")
    EAU_CHARGEE("Eau charg\u00e9e"),
    @XmlEnumValue("Eau claire")
    EAU_CLAIRE("Eau claire"),
    @XmlEnumValue("Fluide acide")
    FLUIDE_ACIDE("Fluide acide"),
    @XmlEnumValue("Fluide basique")
    FLUIDE_BASIQUE("Fluide basique"),
    @XmlEnumValue("Fluide process")
    FLUIDE_PROCESS("Fluide process"),
    @XmlEnumValue("Graisses")
    GRAISSES("Graisses"),
    @XmlEnumValue("Sables")
    SABLES("Sables"),
    NR("NR");
    private final String value;

    FluidesPompesListe(String v) {
        value = v;
    }
	
    public static String getValue(String table, String champ, FluidesPompesListe v, boolean required) {
    	if (required && v == null) {
    		throw new IllegalArgumentException("Table " + table + " - Champs " + champ + " - Valeur 'Null' ou non permise pour la liste.");
    	}
    	return v != null ? v.value : null;
    }

    public static FluidesPompesListe fromValue(String table, String champ, String v) {
    	if (v == null) {
    		System.out.println("Table " + table + " - Champs " + champ + " - Valeur 'Null' non permise.");
    		return FluidesPompesListe.NR;
    	}
    	
        for (FluidesPompesListe c: FluidesPompesListe.values()) {
        	if (VEHelper.checkEnum(c.value, v)) {
        		return c;
        	}
        }
		System.out.println("Table " + table + " - Champs " + champ + " - Mauvaise valeur '" + v + "'");
		return FluidesPompesListe.NR;
    }

}
