//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.14 at 03:43:22 PM CET 
//


package bpm.gateway.core.veolia.patrimoine;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

import bpm.gateway.core.veolia.VEHelper;


/**
 * <p>Java class for indexMaximumListe.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="indexMaximumListe">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *     &lt;enumeration value="99"/>
 *     &lt;enumeration value="999"/>
 *     &lt;enumeration value="9999"/>
 *     &lt;enumeration value="99999"/>
 *     &lt;enumeration value="999999"/>
 *     &lt;enumeration value="9999999"/>
 *     &lt;enumeration value="99999999"/>
 *     &lt;enumeration value="999999999"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "indexMaximumListe")
@XmlEnum
public enum IndexMaximumListe {

    @XmlEnumValue("99")
    VAL_99(99L),
    @XmlEnumValue("999")
    VAL_999(999L),
    @XmlEnumValue("9999")
    VAL_9999(9999L),
    @XmlEnumValue("99999")
    VAL_99999(99999L),
    @XmlEnumValue("999999")
    VAL_999999(999999L),
    @XmlEnumValue("9999999")
    VAL_9999999(9999999L),
    @XmlEnumValue("99999999")
    VAL_99999999(99999999L),
    @XmlEnumValue("999999999")
    VAL_999999999(999999999L);
    private final Long value;

    IndexMaximumListe(Long v) {
        value = v;
    }
	
    public static Long getValue(String table, String champ, IndexMaximumListe v, boolean required) {
    	if (required && v == null) {
    		throw new IllegalArgumentException("Table " + table + " - Champs " + champ + " - Valeur 'Null' ou non permise pour la liste.");
    	}
    	return v != null ? v.value : null;
    }
    
    public static IndexMaximumListe fromValue(String table, String champ, Long v) {
    	if (v == null) {
    		System.out.println("Table " + table + " - Champs " + champ + " - Valeur 'Null' non permise.");
    		return IndexMaximumListe.VAL_999999999;
    	}
    	
        for (IndexMaximumListe c: IndexMaximumListe.values()) {
        	if (c.value.equals(v)) {
        		return c;
        	}
        }
		System.out.println("Table " + table + " - Champs " + champ + " - Mauvaise valeur '" + v + "'");
		return IndexMaximumListe.VAL_999999999;
    }
}
