//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:47:34 AM CET 
//


package bpm.gateway.core.veolia.patrimoine;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

import bpm.gateway.core.veolia.VEHelper;


/**
 * <p>Java class for ParametresMesuresListe.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ParametresMesuresListe">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Ammonium"/>
 *     &lt;enumeration value="Bruit"/>
 *     &lt;enumeration value="Chlore gazeux"/>
 *     &lt;enumeration value="Chlore résiduel"/>
 *     &lt;enumeration value="Colilert"/>
 *     &lt;enumeration value="Conductivité"/>
 *     &lt;enumeration value="COT"/>
 *     &lt;enumeration value="Couple"/>
 *     &lt;enumeration value="Débit"/>
 *     &lt;enumeration value="Direction du vent"/>
 *     &lt;enumeration value="Energie"/>
 *     &lt;enumeration value="H2S"/>
 *     &lt;enumeration value="Hydrocarbure"/>
 *     &lt;enumeration value="Hydrogene"/>
 *     &lt;enumeration value="Hygrométrie"/>
 *     &lt;enumeration value="Intensité"/>
 *     &lt;enumeration value="Isolement"/>
 *     &lt;enumeration value="MES"/>
 *     &lt;enumeration value="Manganèse"/>
 *     &lt;enumeration value="Métaux lourds"/>
 *     &lt;enumeration value="Multiple"/>
 *     &lt;enumeration value="Nitrates"/>
 *     &lt;enumeration value="Nitrites"/>
 *     &lt;enumeration value="Niveau"/>
 *     &lt;enumeration value="Oxygène"/>
 *     &lt;enumeration value="Ozone"/>
 *     &lt;enumeration value="Particules"/>
 *     &lt;enumeration value="pH"/>
 *     &lt;enumeration value="Pluviométrie"/>
 *     &lt;enumeration value="Poids"/>
 *     &lt;enumeration value="Position"/>
 *     &lt;enumeration value="Pression"/>
 *     &lt;enumeration value="Puissance"/>
 *     &lt;enumeration value="Radioactivité"/>
 *     &lt;enumeration value="Redox"/>
 *     &lt;enumeration value="TAC (Titre Alcalimétrique Complet)"/>
 *     &lt;enumeration value="Température"/>
 *     &lt;enumeration value="Turbidité"/>
 *     &lt;enumeration value="UV"/>
 *     &lt;enumeration value="Vibrations"/>
 *     &lt;enumeration value="Vitesse"/>
 *     &lt;enumeration value="Vitesse du vent"/>
 *     &lt;enumeration value="Voile ou lit de boue"/>
 *     &lt;enumeration value="Volume"/>
 *     &lt;enumeration value="NR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ParametresMesuresListe")
@XmlEnum
public enum ParametresMesuresListe {

    @XmlEnumValue("Ammonium")
    AMMONIUM("Ammonium"),
    @XmlEnumValue("Bruit")
    BRUIT("Bruit"),
    @XmlEnumValue("Chlore gazeux")
    CHLORE_GAZEUX("Chlore gazeux"),
    @XmlEnumValue("Chlore r\u00e9siduel")
    CHLORE_RESIDUEL("Chlore r\u00e9siduel"),
    @XmlEnumValue("Colilert")
    COLILERT("Colilert"),
    @XmlEnumValue("Conductivit\u00e9")
    CONDUCTIVITE("Conductivit\u00e9"),
    COT("COT"),
    @XmlEnumValue("Couple")
    COUPLE("Couple"),
    @XmlEnumValue("D\u00e9bit")
    DEBIT("D\u00e9bit"),
    @XmlEnumValue("Direction du vent")
    DIRECTION_DU_VENT("Direction du vent"),
    @XmlEnumValue("Energie")
    ENERGIE("Energie"),
    @XmlEnumValue("H2S")
    H_2_S("H2S"),
    @XmlEnumValue("Hydrocarbure")
    HYDROCARBURE("Hydrocarbure"),
    @XmlEnumValue("Hydrogene")
    HYDROGENE("Hydrogene"),
    @XmlEnumValue("Hygrom\u00e9trie")
    HYGROMETRIE("Hygrom\u00e9trie"),
    @XmlEnumValue("Intensit\u00e9")
    INTENSITE("Intensit\u00e9"),
    @XmlEnumValue("Isolement")
    ISOLEMENT("Isolement"),
    MES("MES"),
    @XmlEnumValue("Mangan\u00e8se")
    MANGANESE("Mangan\u00e8se"),
    @XmlEnumValue("M\u00e9taux lourds")
    METAUX_LOURDS("M\u00e9taux lourds"),
    @XmlEnumValue("Multiple")
    MULTIPLE("Multiple"),
    @XmlEnumValue("Nitrates")
    NITRATES("Nitrates"),
    @XmlEnumValue("Nitrites")
    NITRITES("Nitrites"),
    @XmlEnumValue("Niveau")
    NIVEAU("Niveau"),
    @XmlEnumValue("Oxyg\u00e8ne")
    OXYGENE("Oxyg\u00e8ne"),
    @XmlEnumValue("Ozone")
    OZONE("Ozone"),
    @XmlEnumValue("Particules")
    PARTICULES("Particules"),
    @XmlEnumValue("pH")
    P_H("pH"),
    @XmlEnumValue("Pluviom\u00e9trie")
    PLUVIOMETRIE("Pluviom\u00e9trie"),
    @XmlEnumValue("Poids")
    POIDS("Poids"),
    @XmlEnumValue("Position")
    POSITION("Position"),
    @XmlEnumValue("Pression")
    PRESSION("Pression"),
    @XmlEnumValue("Puissance")
    PUISSANCE("Puissance"),
    @XmlEnumValue("Radioactivit\u00e9")
    RADIOACTIVITE("Radioactivit\u00e9"),
    @XmlEnumValue("Redox")
    REDOX("Redox"),
    @XmlEnumValue("TAC (Titre Alcalim\u00e9trique Complet)")
    TAC_TITRE_ALCALIMETRIQUE_COMPLET("TAC (Titre Alcalim\u00e9trique Complet)"),
    @XmlEnumValue("Temp\u00e9rature")
    TEMPERATURE("Temp\u00e9rature"),
    @XmlEnumValue("Turbidit\u00e9")
    TURBIDITE("Turbidit\u00e9"),
    UV("UV"),
    @XmlEnumValue("Vibrations")
    VIBRATIONS("Vibrations"),
    @XmlEnumValue("Vitesse")
    VITESSE("Vitesse"),
    @XmlEnumValue("Vitesse du vent")
    VITESSE_DU_VENT("Vitesse du vent"),
    @XmlEnumValue("Voile ou lit de boue")
    VOILE_OU_LIT_DE_BOUE("Voile ou lit de boue"),
    @XmlEnumValue("Volume")
    VOLUME("Volume"),
    NR("NR");
    private final String value;

    ParametresMesuresListe(String v) {
        value = v;
    }
	
    public static String getValue(String table, String champ, ParametresMesuresListe v, boolean required) {
    	if (required && v == null) {
    		throw new IllegalArgumentException("Table " + table + " - Champs " + champ + " - Valeur 'Null' ou non permise pour la liste.");
    	}
    	return v != null ? v.value : null;
    }
    
    public static ParametresMesuresListe fromValue(String table, String champ, String v) {
    	if (v == null) {
    		System.out.println("Table " + table + " - Champs " + champ + " - Valeur 'Null' non permise.");
    		return ParametresMesuresListe.NR;
    	}
    	
        for (ParametresMesuresListe c: ParametresMesuresListe.values()) {
        	if (VEHelper.checkEnum(c.value, v)) {
        		return c;
        	}
        }
		System.out.println("Table " + table + " - Champs " + champ + " - Mauvaise valeur '" + v + "'");
		return ParametresMesuresListe.NR;
    }

}
