//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:47:34 AM CET 
//


package bpm.gateway.core.veolia.patrimoine;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import bpm.gateway.core.veolia.VEHelper;


/**
 * <p>Java class for typeEquipementPortail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeEquipementPortail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eqptportail_eqptsocle_id" type="{}equipementIDType"/>
 *         &lt;element name="eqptportail_descriptif" type="{}stringRestricted3000Type" minOccurs="0"/>
 *         &lt;element name="eqptportail_electrique" type="{}ouiNonListe"/>
 *         &lt;element name="eqptportail_largeur" type="{}decimalDeuxChiffres" minOccurs="0"/>
 *         &lt;element name="eqptportail_hauteur" type="{}decimalDeuxChiffres" minOccurs="0"/>
 *         &lt;element name="eqptportail_classehauteur" type="{}classesHauteurCloturesListe"/>
 *         &lt;element name="eqptportail_materiauconstituant" type="{}materiauxConstituantsListe" minOccurs="0"/>
 *         &lt;element name="eqptportail_typeportail" type="{}typesPortailsListe" minOccurs="0"/>
 *         &lt;element name="eqptportail_conformitesecurite" type="{}ouiNonListe" minOccurs="0"/>
 *         &lt;element name="eqptportail_dateconformitesecurite" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="eqptportail_nbvantaux" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="eqptportail_gyrophare" type="{}ouiNonListe" minOccurs="0"/>
 *         &lt;element name="eqptportail_bouclemagnetique" type="{}ouiNonListe"/>
 *         &lt;element name="eqptportail_systemeouverture" type="{}stringRestricted255Type" minOccurs="0"/>
 *         &lt;element name="eqptportail_badge" type="{}ouiNonListe"/>
 *         &lt;element name="eqptportail_digicode" type="{}ouiNonListe"/>
 *         &lt;element name="eqptportail_pjmaintenance" type="{}stringRestricted3000Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@Access(AccessType.FIELD)
@Table (name = PatrimoineDAO.PAT_EQPT_PORTAIL)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeEquipementPortail", propOrder = {
    "eqptportailEqptsocleId",
    "eqptportailDescriptif",
    "eqptportailElectrique",
    "eqptportailLargeur",
    "eqptportailHauteur",
    "eqptportailClassehauteur",
    "eqptportailMateriauconstituant",
    "eqptportailTypeportail",
    "eqptportailConformitesecurite",
    "eqptportailDateconformitesecurite",
    "eqptportailNbvantaux",
    "eqptportailGyrophare",
    "eqptportailBouclemagnetique",
    "eqptportailSystemeouverture",
    "eqptportailBadge",
    "eqptportailDigicode",
    "eqptportailPjmaintenance"
})
public class TypeEquipementPortail {

	@Id
	@Column(name = "eqptportail_id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@XmlTransient
    protected int id;
	@Transient
    @XmlElement(name = "eqptportail_eqptsocle_id", required = true)
    protected String eqptportailEqptsocleId;
	@Column(name = "eqptportail_descriptif")
    @XmlElement(name = "eqptportail_descriptif", defaultValue = "NR")
    protected String eqptportailDescriptif;
	@Transient
    @XmlElement(name = "eqptportail_electrique", required = true)
    protected OuiNonListe eqptportailElectrique;
	@Column(name = "eqptportail_largeur")
    @XmlElement(name = "eqptportail_largeur")
    protected BigDecimal eqptportailLargeur;
	@Column(name = "eqptportail_hauteur")
    @XmlElement(name = "eqptportail_hauteur")
    protected BigDecimal eqptportailHauteur;
	@Transient
    @XmlElement(name = "eqptportail_classehauteur", required = true)
    protected String eqptportailClassehauteur;
	@Transient
    @XmlElement(name = "eqptportail_materiauconstituant")
    protected MateriauxConstituantsListe eqptportailMateriauconstituant;
	@Transient
    @XmlElement(name = "eqptportail_typeportail")
    protected TypesPortailsListe eqptportailTypeportail;
	@Transient
    @XmlElement(name = "eqptportail_conformitesecurite")
    protected OuiNonListe eqptportailConformitesecurite;
	@Transient
    @XmlElement(name = "eqptportail_dateconformitesecurite")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar eqptportailDateconformitesecurite;
	@Column(name = "eqptportail_nbvantaux")
    @XmlElement(name = "eqptportail_nbvantaux")
    protected Integer eqptportailNbvantaux;
	@Transient
    @XmlElement(name = "eqptportail_gyrophare")
    protected OuiNonListe eqptportailGyrophare;
	@Transient
    @XmlElement(name = "eqptportail_bouclemagnetique", required = true)
    protected OuiNonListe eqptportailBouclemagnetique;
	@Column(name = "eqptportail_systemeouverture")
    @XmlElement(name = "eqptportail_systemeouverture")
    protected String eqptportailSystemeouverture;
	@Transient
    @XmlElement(name = "eqptportail_badge", required = true)
    protected OuiNonListe eqptportailBadge;
	@Transient
    @XmlElement(name = "eqptportail_digicode", required = true)
    protected OuiNonListe eqptportailDigicode;
	@Column(name = "eqptportail_pjmaintenance")
    @XmlElement(name = "eqptportail_pjmaintenance")
    protected String eqptportailPjmaintenance;
	@Column(name = "id_chg")
	@XmlTransient
	private Integer idChg;

    /**
     * Gets the value of the eqptportailEqptsocleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptportail_eqptsocle_id")
    public String getEqptportailEqptsocleId() {
    	if (eqptportailEqptsocleId == null) {
    		manageNullException("eqptportail_eqptsocle_id");
    	}
        return eqptportailEqptsocleId;
    }

    /**
     * Sets the value of the eqptportailEqptsocleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptportailEqptsocleId(String value) {
        this.eqptportailEqptsocleId = value != null ? value : "";
    }

    /**
     * Gets the value of the eqptportailDescriptif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptportailDescriptif() {
        return eqptportailDescriptif;
    }

    /**
     * Sets the value of the eqptportailDescriptif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptportailDescriptif(String value) {
        this.eqptportailDescriptif = value;
    }

    /**
     * Gets the value of the eqptportailElectrique property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptportail_electrique")
    public String getEqptportailElectrique() {
        return OuiNonListe.getValue(PatrimoineDAO.PAT_EQPT_PORTAIL, "eqptportail_electrique", eqptportailElectrique, true);
    }

    /**
     * Sets the value of the eqptportailElectrique property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuiNonListe }
     *     
     */
    public void setEqptportailElectrique(String value) {
        this.eqptportailElectrique = OuiNonListe.fromValue(PatrimoineDAO.PAT_EQPT_PORTAIL, "eqptportail_electrique", value);
    }

    /**
     * Gets the value of the eqptportailLargeur property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEqptportailLargeur() {
        return eqptportailLargeur;
    }

    /**
     * Sets the value of the eqptportailLargeur property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptportailLargeur(BigDecimal value) {
        this.eqptportailLargeur = value;
    }

    /**
     * Gets the value of the eqptportailHauteur property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEqptportailHauteur() {
        return eqptportailHauteur;
    }

    /**
     * Sets the value of the eqptportailHauteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptportailHauteur(BigDecimal value) {
        this.eqptportailHauteur = value;
    }

    /**
     * Gets the value of the eqptportailClassehauteur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptportail_classehauteur")
    public String getEqptportailClassehauteur() {
    	if (eqptportailClassehauteur == null) {
    		manageNullException("eqptportail_classehauteur");
    	}
        return eqptportailClassehauteur;
    }

    /**
     * Sets the value of the eqptportailClassehauteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptportailClassehauteur(String value) {
        this.eqptportailClassehauteur = value != null ? value : "";
    }

    /**
     * Gets the value of the eqptportailMateriauconstituant property.
     * 
     * @return
     *     possible object is
     *     {@link MateriauxConstituantsListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptportail_materiauconstituant")
    public String getEqptportailMateriauconstituant() {
        return MateriauxConstituantsListe.getValue(PatrimoineDAO.PAT_EQPT_PORTAIL, "eqptportail_materiauconstituant", eqptportailMateriauconstituant, false);
    }

    /**
     * Sets the value of the eqptportailMateriauconstituant property.
     * 
     * @param value
     *     allowed object is
     *     {@link MateriauxConstituantsListe }
     *     
     */
    public void setEqptportailMateriauconstituant(String value) {
        this.eqptportailMateriauconstituant = MateriauxConstituantsListe.fromValue(PatrimoineDAO.PAT_EQPT_PORTAIL, "eqptportail_materiauconstituant", value);
    }

    /**
     * Gets the value of the eqptportailTypeportail property.
     * 
     * @return
     *     possible object is
     *     {@link TypesPortailsListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptportail_typeportail")
    public String getEqptportailTypeportail() {
        return TypesPortailsListe.getValue(PatrimoineDAO.PAT_EQPT_PORTAIL, "eqptportail_typeportail", eqptportailTypeportail, false);
    }

    /**
     * Sets the value of the eqptportailTypeportail property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypesPortailsListe }
     *     
     */
    public void setEqptportailTypeportail(String value) {
        this.eqptportailTypeportail = TypesPortailsListe.fromValue(PatrimoineDAO.PAT_EQPT_PORTAIL, "eqptportail_typeportail", value);
    }

    /**
     * Gets the value of the eqptportailConformitesecurite property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptportail_conformitesecurite")
    public String getEqptportailConformitesecurite() {
        return OuiNonListe.getValue(PatrimoineDAO.PAT_EQPT_PORTAIL, "eqptportail_conformitesecurite", eqptportailConformitesecurite, false);
    }

    /**
     * Sets the value of the eqptportailConformitesecurite property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuiNonListe }
     *     
     */
    public void setEqptportailConformitesecurite(String value) {
        this.eqptportailConformitesecurite = OuiNonListe.fromValue(PatrimoineDAO.PAT_EQPT_PORTAIL, "eqptportail_conformitesecurite", value);
    }

    /**
     * Gets the value of the eqptportailDateconformitesecurite property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptportail_dateconformitesecurite")
    public Date getEqptportailDateconformitesecurite() {
        return VEHelper.toDate(eqptportailDateconformitesecurite);
    }

    /**
     * Sets the value of the eqptportailDateconformitesecurite property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEqptportailDateconformitesecurite(XMLGregorianCalendar value) {
        this.eqptportailDateconformitesecurite = value;
    }

    /**
     * Gets the value of the eqptportailNbvantaux property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEqptportailNbvantaux() {
        return eqptportailNbvantaux;
    }

    /**
     * Sets the value of the eqptportailNbvantaux property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEqptportailNbvantaux(Integer value) {
        this.eqptportailNbvantaux = value;
    }

    /**
     * Gets the value of the eqptportailGyrophare property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptportail_gyrophare")
    public String getEqptportailGyrophare() {
        return OuiNonListe.getValue(PatrimoineDAO.PAT_EQPT_PORTAIL, "eqptportail_gyrophare", eqptportailGyrophare, false);
    }

    /**
     * Sets the value of the eqptportailGyrophare property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuiNonListe }
     *     
     */
    public void setEqptportailGyrophare(String value) {
        this.eqptportailGyrophare = OuiNonListe.fromValue(PatrimoineDAO.PAT_EQPT_PORTAIL, "eqptportail_gyrophare", value);
    }

    /**
     * Gets the value of the eqptportailBouclemagnetique property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptportail_bouclemagnetique")
    public String getEqptportailBouclemagnetique() {
        return OuiNonListe.getValue(PatrimoineDAO.PAT_EQPT_PORTAIL, "eqptportail_bouclemagnetique", eqptportailBouclemagnetique, true);
    }

    /**
     * Sets the value of the eqptportailBouclemagnetique property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuiNonListe }
     *     
     */
    public void setEqptportailBouclemagnetique(String value) {
        this.eqptportailBouclemagnetique = OuiNonListe.fromValue(PatrimoineDAO.PAT_EQPT_PORTAIL, "eqptportail_bouclemagnetique", value);
    }

    /**
     * Gets the value of the eqptportailSystemeouverture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptportailSystemeouverture() {
        return eqptportailSystemeouverture;
    }

    /**
     * Sets the value of the eqptportailSystemeouverture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptportailSystemeouverture(String value) {
        this.eqptportailSystemeouverture = value;
    }

    /**
     * Gets the value of the eqptportailBadge property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptportail_badge")
    public String getEqptportailBadge() {
        return OuiNonListe.getValue(PatrimoineDAO.PAT_EQPT_PORTAIL, "eqptportail_badge", eqptportailBadge, true);
    }

    /**
     * Sets the value of the eqptportailBadge property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuiNonListe }
     *     
     */
    public void setEqptportailBadge(String value) {
        this.eqptportailBadge = OuiNonListe.fromValue(PatrimoineDAO.PAT_EQPT_PORTAIL, "eqptportail_badge", value);
    }

    /**
     * Gets the value of the eqptportailDigicode property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptportail_digicode")
    public String getEqptportailDigicode() {
        return OuiNonListe.getValue(PatrimoineDAO.PAT_EQPT_PORTAIL, "eqptportail_digicode", eqptportailDigicode, true);
    }

    /**
     * Sets the value of the eqptportailDigicode property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuiNonListe }
     *     
     */
    public void setEqptportailDigicode(String value) {
        this.eqptportailDigicode = OuiNonListe.fromValue(PatrimoineDAO.PAT_EQPT_PORTAIL, "eqptportail_digicode", value);
    }

    /**
     * Gets the value of the eqptportailPjmaintenance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptportailPjmaintenance() {
        return eqptportailPjmaintenance;
    }

    /**
     * Sets the value of the eqptportailPjmaintenance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptportailPjmaintenance(String value) {
        this.eqptportailPjmaintenance = value;
    }

	public void setIdChg(Integer idChg) {
		this.idChg = idChg;
	}

    private void manageNullException(String champ) {
    	throw new IllegalArgumentException("Table " + PatrimoineDAO.PAT_EQPT_PORTAIL + " - Champs " + champ + " - Valeur 'Null' ou non permise par le XSD.");
	}

}
