//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:47:34 AM CET 
//


package bpm.gateway.core.veolia.patrimoine;

import java.math.BigDecimal;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeEquipementBouteilleChlore complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeEquipementBouteilleChlore">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eqptbouttankchlore_eqptsocle_id" type="{}equipementIDType"/>
 *         &lt;element name="eqptbouttankchlore_descriptif" type="{}stringRestricted3000Type"/>
 *         &lt;element name="eqptbouttankchlore_pdschlore" type="{}decimalDeuxChiffres"/>
 *         &lt;element name="eqptbouttankchlore_volume" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="eqptbouttankchlore_tensionnominale" type="{}tensionsNominalesListe" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@Access(AccessType.FIELD)
@Table (name = PatrimoineDAO.PAT_EQPT_BOUTEILLECHLORE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeEquipementBouteilleChlore", propOrder = {
    "eqptbouttankchloreEqptsocleId",
    "eqptbouttankchloreDescriptif",
    "eqptbouttankchlorePdschlore",
    "eqptbouttankchloreVolume",
    "eqptbouttankchloreTensionnominale"
})
public class TypeEquipementBouteilleChlore {

	@Id
	@Column(name = "eqptbouttankchlore_id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@XmlTransient
    protected int id;
	@Transient
    @XmlElement(name = "eqptbouttankchlore_eqptsocle_id", required = true)
    protected String eqptbouttankchloreEqptsocleId;
	@Transient
    @XmlElement(name = "eqptbouttankchlore_descriptif", required = true, defaultValue = "NR")
    protected String eqptbouttankchloreDescriptif;
	@Transient
    @XmlElement(name = "eqptbouttankchlore_pdschlore", required = true)
    protected BigDecimal eqptbouttankchlorePdschlore;
	@Column(name = "eqptbouttankchlore_volume")
    @XmlElement(name = "eqptbouttankchlore_volume")
    protected Integer eqptbouttankchloreVolume;
	@Transient
    @XmlElement(name = "eqptbouttankchlore_tensionnominale")
    protected TensionsNominalesListe eqptbouttankchloreTensionnominale;
	@Column(name = "id_chg")
	@XmlTransient
	private Integer idChg;

    /**
     * Gets the value of the eqptbouttankchloreEqptsocleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptbouttankchlore_eqptsocle_id")
    public String getEqptbouttankchloreEqptsocleId() {
    	if (eqptbouttankchloreEqptsocleId == null) {
    		manageNullException("eqptbouttankchlore_eqptsocle_id");
    	}
        return eqptbouttankchloreEqptsocleId;
    }

    /**
     * Sets the value of the eqptbouttankchloreEqptsocleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptbouttankchloreEqptsocleId(String value) {
        this.eqptbouttankchloreEqptsocleId = value;
    }

    /**
     * Gets the value of the eqptbouttankchloreDescriptif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptbouttankchlore_descriptif")
    public String getEqptbouttankchloreDescriptif() {
    	if (eqptbouttankchloreDescriptif == null) {
    		manageNullException("eqptbouttankchlore_descriptif");
    	}
        return eqptbouttankchloreDescriptif;
    }

    /**
     * Sets the value of the eqptbouttankchloreDescriptif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptbouttankchloreDescriptif(String value) {
        this.eqptbouttankchloreDescriptif = value;
    }

    /**
     * Gets the value of the eqptbouttankchlorePdschlore property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptbouttankchlore_pdschlore")
    public BigDecimal getEqptbouttankchlorePdschlore() {
    	if (eqptbouttankchlorePdschlore == null) {
    		manageNullException("eqptbouttankchlore_pdschlore");
    	}
        return eqptbouttankchlorePdschlore;
    }

    /**
     * Sets the value of the eqptbouttankchlorePdschlore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptbouttankchlorePdschlore(BigDecimal value) {
        this.eqptbouttankchlorePdschlore = value;
    }

    /**
     * Gets the value of the eqptbouttankchloreVolume property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEqptbouttankchloreVolume() {
        return eqptbouttankchloreVolume;
    }

    /**
     * Sets the value of the eqptbouttankchloreVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEqptbouttankchloreVolume(Integer value) {
        this.eqptbouttankchloreVolume = value;
    }

    /**
     * Gets the value of the eqptbouttankchloreTensionnominale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Access(AccessType.PROPERTY)
	@Column(name = "eqptbouttankchlore_tensionnominale")
    public String getEqptbouttankchloreTensionnominale() {
        return TensionsNominalesListe.getValue(PatrimoineDAO.PAT_EQPT_BOUTEILLECHLORE, "eqptbouttankchlore_tensionnominale", eqptbouttankchloreTensionnominale, false);
    }

    /**
     * Sets the value of the eqptbouttankchloreTensionnominale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptbouttankchloreTensionnominale(String value) {
        this.eqptbouttankchloreTensionnominale = TensionsNominalesListe.fromValue(PatrimoineDAO.PAT_EQPT_BOUTEILLECHLORE, "eqptbouttankchlore_tensionnominale", value);
    }

	public void setIdChg(Integer idChg) {
		this.idChg = idChg;
	}

    private void manageNullException(String champ) {
    	throw new IllegalArgumentException("Table " + PatrimoineDAO.PAT_EQPT_BOUTEILLECHLORE + " - Champs " + champ + " - Valeur 'Null' ou non permise par le XSD.");
	}

}
