//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:47:34 AM CET 
//


package bpm.gateway.core.veolia.patrimoine;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import bpm.gateway.core.veolia.VEHelper;


/**
 * <p>Java class for typeIntervention complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeIntervention">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="intervention_ve_id" type="{}stringRestricted255Type"/>
 *         &lt;element name="intervention_unitesocle_id" type="{}uniteIDType" minOccurs="0"/>
 *         &lt;element name="intervention_eqptsocle_id" type="{}equipementIDType" minOccurs="0"/>
 *         &lt;element name="intervention_intitule" type="{}stringRestricted255Type"/>
 *         &lt;element name="intervention_nature" type="{}naturesInterventionsListe"/>
 *         &lt;element name="intervention_dateprogrammation" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="intervention_daterealisation" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="intervention_duree" type="{}decimalDeuxChiffres" minOccurs="0"/>
 *         &lt;element name="intervention_statut" type="{}statutsInterventionsListe"/>
 *         &lt;element name="intervention_commentaire" type="{}stringRestricted3000Type" minOccurs="0"/>
 *         &lt;element name="intervention_pjbonintervention" type="{}stringRestricted3000Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@Access(AccessType.FIELD)
@Table (name = PatrimoineDAO.PAT_EQPT_INTERVENTION)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeIntervention", propOrder = {
    "interventionVeId",
    "interventionUnitesocleId",
    "interventionEqptsocleId",
    "interventionIntitule",
    "interventionNature",
    "interventionDateprogrammation",
    "interventionDaterealisation",
    "interventionDuree",
    "interventionStatut",
    "interventionCommentaire",
    "interventionPjbonintervention"
})
public class TypeIntervention {

	@Id
	@Column(name = "intervention_id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@XmlTransient
    protected int id;
	@Transient
    @XmlElement(name = "intervention_ve_id", required = true, defaultValue = "NR")
    protected String interventionVeId;
	@Column(name = "intervention_unitesocle_id")
    @XmlElement(name = "intervention_unitesocle_id")
    protected String interventionUnitesocleId;
	@Column(name = "intervention_eqptsocle_id")
    @XmlElement(name = "intervention_eqptsocle_id")
    protected String interventionEqptsocleId;
	@Transient
    @XmlElement(name = "intervention_intitule", required = true, defaultValue = "NR")
    protected String interventionIntitule;
	@Transient
    @XmlElement(name = "intervention_nature", required = true)
    protected NaturesInterventionsListe interventionNature;
	@Transient
    @XmlElement(name = "intervention_dateprogrammation", defaultValue = "1901-01-01")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar interventionDateprogrammation;
	@Transient
    @XmlElement(name = "intervention_daterealisation", required = true, defaultValue = "1901-01-01")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar interventionDaterealisation;
	@Column(name = "intervention_duree")
    @XmlElement(name = "intervention_duree")
    protected BigDecimal interventionDuree;
	@Transient
    @XmlElement(name = "intervention_statut", required = true)
    protected StatutsInterventionsListe interventionStatut;
	@Column(name = "intervention_commentaire")
    @XmlElement(name = "intervention_commentaire", defaultValue = "NR")
    protected String interventionCommentaire;
	@Transient
    @XmlElement(name = "intervention_pjbonintervention", required = true, defaultValue = "NR")
    protected String interventionPjbonintervention;
	@Column(name = "id_chg")
	@XmlTransient
	private Integer idChg;

    /**
     * Gets the value of the interventionVeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "intervention_ve_id")
    public String getInterventionVeId() {
    	if (interventionVeId == null) {
    		manageNullException("intervention_ve_id");
    	}
        return interventionVeId;
    }

    /**
     * Sets the value of the interventionVeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterventionVeId(String value) {
        this.interventionVeId = value;
    }

    /**
     * Gets the value of the interventionUnitesocleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterventionUnitesocleId() {
        return interventionUnitesocleId;
    }

    /**
     * Sets the value of the interventionUnitesocleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterventionUnitesocleId(String value) {
        this.interventionUnitesocleId = value;
    }

    /**
     * Gets the value of the interventionEqptsocleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterventionEqptsocleId() {
        return interventionEqptsocleId;
    }

    /**
     * Sets the value of the interventionEqptsocleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterventionEqptsocleId(String value) {
        this.interventionEqptsocleId = value;
    }

    /**
     * Gets the value of the interventionIntitule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "intervention_intitule")
    public String getInterventionIntitule() {
    	if (interventionIntitule == null) {
    		manageNullException("intervention_intitule");
    	}
        return interventionIntitule;
    }

    /**
     * Sets the value of the interventionIntitule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterventionIntitule(String value) {
        this.interventionIntitule = value;
    }

    /**
     * Gets the value of the interventionNature property.
     * 
     * @return
     *     possible object is
     *     {@link NaturesInterventionsListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "intervention_nature")
    public String getInterventionNature() {
        return NaturesInterventionsListe.getValue(PatrimoineDAO.PAT_EQPT_INTERVENTION, "intervention_nature", interventionNature);
    }

    /**
     * Sets the value of the interventionNature property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturesInterventionsListe }
     *     
     */
    public void setInterventionNature(String value) {
        this.interventionNature = NaturesInterventionsListe.fromValue(PatrimoineDAO.PAT_EQPT_INTERVENTION, "intervention_nature", value);
    }

    /**
     * Gets the value of the interventionDateprogrammation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "intervention_dateprogrammation")
    public Date getInterventionDateprogrammation() {
        return VEHelper.toDate(interventionDateprogrammation);
    }

    /**
     * Sets the value of the interventionDateprogrammation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInterventionDateprogrammation(XMLGregorianCalendar value) {
        this.interventionDateprogrammation = value;
    }

    /**
     * Sets the value of the interventionDateprogrammation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInterventionDateprogrammation(Date value) {
        this.interventionDateprogrammation = VEHelper.fromDate(value);
    }

    /**
     * Gets the value of the interventionDaterealisation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "intervention_daterealisation")
    public Date getInterventionDaterealisation() {
    	if (interventionDaterealisation == null) {
    		manageNullException("intervention_daterealisation");
    	}
        return VEHelper.toDate(interventionDaterealisation);
    }

    /**
     * Sets the value of the interventionDaterealisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInterventionDaterealisation(XMLGregorianCalendar value) {
        this.interventionDaterealisation = value;
    }

    /**
     * Sets the value of the interventionDaterealisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInterventionDaterealisation(Date value) {
        this.interventionDaterealisation = VEHelper.fromDate(value);
    }

    /**
     * Gets the value of the interventionDuree property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInterventionDuree() {
        return interventionDuree;
    }

    /**
     * Sets the value of the interventionDuree property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInterventionDuree(BigDecimal value) {
        this.interventionDuree = value;
    }

    /**
     * Gets the value of the interventionStatut property.
     * 
     * @return
     *     possible object is
     *     {@link StatutsInterventionsListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "intervention_statut")
    public String getInterventionStatut() {
        return StatutsInterventionsListe.getValue(PatrimoineDAO.PAT_EQPT_INTERVENTION, "intervention_statut", interventionStatut);
    }

    /**
     * Sets the value of the interventionStatut property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatutsInterventionsListe }
     *     
     */
    public void setInterventionStatut(String value) {
        this.interventionStatut = StatutsInterventionsListe.fromValue(PatrimoineDAO.PAT_EQPT_INTERVENTION, "intervention_statut", value);
    }

    /**
     * Gets the value of the interventionCommentaire property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterventionCommentaire() {
        return interventionCommentaire;
    }

    /**
     * Sets the value of the interventionCommentaire property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterventionCommentaire(String value) {
        this.interventionCommentaire = value;
    }

    /**
     * Gets the value of the interventionPjbonintervention property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "intervention_pjbonintervention")
    public String getInterventionPjbonintervention() {
    	if (interventionPjbonintervention == null) {
    		manageNullException("intervention_pjbonintervention");
    	}
        return interventionPjbonintervention;
    }

    /**
     * Sets the value of the interventionPjbonintervention property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterventionPjbonintervention(String value) {
        this.interventionPjbonintervention = value;
    }

	public void setIdChg(Integer idChg) {
		this.idChg = idChg;
	}

    private void manageNullException(String champ) {
    	throw new IllegalArgumentException("Table " + PatrimoineDAO.PAT_EQPT_INTERVENTION + " - Champs " + champ + " - Valeur 'Null' ou non permise par le XSD.");
	}

}
