//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:47:34 AM CET 
//


package bpm.gateway.core.veolia.patrimoine;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeEquipementMaterielLaboratoire complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeEquipementMaterielLaboratoire">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eqptmaterlabo_eqptsocle_id" type="{}equipementIDType"/>
 *         &lt;element name="eqptmaterlabo_descriptif" type="{}stringRestricted3000Type" minOccurs="0"/>
 *         &lt;element name="eqptmaterlabo_fonctioncable" type="{}parametresMesuresListe" minOccurs="0"/>
 *         &lt;element name="eqptmaterlabo_pjetalonnage" type="{}stringRestricted3000Type" minOccurs="0"/>
 *         &lt;element name="eqptmaterlabo_pjfichetechnique" type="{}stringRestricted3000Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@Access(AccessType.FIELD)
@Table (name = PatrimoineDAO.PAT_EQPT_MATERIELLABORATOIRE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeEquipementMaterielLaboratoire", propOrder = {
    "eqptmaterlaboEqptsocleId",
    "eqptmaterlaboDescriptif",
    "eqptmaterlaboFonctioncable",
    "eqptmaterlaboPjetalonnage",
    "eqptmaterlaboPjfichetechnique"
})
public class TypeEquipementMaterielLaboratoire {

	@Id
	@Column(name = "eqptmaterlabo_id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@XmlTransient
    protected int id;
	@Transient
    @XmlElement(name = "eqptmaterlabo_eqptsocle_id", required = true)
    protected String eqptmaterlaboEqptsocleId;
	@Column(name = "eqptmaterlabo_descriptif")
    @XmlElement(name = "eqptmaterlabo_descriptif", defaultValue = "NR")
    protected String eqptmaterlaboDescriptif;
	@Transient
    @XmlElement(name = "eqptmaterlabo_fonctioncable")
    protected ParametresMesuresListe eqptmaterlaboFonctioncable;
	@Column(name = "eqptmaterlabo_pjetalonnage")
    @XmlElement(name = "eqptmaterlabo_pjetalonnage")
    protected String eqptmaterlaboPjetalonnage;
	@Column(name = "eqptmaterlabo_pjfichetechnique")
    @XmlElement(name = "eqptmaterlabo_pjfichetechnique")
    protected String eqptmaterlaboPjfichetechnique;
	@Column(name = "id_chg")
	@XmlTransient
	private Integer idChg;

    /**
     * Gets the value of the eqptmaterlaboEqptsocleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptmaterlabo_eqptsocle_id")
    public String getEqptmaterlaboEqptsocleId() {
    	if (eqptmaterlaboEqptsocleId == null) {
    		manageNullException("eqptmaterlabo_eqptsocle_id");
    	}
        return eqptmaterlaboEqptsocleId;
    }

    /**
     * Sets the value of the eqptmaterlaboEqptsocleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptmaterlaboEqptsocleId(String value) {
        this.eqptmaterlaboEqptsocleId = value;
    }

    /**
     * Gets the value of the eqptmaterlaboDescriptif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptmaterlaboDescriptif() {
        return eqptmaterlaboDescriptif;
    }

    /**
     * Sets the value of the eqptmaterlaboDescriptif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptmaterlaboDescriptif(String value) {
        this.eqptmaterlaboDescriptif = value;
    }

    /**
     * Gets the value of the eqptmaterlaboFonctioncable property.
     * 
     * @return
     *     possible object is
     *     {@link ParametresMesuresListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptmaterlabo_fonctioncable")
    public String getEqptmaterlaboFonctioncable() {
        return ParametresMesuresListe.getValue(PatrimoineDAO.PAT_EQPT_MATERIELLABORATOIRE, "eqptmaterlabo_fonctioncable", eqptmaterlaboFonctioncable, false);
    }

    /**
     * Sets the value of the eqptmaterlaboFonctioncable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametresMesuresListe }
     *     
     */
    public void setEqptmaterlaboFonctioncable(String value) {
        this.eqptmaterlaboFonctioncable = ParametresMesuresListe.fromValue(PatrimoineDAO.PAT_EQPT_MATERIELLABORATOIRE, "eqptmaterlabo_fonctioncable", value);
    }

    /**
     * Gets the value of the eqptmaterlaboPjetalonnage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptmaterlaboPjetalonnage() {
        return eqptmaterlaboPjetalonnage;
    }

    /**
     * Sets the value of the eqptmaterlaboPjetalonnage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptmaterlaboPjetalonnage(String value) {
        this.eqptmaterlaboPjetalonnage = value;
    }

    /**
     * Gets the value of the eqptmaterlaboPjfichetechnique property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptmaterlaboPjfichetechnique() {
        return eqptmaterlaboPjfichetechnique;
    }

    /**
     * Sets the value of the eqptmaterlaboPjfichetechnique property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptmaterlaboPjfichetechnique(String value) {
        this.eqptmaterlaboPjfichetechnique = value;
    }

	public void setIdChg(Integer idChg) {
		this.idChg = idChg;
	}

    private void manageNullException(String champ) {
    	throw new IllegalArgumentException("Table " + PatrimoineDAO.PAT_EQPT_MATERIELLABORATOIRE + " - Champs " + champ + " - Valeur 'Null' ou non permise par le XSD.");
	}

}
