//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:47:34 AM CET 
//


package bpm.gateway.core.veolia.patrimoine;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeEquipementAutomate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeEquipementAutomate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eqptautomprogindus_eqptsocle_id" type="{}equipementIDType"/>
 *         &lt;element name="eqptautomprogindus_descriptif" type="{}stringRestricted3000Type"/>
 *         &lt;element name="eqptautomprogindus_supportcomm" type="{}supportsCommunicationListe"/>
 *         &lt;element name="eqptautomprogindus_nbcartes" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eqptautomprogindus_typecarte" type="{}stringRestricted3000Type"/>
 *         &lt;element name="eqptautomprogindus_capacite" type="{}stringRestricted3000Type"/>
 *         &lt;element name="eqptautomprogindus_nbentreesortieana" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eqptautomprogindus_nbentreesortieanautil" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eqptautomprogindus_nbentreesortietor" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eqptautomprogindus_nbentreesortietorutil" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eqptautomprogindus_pjfichetechnique" type="{}stringRestricted3000Type" minOccurs="1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@Access(AccessType.FIELD)
@Table (name = PatrimoineDAO.PAT_EQPT_AUTOMATE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeEquipementAutomate", propOrder = {
    "eqptautomprogindusEqptsocleId",
    "eqptautomprogindusDescriptif",
    "eqptautomprogindusSupportcomm",
    "eqptautomprogindusNbcartes",
    "eqptautomprogindusTypecarte",
    "eqptautomprogindusCapacite",
    "eqptautomprogindusNbentreesortieana",
    "eqptautomprogindusNbentreesortieanautil",
    "eqptautomprogindusNbentreesortietor",
    "eqptautomprogindusNbentreesortietorutil",
    "eqptautomprogindusPjfichetechnique"
})
public class TypeEquipementAutomate {

	@Id
	@Column(name = "eqptautomprogindus_id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@XmlTransient
    protected int id;
	@Transient
    @XmlElement(name = "eqptautomprogindus_eqptsocle_id", required = true)
    protected String eqptautomprogindusEqptsocleId;
	@Transient
    @XmlElement(name = "eqptautomprogindus_descriptif", required = true, defaultValue = "NR")
    protected String eqptautomprogindusDescriptif;
	@Transient
    @XmlElement(name = "eqptautomprogindus_supportcomm", required = true)
    protected SupportsCommunicationListe eqptautomprogindusSupportcomm;
	@Transient
    @XmlElement(name = "eqptautomprogindus_nbcartes")
    protected Integer eqptautomprogindusNbcartes;
	@Transient
    @XmlElement(name = "eqptautomprogindus_typecarte", required = true, defaultValue = "NR")
    protected String eqptautomprogindusTypecarte;
	@Transient
    @XmlElement(name = "eqptautomprogindus_capacite", required = true, defaultValue = "NR")
    protected String eqptautomprogindusCapacite;
	@Transient
    @XmlElement(name = "eqptautomprogindus_nbentreesortieana")
    protected Integer eqptautomprogindusNbentreesortieana;
	@Transient
    @XmlElement(name = "eqptautomprogindus_nbentreesortieanautil")
    protected Integer eqptautomprogindusNbentreesortieanautil;
	@Transient
    @XmlElement(name = "eqptautomprogindus_nbentreesortietor")
    protected Integer eqptautomprogindusNbentreesortietor;
	@Transient
    @XmlElement(name = "eqptautomprogindus_nbentreesortietorutil")
    protected Integer eqptautomprogindusNbentreesortietorutil;
	@Transient
    @XmlElement(name = "eqptautomprogindus_pjfichetechnique")
    protected String eqptautomprogindusPjfichetechnique;
	@Column(name = "id_chg")
	@XmlTransient
	private Integer idChg;

    /**
     * Gets the value of the eqptautomprogindusEqptsocleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptautomprogindus_eqptsocle_id")
    public String getEqptautomprogindusEqptsocleId() {
    	if (eqptautomprogindusEqptsocleId == null) {
    		manageNullException("eqptautomprogindus_eqptsocle_id");
    	}
        return eqptautomprogindusEqptsocleId;
    }

    /**
     * Sets the value of the eqptautomprogindusEqptsocleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptautomprogindusEqptsocleId(String value) {
        this.eqptautomprogindusEqptsocleId = value;
    }

    /**
     * Gets the value of the eqptautomprogindusDescriptif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptautomprogindus_descriptif")
    public String getEqptautomprogindusDescriptif() {
    	if (eqptautomprogindusDescriptif == null) {
    		manageNullException("eqptautomprogindus_descriptif");
    	}
        return eqptautomprogindusDescriptif;
    }

    /**
     * Sets the value of the eqptautomprogindusDescriptif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptautomprogindusDescriptif(String value) {
        this.eqptautomprogindusDescriptif = value;
    }

    /**
     * Gets the value of the eqptautomprogindusSupportcomm property.
     * 
     * @return
     *     possible object is
     *     {@link SupportsCommunicationListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptautomprogindus_supportcomm")
    public String getEqptautomprogindusSupportcomm() {
        return SupportsCommunicationListe.getValue(PatrimoineDAO.PAT_EQPT_AUTOMATE, "eqptautomprogindus_supportcomm", eqptautomprogindusSupportcomm, true);
    }

    /**
     * Sets the value of the eqptautomprogindusSupportcomm property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportsCommunicationListe }
     *     
     */
    public void setEqptautomprogindusSupportcomm(String value) {
        this.eqptautomprogindusSupportcomm = SupportsCommunicationListe.fromValue(PatrimoineDAO.PAT_EQPT_AUTOMATE, "eqptautomprogindus_supportcomm", value);
    }

    /**
     * Gets the value of the eqptautomprogindusNbcartes property.
     * 
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptautomprogindus_nbcartes")
    public int getEqptautomprogindusNbcartes() {
    	if (eqptautomprogindusNbcartes == null) {
    		manageNullException("eqptautomprogindus_nbcartes");
    	}
        return eqptautomprogindusNbcartes;
    }

    /**
     * Sets the value of the eqptautomprogindusNbcartes property.
     * 
     */
    public void setEqptautomprogindusNbcartes(int value) {
        this.eqptautomprogindusNbcartes = value;
    }

    /**
     * Gets the value of the eqptautomprogindusTypecarte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptautomprogindus_typecarte")
    public String getEqptautomprogindusTypecarte() {
    	if (eqptautomprogindusTypecarte == null) {
    		manageNullException("eqptautomprogindus_typecarte");
    	}
        return eqptautomprogindusTypecarte;
    }

    /**
     * Sets the value of the eqptautomprogindusTypecarte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptautomprogindusTypecarte(String value) {
        this.eqptautomprogindusTypecarte = value;
    }

    /**
     * Gets the value of the eqptautomprogindusCapacite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptautomprogindus_capacite")
    public String getEqptautomprogindusCapacite() {
    	if (eqptautomprogindusCapacite == null) {
    		manageNullException("eqptautomprogindus_capacite");
    	}
        return eqptautomprogindusCapacite;
    }

    /**
     * Sets the value of the eqptautomprogindusCapacite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptautomprogindusCapacite(String value) {
        this.eqptautomprogindusCapacite = value;
    }

    /**
     * Gets the value of the eqptautomprogindusNbentreesortieana property.
     * 
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptautomprogindus_nbentreesortieana")
    public int getEqptautomprogindusNbentreesortieana() {
    	if (eqptautomprogindusNbentreesortieana == null) {
    		manageNullException("eqptautomprogindus_nbentreesortieana");
    	}
        return eqptautomprogindusNbentreesortieana;
    }

    /**
     * Sets the value of the eqptautomprogindusNbentreesortieana property.
     * 
     */
    public void setEqptautomprogindusNbentreesortieana(int value) {
        this.eqptautomprogindusNbentreesortieana = value;
    }

    /**
     * Gets the value of the eqptautomprogindusNbentreesortieanautil property.
     * 
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptautomprogindus_nbentreesortieanautil")
    public int getEqptautomprogindusNbentreesortieanautil() {
    	if (eqptautomprogindusNbentreesortieanautil == null) {
    		manageNullException("eqptautomprogindus_nbentreesortieanautil");
    	}
        return eqptautomprogindusNbentreesortieanautil;
    }

    /**
     * Sets the value of the eqptautomprogindusNbentreesortieanautil property.
     * 
     */
    public void setEqptautomprogindusNbentreesortieanautil(int value) {
        this.eqptautomprogindusNbentreesortieanautil = value;
    }

    /**
     * Gets the value of the eqptautomprogindusNbentreesortietor property.
     * 
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptautomprogindus_nbentreesortietor")
    public int getEqptautomprogindusNbentreesortietor() {
    	if (eqptautomprogindusNbentreesortietor == null) {
    		manageNullException("eqptautomprogindus_nbentreesortietor");
    	}
        return eqptautomprogindusNbentreesortietor;
    }

    /**
     * Sets the value of the eqptautomprogindusNbentreesortietor property.
     * 
     */
    public void setEqptautomprogindusNbentreesortietor(int value) {
        this.eqptautomprogindusNbentreesortietor = value;
    }

    /**
     * Gets the value of the eqptautomprogindusNbentreesortietorutil property.
     * 
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptautomprogindus_nbentreesortietorutil")
    public int getEqptautomprogindusNbentreesortietorutil() {
    	if (eqptautomprogindusNbentreesortietorutil == null) {
    		manageNullException("eqptautomprogindus_nbentreesortietorutil");
    	}
        return eqptautomprogindusNbentreesortietorutil;
    }

    /**
     * Sets the value of the eqptautomprogindusNbentreesortietorutil property.
     * 
     */
    public void setEqptautomprogindusNbentreesortietorutil(int value) {
        this.eqptautomprogindusNbentreesortietorutil = value;
    }

    /**
     * Gets the value of the eqptautomprogindusPjfichetechnique property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptautomprogindus_pjfichetechnique")
    public String getEqptautomprogindusPjfichetechnique() {
		if (eqptautomprogindusPjfichetechnique == null) {
    		manageNullException("eqptautomprogindus_pjfichetechnique");
    	}
        return eqptautomprogindusPjfichetechnique;
    }

    /**
     * Sets the value of the eqptautomprogindusPjfichetechnique property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptautomprogindusPjfichetechnique(String value) {
        this.eqptautomprogindusPjfichetechnique = value;
    }

	public void setIdChg(Integer idChg) {
		this.idChg = idChg;
	}

    private void manageNullException(String champ) {
    	throw new IllegalArgumentException("Table " + PatrimoineDAO.PAT_EQPT_AUTOMATE + " - Champs " + champ + " - Valeur 'Null' ou non permise par le XSD.");
	}

}
