//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:47:34 AM CET 
//


package bpm.gateway.core.veolia.patrimoine;

import java.math.BigDecimal;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeEquipementOzoneur complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeEquipementOzoneur">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eqptozoneur_eqptsocle_id" type="{}equipementIDType"/>
 *         &lt;element name="eqptozoneur_descriptif" type="{}stringRestricted3000Type"/>
 *         &lt;element name="eqptozoneur_gazprimaire" type="{}gazPrimairesListe" minOccurs="0"/>
 *         &lt;element name="eqptozoneur_puissance" type="{}decimalDeuxChiffres"/>
 *         &lt;element name="eqptozoneur_puissancewatt" type="{}decimalDeuxChiffres"/>
 *         &lt;element name="eqptozoneur_tensionnominale" type="{}tensionsNominalesListe"/>
 *         &lt;element name="eqptozoneur_capacite" type="{}decimalDeuxChiffres"/>
 *         &lt;element name="eqptozoneur_frequence" type="{}decimalDeuxChiffres"/>
 *         &lt;element name="eqptozoneur_pressionnominale" type="{}pressionsNominalesListe"/>
 *         &lt;element name="eqptozoneur_nbtube" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eqptozoneur_materiauconstituant" type="{}materiauxConstituantsListe"/>
 *         &lt;element name="eqptozoneur_dimension" type="{}decimalDeuxChiffres"/>
 *         &lt;element name="eqptozoneur_typediffuseur" type="{}typesDiffuseursListe"/>
 *         &lt;element name="eqptozoneur_longueur" type="{}decimalDeuxChiffres" minOccurs="0"/>
 *         &lt;element name="eqptozoneur_capacite2" type="{}decimalDeuxChiffres"/>
 *         &lt;element name="eqptozoneur_diametremm" type="{}decimalDeuxChiffres"/>
 *         &lt;element name="eqptozoneur_pjmaintenance" type="{}stringRestricted3000Type" minOccurs="0"/>
 *         &lt;element name="eqptozoneur_pjfichetechnique" type="{}stringRestricted3000Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@Access(AccessType.FIELD)
@Table (name = PatrimoineDAO.PAT_EQPT_OZONEUR)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeEquipementOzoneur", propOrder = {
    "eqptozoneurEqptsocleId",
    "eqptozoneurDescriptif",
    "eqptozoneurGazprimaire",
    "eqptozoneurPuissance",
    "eqptozoneurPuissancewatt",
    "eqptozoneurTensionnominale",
    "eqptozoneurCapacite",
    "eqptozoneurFrequence",
    "eqptozoneurPressionnominale",
    "eqptozoneurNbtube",
    "eqptozoneurMateriauconstituant",
    "eqptozoneurDimension",
    "eqptozoneurTypediffuseur",
    "eqptozoneurLongueur",
    "eqptozoneurCapacite2",
    "eqptozoneurDiametremm",
    "eqptozoneurPjmaintenance",
    "eqptozoneurPjfichetechnique"
})
public class TypeEquipementOzoneur {

	@Id
	@Column(name = "eqptozoneur_id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@XmlTransient
    protected int id;
	@Transient
    @XmlElement(name = "eqptozoneur_eqptsocle_id", required = true)
    protected String eqptozoneurEqptsocleId;
	@Transient
    @XmlElement(name = "eqptozoneur_descriptif", required = true, defaultValue = "NR")
    protected String eqptozoneurDescriptif;
	@Transient
    @XmlElement(name = "eqptozoneur_gazprimaire")
    protected GazPrimairesListe eqptozoneurGazprimaire;
	@Transient
    @XmlElement(name = "eqptozoneur_puissance", required = true)
    protected BigDecimal eqptozoneurPuissance;
	@Transient
    @XmlElement(name = "eqptozoneur_puissancewatt", required = true)
    protected BigDecimal eqptozoneurPuissancewatt;
	@Transient
    @XmlElement(name = "eqptozoneur_tensionnominale", required = true)
    protected TensionsNominalesListe eqptozoneurTensionnominale;
	@Transient
    @XmlElement(name = "eqptozoneur_capacite", required = true)
    protected BigDecimal eqptozoneurCapacite;
	@Transient
    @XmlElement(name = "eqptozoneur_frequence", required = true)
    protected BigDecimal eqptozoneurFrequence;
	@Transient
    @XmlElement(name = "eqptozoneur_pressionnominale", required = true)
    protected PressionsNominalesListe eqptozoneurPressionnominale;
	@Transient
    @XmlElement(name = "eqptozoneur_nbtube")
    protected Integer eqptozoneurNbtube;
	@Transient
    @XmlElement(name = "eqptozoneur_materiauconstituant", required = true)
    protected MateriauxConstituantsListe eqptozoneurMateriauconstituant;
	@Transient
    @XmlElement(name = "eqptozoneur_dimension", required = true)
    protected String eqptozoneurDimension;
	@Transient
    @XmlElement(name = "eqptozoneur_typediffuseur", required = true)
    protected TypesDiffuseursListe eqptozoneurTypediffuseur;
	@Column(name = "eqptozoneur_longueur")
    @XmlElement(name = "eqptozoneur_longueur")
    protected BigDecimal eqptozoneurLongueur;
	@Transient
    @XmlElement(name = "eqptozoneur_capacite2", required = true)
    protected BigDecimal eqptozoneurCapacite2;
	@Transient
    @XmlElement(name = "eqptozoneur_diametremm", required = true)
    protected BigDecimal eqptozoneurDiametremm;
	@Column(name = "eqptozoneur_pjmaintenance")
    @XmlElement(name = "eqptozoneur_pjmaintenance")
    protected String eqptozoneurPjmaintenance;
	@Column(name = "eqptozoneur_pjfichetechnique")
    @XmlElement(name = "eqptozoneur_pjfichetechnique")
    protected String eqptozoneurPjfichetechnique;
	@Column(name = "id_chg")
	@XmlTransient
	private Integer idChg;

    /**
     * Gets the value of the eqptozoneurEqptsocleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptozoneur_eqptsocle_id")
    public String getEqptozoneurEqptsocleId() {
    	if (eqptozoneurEqptsocleId == null) {
    		manageNullException("eqptozoneur_eqptsocle_id");
    	}
        return eqptozoneurEqptsocleId;
    }

    /**
     * Sets the value of the eqptozoneurEqptsocleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptozoneurEqptsocleId(String value) {
        this.eqptozoneurEqptsocleId = value;
    }

    /**
     * Gets the value of the eqptozoneurDescriptif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptozoneur_descriptif")
    public String getEqptozoneurDescriptif() {
    	if (eqptozoneurDescriptif == null) {
    		manageNullException("eqptozoneur_descriptif");
    	}
        return eqptozoneurDescriptif;
    }

    /**
     * Sets the value of the eqptozoneurDescriptif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptozoneurDescriptif(String value) {
        this.eqptozoneurDescriptif = value;
    }

    /**
     * Gets the value of the eqptozoneurGazprimaire property.
     * 
     * @return
     *     possible object is
     *     {@link GazPrimairesListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptozoneur_gazprimaire")
    public String getEqptozoneurGazprimaire() {
        return GazPrimairesListe.getValue(PatrimoineDAO.PAT_EQPT_OZONEUR, "eqptozoneur_gazprimaire", eqptozoneurGazprimaire, false);
    }

    /**
     * Sets the value of the eqptozoneurGazprimaire property.
     * 
     * @param value
     *     allowed object is
     *     {@link GazPrimairesListe }
     *     
     */
    public void setEqptozoneurGazprimaire(String value) {
        this.eqptozoneurGazprimaire = GazPrimairesListe.fromValue(PatrimoineDAO.PAT_EQPT_OZONEUR, "eqptozoneur_gazprimaire", value);
    }

    /**
     * Gets the value of the eqptozoneurPuissance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptozoneur_puissance")
    public BigDecimal getEqptozoneurPuissance() {
    	if (eqptozoneurPuissance == null) {
    		manageNullException("eqptozoneur_puissance");
    	}
        return eqptozoneurPuissance;
    }

    /**
     * Sets the value of the eqptozoneurPuissance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptozoneurPuissance(BigDecimal value) {
        this.eqptozoneurPuissance = value;
    }

    /**
     * Gets the value of the eqptozoneurPuissancewatt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptozoneur_puissancewatt")
    public BigDecimal getEqptozoneurPuissancewatt() {
    	if (eqptozoneurPuissancewatt == null) {
    		manageNullException("eqptozoneur_puissancewatt");
    	}
        return eqptozoneurPuissancewatt;
    }

    /**
     * Sets the value of the eqptozoneurPuissancewatt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptozoneurPuissancewatt(BigDecimal value) {
        this.eqptozoneurPuissancewatt = value;
    }

    /**
     * Gets the value of the eqptozoneurTensionnominale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptozoneur_tensionnominale")
    public String getEqptozoneurTensionnominale() {
        return TensionsNominalesListe.getValue(PatrimoineDAO.PAT_EQPT_OZONEUR, "eqptozoneur_tensionnominale", eqptozoneurTensionnominale, true);
    }

    /**
     * Sets the value of the eqptozoneurTensionnominale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptozoneurTensionnominale(String value) {
        this.eqptozoneurTensionnominale = TensionsNominalesListe.fromValue(PatrimoineDAO.PAT_EQPT_OZONEUR, "eqptozoneur_tensionnominale", value);
    }

    /**
     * Gets the value of the eqptozoneurCapacite property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptozoneur_capacite")
    public BigDecimal getEqptozoneurCapacite() {
    	if (eqptozoneurCapacite == null) {
    		manageNullException("eqptozoneur_capacite");
    	}
        return eqptozoneurCapacite;
    }

    /**
     * Sets the value of the eqptozoneurCapacite property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptozoneurCapacite(BigDecimal value) {
        this.eqptozoneurCapacite = value;
    }

    /**
     * Gets the value of the eqptozoneurFrequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptozoneur_frequence")
    public BigDecimal getEqptozoneurFrequence() {
    	if (eqptozoneurFrequence == null) {
    		manageNullException("eqptozoneur_frequence");
    	}
        return eqptozoneurFrequence;
    }

    /**
     * Sets the value of the eqptozoneurFrequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptozoneurFrequence(BigDecimal value) {
        this.eqptozoneurFrequence = value;
    }

    /**
     * Gets the value of the eqptozoneurPressionnominale property.
     * 
     * @return
     *     possible object is
     *     {@link PressionsNominalesListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptozoneur_pressionnominale")
    public String getEqptozoneurPressionnominale() {
        return PressionsNominalesListe.getValue(PatrimoineDAO.PAT_EQPT_OZONEUR, "eqptozoneur_pressionnominale", eqptozoneurPressionnominale, true);
    }

    /**
     * Sets the value of the eqptozoneurPressionnominale property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressionsNominalesListe }
     *     
     */
    public void setEqptozoneurPressionnominale(String value) {
        this.eqptozoneurPressionnominale = PressionsNominalesListe.fromValue(PatrimoineDAO.PAT_EQPT_OZONEUR, "eqptozoneur_pressionnominale", value);
    }

    /**
     * Gets the value of the eqptozoneurNbtube property.
     * 
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptozoneur_nbtube")
    public int getEqptozoneurNbtube() {
    	if (eqptozoneurNbtube == null) {
    		manageNullException("eqptozoneur_nbtube");
    	}
        return eqptozoneurNbtube;
    }

    /**
     * Sets the value of the eqptozoneurNbtube property.
     * 
     */
    public void setEqptozoneurNbtube(int value) {
        this.eqptozoneurNbtube = value;
    }

    /**
     * Gets the value of the eqptozoneurMateriauconstituant property.
     * 
     * @return
     *     possible object is
     *     {@link MateriauxConstituantsListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptozoneur_materiauconstituant")
    public String getEqptozoneurMateriauconstituant() {
        return MateriauxConstituantsListe.getValue(PatrimoineDAO.PAT_EQPT_OZONEUR, "eqptozoneur_materiauconstituant", eqptozoneurMateriauconstituant, true);
    }

    /**
     * Sets the value of the eqptozoneurMateriauconstituant property.
     * 
     * @param value
     *     allowed object is
     *     {@link MateriauxConstituantsListe }
     *     
     */
    public void setEqptozoneurMateriauconstituant(String value) {
        this.eqptozoneurMateriauconstituant = MateriauxConstituantsListe.fromValue(PatrimoineDAO.PAT_EQPT_OZONEUR, "eqptozoneur_materiauconstituant", value);
    }

    /**
     * Gets the value of the eqptozoneurDimension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptozoneur_dimension")
    public String getEqptozoneurDimension() {
    	if (eqptozoneurDimension == null) {
    		manageNullException("eqptozoneur_dimension");
    	}
        return eqptozoneurDimension;
    }

    /**
     * Sets the value of the eqptozoneurDimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptozoneurDimension(String value) {
        this.eqptozoneurDimension = value;
    }

    /**
     * Gets the value of the eqptozoneurTypediffuseur property.
     * 
     * @return
     *     possible object is
     *     {@link TypesDiffuseursListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptozoneur_typediffuseur")
    public String getEqptozoneurTypediffuseur() {
        return TypesDiffuseursListe.getValue(PatrimoineDAO.PAT_EQPT_OZONEUR, "eqptozoneur_typediffuseur", eqptozoneurTypediffuseur);
    }

    /**
     * Sets the value of the eqptozoneurTypediffuseur property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypesDiffuseursListe }
     *     
     */
    public void setEqptozoneurTypediffuseur(String value) {
        this.eqptozoneurTypediffuseur = TypesDiffuseursListe.fromValue(PatrimoineDAO.PAT_EQPT_OZONEUR, "eqptozoneur_typediffuseur", value);
    }

    /**
     * Gets the value of the eqptozoneurLongueur property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEqptozoneurLongueur() {
        return eqptozoneurLongueur;
    }

    /**
     * Sets the value of the eqptozoneurLongueur property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptozoneurLongueur(BigDecimal value) {
        this.eqptozoneurLongueur = value;
    }

    /**
     * Gets the value of the eqptozoneurCapacite2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptozoneur_capacite2")
    public BigDecimal getEqptozoneurCapacite2() {
    	if (eqptozoneurCapacite2 == null) {
    		manageNullException("eqptozoneur_capacite2");
    	}
        return eqptozoneurCapacite2;
    }

    /**
     * Sets the value of the eqptozoneurCapacite2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptozoneurCapacite2(BigDecimal value) {
        this.eqptozoneurCapacite2 = value;
    }

    /**
     * Gets the value of the eqptozoneurDiametremm property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptozoneur_diametremm")
    public BigDecimal getEqptozoneurDiametremm() {
    	if (eqptozoneurDiametremm == null) {
    		manageNullException("eqptozoneur_diametremm");
    	}
        return eqptozoneurDiametremm;
    }

    /**
     * Sets the value of the eqptozoneurDiametremm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptozoneurDiametremm(BigDecimal value) {
        this.eqptozoneurDiametremm = value;
    }

    /**
     * Gets the value of the eqptozoneurPjmaintenance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptozoneurPjmaintenance() {
        return eqptozoneurPjmaintenance;
    }

    /**
     * Sets the value of the eqptozoneurPjmaintenance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptozoneurPjmaintenance(String value) {
        this.eqptozoneurPjmaintenance = value;
    }

    /**
     * Gets the value of the eqptozoneurPjfichetechnique property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptozoneurPjfichetechnique() {
        return eqptozoneurPjfichetechnique;
    }

    /**
     * Sets the value of the eqptozoneurPjfichetechnique property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptozoneurPjfichetechnique(String value) {
        this.eqptozoneurPjfichetechnique = value;
    }

	public void setIdChg(Integer idChg) {
		this.idChg = idChg;
	}

    private void manageNullException(String champ) {
    	throw new IllegalArgumentException("Table " + PatrimoineDAO.PAT_EQPT_OZONEUR + " - Champs " + champ + " - Valeur 'Null' ou non permise par le XSD.");
	}

}
