//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:47:34 AM CET 
//


package bpm.gateway.core.veolia.patrimoine;

import java.math.BigDecimal;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeEquipementTrappeAcces complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeEquipementTrappeAcces">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eqpttrappeacces_eqptsocle_id" type="{}equipementIDType"/>
 *         &lt;element name="eqpttrappeacces_descriptif" type="{}stringRestricted3000Type"/>
 *         &lt;element name="eqpttrappeacces_materiauconstituant" type="{}materiauxConstituantsListe"/>
 *         &lt;element name="eqpttrappeacces_longueur" type="{}decimalDeuxChiffres" minOccurs="0"/>
 *         &lt;element name="eqpttrappeacces_largeur" type="{}decimalDeuxChiffres" minOccurs="0"/>
 *         &lt;element name="eqpttrappeacces_eqptsecurite" type="{}equipementsSecuriteListe"/>
 *         &lt;element name="eqpttrappeacces_barremateriauconstituant" type="{}materiauxConstituantsListe" minOccurs="0"/>
 *         &lt;element name="eqpttrappeacces_barredimension" type="{}stringRestricted255Type" minOccurs="0"/>
 *         &lt;element name="eqpttrappeacces_gardecorps_id" type="{}equipementIDType" minOccurs="0"/>
 *         &lt;element name="eqpttrappeacces_echelle_id" type="{}equipementIDType" minOccurs="0"/>
 *         &lt;element name="eqpttrappeacces_verouillables" type="{}ouiNonListe"/>
 *         &lt;element name="eqpttrappeacces_type" type="{}TypeBacRetentionListe"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@Access(AccessType.FIELD)
@Table (name = PatrimoineDAO.PAT_EQPT_TRAPPEACCES)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeEquipementTrappeAcces", propOrder = {
    "eqpttrappeaccesEqptsocleId",
    "eqpttrappeaccesDescriptif",
    "eqpttrappeaccesMateriauconstituant",
    "eqpttrappeaccesLongueur",
    "eqpttrappeaccesLargeur",
    "eqpttrappeaccesEqptsecurite",
    "eqpttrappeaccesBarremateriauconstituant",
    "eqpttrappeaccesBarredimension",
    "eqpttrappeaccesGardecorpsId",
    "eqpttrappeaccesEchelleId",
    "eqpttrappeaccesVerouillables",
    "eqpttrappeaccesType"
})
public class TypeEquipementTrappeAcces {

	@Id
	@Column(name = "eqpttrappeacces_id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@XmlTransient
    protected int id;
	@Transient
    @XmlElement(name = "eqpttrappeacces_eqptsocle_id", required = true)
    protected String eqpttrappeaccesEqptsocleId;
	@Transient
    @XmlElement(name = "eqpttrappeacces_descriptif", required = true, defaultValue = "NR")
    protected String eqpttrappeaccesDescriptif;
	@Transient
    @XmlElement(name = "eqpttrappeacces_materiauconstituant", required = true)
    protected MateriauxConstituantsListe eqpttrappeaccesMateriauconstituant;
	@Column(name = "eqpttrappeacces_longueur")
    @XmlElement(name = "eqpttrappeacces_longueur")
    protected BigDecimal eqpttrappeaccesLongueur;
	@Column(name = "eqpttrappeacces_largeur")
    @XmlElement(name = "eqpttrappeacces_largeur")
    protected BigDecimal eqpttrappeaccesLargeur;
	@Transient
    @XmlElement(name = "eqpttrappeacces_eqptsecurite", required = true)
    protected EquipementsSecuriteListe eqpttrappeaccesEqptsecurite;
	@Transient
    @XmlElement(name = "eqpttrappeacces_barremateriauconstituant")
    protected MateriauxConstituantsListe eqpttrappeaccesBarremateriauconstituant;
	@Column(name = "eqpttrappeacces_barredimension")
    @XmlElement(name = "eqpttrappeacces_barredimension")
    protected String eqpttrappeaccesBarredimension;
	@Column(name = "eqpttrappeacces_gardecorps_id")
    @XmlElement(name = "eqpttrappeacces_gardecorps_id")
    protected String eqpttrappeaccesGardecorpsId;
	@Column(name = "eqpttrappeacces_echelle_id")
    @XmlElement(name = "eqpttrappeacces_echelle_id")
    protected String eqpttrappeaccesEchelleId;
	@Transient
    @XmlElement(name = "eqpttrappeacces_verouillables", required = true)
    protected OuiNonListe eqpttrappeaccesVerouillables;
	@Transient
    @XmlElement(name = "eqpttrappeacces_type", required = true)
    protected TypeBacRetentionListe eqpttrappeaccesType;
	@Column(name = "id_chg")
	@XmlTransient
	private Integer idChg;

    /**
     * Gets the value of the eqpttrappeaccesEqptsocleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqpttrappeacces_eqptsocle_id")
    public String getEqpttrappeaccesEqptsocleId() {
    	if (eqpttrappeaccesEqptsocleId == null) {
    		manageNullException("eqpttrappeacces_eqptsocle_id");
    	}
        return eqpttrappeaccesEqptsocleId;
    }

    /**
     * Sets the value of the eqpttrappeaccesEqptsocleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqpttrappeaccesEqptsocleId(String value) {
        this.eqpttrappeaccesEqptsocleId = value;
    }

    /**
     * Gets the value of the eqpttrappeaccesDescriptif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqpttrappeacces_descriptif")
    public String getEqpttrappeaccesDescriptif() {
    	if (eqpttrappeaccesDescriptif == null) {
    		manageNullException("eqpttrappeacces_descriptif");
    	}
        return eqpttrappeaccesDescriptif;
    }

    /**
     * Sets the value of the eqpttrappeaccesDescriptif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqpttrappeaccesDescriptif(String value) {
        this.eqpttrappeaccesDescriptif = value;
    }

    /**
     * Gets the value of the eqpttrappeaccesMateriauconstituant property.
     * 
     * @return
     *     possible object is
     *     {@link MateriauxConstituantsListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqpttrappeacces_materiauconstituant")
    public String getEqpttrappeaccesMateriauconstituant() {
        return MateriauxConstituantsListe.getValue(PatrimoineDAO.PAT_EQPT_TRAPPEACCES, "eqpttrappeacces_materiauconstituant", eqpttrappeaccesMateriauconstituant, true);
    }

    /**
     * Sets the value of the eqpttrappeaccesMateriauconstituant property.
     * 
     * @param value
     *     allowed object is
     *     {@link MateriauxConstituantsListe }
     *     
     */
    public void setEqpttrappeaccesMateriauconstituant(String value) {
        this.eqpttrappeaccesMateriauconstituant = MateriauxConstituantsListe.fromValue(PatrimoineDAO.PAT_EQPT_TRAPPEACCES, "eqpttrappeacces_materiauconstituant", value);
    }

    /**
     * Gets the value of the eqpttrappeaccesLongueur property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEqpttrappeaccesLongueur() {
        return eqpttrappeaccesLongueur;
    }

    /**
     * Sets the value of the eqpttrappeaccesLongueur property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqpttrappeaccesLongueur(BigDecimal value) {
        this.eqpttrappeaccesLongueur = value;
    }

    /**
     * Gets the value of the eqpttrappeaccesLargeur property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEqpttrappeaccesLargeur() {
        return eqpttrappeaccesLargeur;
    }

    /**
     * Sets the value of the eqpttrappeaccesLargeur property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqpttrappeaccesLargeur(BigDecimal value) {
        this.eqpttrappeaccesLargeur = value;
    }

    /**
     * Gets the value of the eqpttrappeaccesEqptsecurite property.
     * 
     * @return
     *     possible object is
     *     {@link EquipementsSecuriteListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqpttrappeacces_eqptsecurite")
    public String getEqpttrappeaccesEqptsecurite() {
        return EquipementsSecuriteListe.getValue(PatrimoineDAO.PAT_EQPT_TRAPPEACCES, "eqpttrappeacces_eqptsecurite", eqpttrappeaccesEqptsecurite);
    }

    /**
     * Sets the value of the eqpttrappeaccesEqptsecurite property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipementsSecuriteListe }
     *     
     */
    public void setEqpttrappeaccesEqptsecurite(String value) {
        this.eqpttrappeaccesEqptsecurite = EquipementsSecuriteListe.fromValue(PatrimoineDAO.PAT_EQPT_TRAPPEACCES, "eqpttrappeacces_eqptsecurite", value);
    }

    /**
     * Gets the value of the eqpttrappeaccesBarremateriauconstituant property.
     * 
     * @return
     *     possible object is
     *     {@link MateriauxConstituantsListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqpttrappeacces_barremateriauconstituant")
    public String getEqpttrappeaccesBarremateriauconstituant() {
        return MateriauxConstituantsListe.getValue(PatrimoineDAO.PAT_EQPT_TRAPPEACCES, "eqpttrappeacces_barremateriauconstituant", eqpttrappeaccesBarremateriauconstituant, false);
    }

    /**
     * Sets the value of the eqpttrappeaccesBarremateriauconstituant property.
     * 
     * @param value
     *     allowed object is
     *     {@link MateriauxConstituantsListe }
     *     
     */
    public void setEqpttrappeaccesBarremateriauconstituant(String value) {
        this.eqpttrappeaccesBarremateriauconstituant = MateriauxConstituantsListe.fromValue(PatrimoineDAO.PAT_EQPT_TRAPPEACCES, "eqpttrappeacces_barremateriauconstituant", value);
    }

    /**
     * Gets the value of the eqpttrappeaccesBarredimension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqpttrappeaccesBarredimension() {
        return eqpttrappeaccesBarredimension;
    }

    /**
     * Sets the value of the eqpttrappeaccesBarredimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqpttrappeaccesBarredimension(String value) {
        this.eqpttrappeaccesBarredimension = value;
    }

    /**
     * Gets the value of the eqpttrappeaccesGardecorpsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqpttrappeaccesGardecorpsId() {
        return eqpttrappeaccesGardecorpsId;
    }

    /**
     * Sets the value of the eqpttrappeaccesGardecorpsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqpttrappeaccesGardecorpsId(String value) {
        this.eqpttrappeaccesGardecorpsId = value;
    }

    /**
     * Gets the value of the eqpttrappeaccesEchelleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqpttrappeaccesEchelleId() {
        return eqpttrappeaccesEchelleId;
    }

    /**
     * Sets the value of the eqpttrappeaccesEchelleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqpttrappeaccesEchelleId(String value) {
        this.eqpttrappeaccesEchelleId = value;
    }

    /**
     * Gets the value of the eqpttrappeaccesVerouillables property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqpttrappeacces_verouillables")
    public String getEqpttrappeaccesVerouillables() {
        return OuiNonListe.getValue(PatrimoineDAO.PAT_EQPT_TRAPPEACCES, "eqpttrappeacces_verouillables", eqpttrappeaccesVerouillables, true);
    }

    /**
     * Sets the value of the eqpttrappeaccesVerouillables property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuiNonListe }
     *     
     */
    public void setEqpttrappeaccesVerouillables(String value) {
        this.eqpttrappeaccesVerouillables = OuiNonListe.fromValue(PatrimoineDAO.PAT_EQPT_TRAPPEACCES, "eqpttrappeacces_verouillables", value);
    }
    
    /**
     * Gets the value of the eqpttrappeaccesVerouillables property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqpttrappeacces_type")
    public String getEqpttrappeaccesType() {
		return TypeBacRetentionListe.getValue(PatrimoineDAO.PAT_EQPT_TRAPPEACCES, "eqpttrappeacces_type", eqpttrappeaccesType, true);
	}
    
    /**
     * Sets the value of the eqpttrappeaccesType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypesBacsRetentionListe }
     *     
     */
    public void setEqpttrappeaccesType(String value) {
		this.eqpttrappeaccesType = TypeBacRetentionListe.fromValue(PatrimoineDAO.PAT_EQPT_TRAPPEACCES, "eqpttrappeacces_type", value);
	}

	public void setIdChg(Integer idChg) {
		this.idChg = idChg;
	}

    private void manageNullException(String champ) {
    	throw new IllegalArgumentException("Table " + PatrimoineDAO.PAT_EQPT_TRAPPEACCES + " - Champs " + champ + " - Valeur 'Null' ou non permise par le XSD.");
	}

}
