//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:47:34 AM CET 
//


package bpm.gateway.core.veolia.patrimoine;

import java.math.BigDecimal;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeEquipementBuselure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeEquipementBuselure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eqptbuselure_eqptsocle_id" type="{}equipementIDType"/>
 *         &lt;element name="eqptbuselure_descriptif" type="{}stringRestricted3000Type"/>
 *         &lt;element name="eqptbuselure_maille" type="{}decimalDeuxChiffres"/>
 *         &lt;element name="eqptbuselure_hauteur" type="{}decimalDeuxChiffres"/>
 *         &lt;element name="eqptbuselure_materiauconstituant" type="{}materiauxConstituantsListe"/>
 *         &lt;element name="eqptbuselure_type" type="{}stringRestricted255Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@Access(AccessType.FIELD)
@Table (name = PatrimoineDAO.PAT_EQPT_BUSELURE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeEquipementBuselure", propOrder = {
    "eqptbuselureEqptsocleId",
    "eqptbuselureDescriptif",
    "eqptbuselureMaille",
    "eqptbuselureHauteur",
    "eqptbuselureMateriauconstituant",
    "eqptbuselureType"
})
public class TypeEquipementBuselure {

	@Id
	@Column(name = "eqptbuselure_id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@XmlTransient
    protected int id;
	@Transient
    @XmlElement(name = "eqptbuselure_eqptsocle_id", required = true)
    protected String eqptbuselureEqptsocleId;
	@Transient
    @XmlElement(name = "eqptbuselure_descriptif", required = true, defaultValue = "NR")
    protected String eqptbuselureDescriptif;
	@Transient
    @XmlElement(name = "eqptbuselure_maille", required = true)
    protected BigDecimal eqptbuselureMaille;
	@Transient
    @XmlElement(name = "eqptbuselure_hauteur", required = true)
    protected BigDecimal eqptbuselureHauteur;
	@Transient
    @XmlElement(name = "eqptbuselure_materiauconstituant", required = true)
    protected MateriauxConstituantsListe eqptbuselureMateriauconstituant;
	@Transient
    @XmlElement(name = "eqptbuselure_type", required = true)
    protected String eqptbuselureType;
	@Column(name = "id_chg")
	@XmlTransient
	private Integer idChg;

    /**
     * Gets the value of the eqptbuselureEqptsocleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptbuselure_eqptsocle_id")
    public String getEqptbuselureEqptsocleId() {
    	if (eqptbuselureEqptsocleId == null) {
    		manageNullException("eqptbuselure_eqptsocle_id");
    	}
        return eqptbuselureEqptsocleId;
    }

    /**
     * Sets the value of the eqptbuselureEqptsocleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptbuselureEqptsocleId(String value) {
        this.eqptbuselureEqptsocleId = value;
    }

    /**
     * Gets the value of the eqptbuselureDescriptif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptbuselure_descriptif")
    public String getEqptbuselureDescriptif() {
    	if (eqptbuselureDescriptif == null) {
    		manageNullException("eqptbuselure_descriptif");
    	}
        return eqptbuselureDescriptif;
    }

    /**
     * Sets the value of the eqptbuselureDescriptif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptbuselureDescriptif(String value) {
        this.eqptbuselureDescriptif = value;
    }

    /**
     * Gets the value of the eqptbuselureMaille property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptbuselure_maille")
    public BigDecimal getEqptbuselureMaille() {
    	if (eqptbuselureMaille == null) {
    		manageNullException("eqptbuselure_maille");
    	}
        return eqptbuselureMaille;
    }

    /**
     * Sets the value of the eqptbuselureMaille property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptbuselureMaille(BigDecimal value) {
        this.eqptbuselureMaille = value;
    }

    /**
     * Gets the value of the eqptbuselureHauteur property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptbuselure_hauteur")
    public BigDecimal getEqptbuselureHauteur() {
    	if (eqptbuselureHauteur == null) {
    		manageNullException("eqptbuselure_hauteur");
    	}
        return eqptbuselureHauteur;
    }

    /**
     * Sets the value of the eqptbuselureHauteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptbuselureHauteur(BigDecimal value) {
        this.eqptbuselureHauteur = value;
    }

    /**
     * Gets the value of the eqptbuselureMateriauconstituant property.
     * 
     * @return
     *     possible object is
     *     {@link MateriauxConstituantsListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptbuselure_materiauconstituant")
    public String getEqptbuselureMateriauconstituant() {
        return MateriauxConstituantsListe.getValue(PatrimoineDAO.PAT_EQPT_BUSELURE, "eqptbuselure_materiauconstituant", eqptbuselureMateriauconstituant, true);
    }

    /**
     * Sets the value of the eqptbuselureMateriauconstituant property.
     * 
     * @param value
     *     allowed object is
     *     {@link MateriauxConstituantsListe }
     *     
     */
    public void setEqptbuselureMateriauconstituant(String value) {
        this.eqptbuselureMateriauconstituant = MateriauxConstituantsListe.fromValue(PatrimoineDAO.PAT_EQPT_BUSELURE, "eqptbuselure_materiauconstituant", value);
    }

    /**
     * Gets the value of the eqptbuselureType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptbuselure_type")
    public String getEqptbuselureType() {
    	if (eqptbuselureType == null) {
    		manageNullException("eqptbuselure_type");
    	}
        return eqptbuselureType;
    }

    /**
     * Sets the value of the eqptbuselureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptbuselureType(String value) {
        this.eqptbuselureType = value;
    }

	public void setIdChg(Integer idChg) {
		this.idChg = idChg;
	}

    private void manageNullException(String champ) {
    	throw new IllegalArgumentException("Table " + PatrimoineDAO.PAT_EQPT_BUSELURE + " - Champs " + champ + " - Valeur 'Null' ou non permise par le XSD.");
	}

}
