//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.14 at 03:43:22 PM CET 
//


package bpm.gateway.core.veolia.patrimoine;

import java.math.BigDecimal;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeEquipementBallon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeEquipementBallon">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eqptballonregul_eqptsocle_id" type="{}equipementIDType"/>
 *         &lt;element name="eqptballonregul_descriptif" type="{}stringRestricted3000Type"/>
 *         &lt;element name="eqptballonregul_type" type="{}typesBallonsRegulationListe"/>
 *         &lt;element name="eqptballonregul_position" type="{}stringRestricted255Type"/>
 *         &lt;element name="eqptballonregul_dimension" type="{}stringRestricted3000Type" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_typevessie" type="{}typesVessiesListe"/>
 *         &lt;element name="eqptballonregul_materiauvessie" type="{}stringRestricted255Type" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_pressionnominale" type="{}pressionsNominalesListe"/>
 *         &lt;element name="eqptballonregul_trouhomme" type="{}ouiNonListe" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_volume" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eqptballonregul_diametrebridesortie" type="{}decimalDeuxChiffres"/>
 *         &lt;element name="eqptballonregul_vannevidange" type="{}stringRestricted3000Type" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_presencecompresseur" type="{}ouiNonListe" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_pressionepreuve" type="{}decimalDeuxChiffres" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_diametre" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_typegarnitureniveau" type="{}typesGarnituresNiveauListe" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_seuilenclenchement" type="{}seuilsEnclenchementListe" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_accespossible" type="{}stringRestricted3000Type" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_clapetperce" type="{}ouiNonListe" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_dispositifcontrole" type="{}stringRestricted3000Type" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_pressionmax" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_pressionmin" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_presencesoupapecharge" type="{}ouiNonListe" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_pjmaintenance" type="{}stringRestricted3000Type" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_pjfichetechnique" type="{}stringRestricted3000Type" minOccurs="0"/>
 *         &lt;element name="eqptballonregul_pjplanfabrication" type="{}stringRestricted3000Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@Access(AccessType.FIELD)
@Table (name = PatrimoineDAO.PAT_EQPT_BALLONREGULATION)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeEquipementBallon", propOrder = {
    "eqptballonregulEqptsocleId",
    "eqptballonregulDescriptif",
    "eqptballonregulType",
    "eqptballonregulPosition",
    "eqptballonregulDimension",
    "eqptballonregulTypevessie",
    "eqptballonregulMateriauvessie",
    "eqptballonregulPressionnominale",
    "eqptballonregulTrouhomme",
    "eqptballonregulVolume",
    "eqptballonregulDiametrebridesortie",
    "eqptballonregulVannevidange",
    "eqptballonregulPresencecompresseur",
    "eqptballonregulPressionepreuve",
    "eqptballonregulDiametre",
    "eqptballonregulTypegarnitureniveau",
    "eqptballonregulSeuilenclenchement",
    "eqptballonregulAccespossible",
    "eqptballonregulClapetperce",
    "eqptballonregulDispositifcontrole",
    "eqptballonregulPressionmax",
    "eqptballonregulPressionmin",
    "eqptballonregulPresencesoupapecharge",
    "eqptballonregulPjmaintenance",
    "eqptballonregulPjfichetechnique",
    "eqptballonregulPjplanfabrication"
})
public class TypeEquipementBallon {

	@Id
	@Column(name = "eqptballonregul_id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@XmlTransient
    protected int id;
	@Transient
    @XmlElement(name = "eqptballonregul_eqptsocle_id", required = true)
    protected String eqptballonregulEqptsocleId;
	@Transient
    @XmlElement(name = "eqptballonregul_descriptif", required = true, defaultValue = "NR")
    protected String eqptballonregulDescriptif;
	@Transient
    @XmlElement(name = "eqptballonregul_type", required = true)
    protected TypesBallonsRegulationListe eqptballonregulType;
	@Transient
    @XmlElement(name = "eqptballonregul_position", required = true)
    protected String eqptballonregulPosition;
	@Column(name = "eqptballonregul_dimension")
    @XmlElement(name = "eqptballonregul_dimension")
    protected String eqptballonregulDimension;
	@Transient
    @XmlElement(name = "eqptballonregul_typevessie", required = true)
    protected TypesVessiesListe eqptballonregulTypevessie;
	@Column(name = "eqptballonregul_materiauvessie")
    @XmlElement(name = "eqptballonregul_materiauvessie")
    protected String eqptballonregulMateriauvessie;
	@Transient
    @XmlElement(name = "eqptballonregul_pressionnominale", required = true)
    protected PressionsNominalesListe eqptballonregulPressionnominale;
	@Transient
    @XmlElement(name = "eqptballonregul_trouhomme")
    protected OuiNonListe eqptballonregulTrouhomme;
	@Transient
    @XmlElement(name = "eqptballonregul_volume", required = true)
    protected BigDecimal eqptballonregulVolume;
	@Transient
    @XmlElement(name = "eqptballonregul_diametrebridesortie", required = true)
    protected BigDecimal eqptballonregulDiametrebridesortie;
	@Column(name = "eqptballonregul_vannevidange")
    @XmlElement(name = "eqptballonregul_vannevidange")
    protected String eqptballonregulVannevidange;
	@Transient
    @XmlElement(name = "eqptballonregul_presencecompresseur")
    protected OuiNonListe eqptballonregulPresencecompresseur;
	@Column(name = "eqptballonregul_pressionepreuve")
    @XmlElement(name = "eqptballonregul_pressionepreuve")
    protected BigDecimal eqptballonregulPressionepreuve;
	@Column(name = "eqptballonregul_diametre")
    @XmlElement(name = "eqptballonregul_diametre")
    protected Integer eqptballonregulDiametre;
	@Transient
    @XmlElement(name = "eqptballonregul_typegarnitureniveau")
    protected TypesGarnituresNiveauListe eqptballonregulTypegarnitureniveau;
	@Transient
    @XmlElement(name = "eqptballonregul_seuilenclenchement")
    protected SeuilsEnclenchementListe eqptballonregulSeuilenclenchement;
	@Column(name = "eqptballonregul_accespossible")
    @XmlElement(name = "eqptballonregul_accespossible")
    protected String eqptballonregulAccespossible;
	@Transient
    @XmlElement(name = "eqptballonregul_clapetperce")
    protected OuiNonListe eqptballonregulClapetperce;
	@Column(name = "eqptballonregul_dispositifcontrole")
    @XmlElement(name = "eqptballonregul_dispositifcontrole")
    protected String eqptballonregulDispositifcontrole;
	@Column(name = "eqptballonregul_pressionmax")
    @XmlElement(name = "eqptballonregul_pressionmax")
    protected Integer eqptballonregulPressionmax;
	@Column(name = "eqptballonregul_pressionmin")
    @XmlElement(name = "eqptballonregul_pressionmin")
    protected Integer eqptballonregulPressionmin;
	@Transient
    @XmlElement(name = "eqptballonregul_presencesoupapecharge")
    protected OuiNonListe eqptballonregulPresencesoupapecharge;
	@Column(name = "eqptballonregul_pjmaintenance")
    @XmlElement(name = "eqptballonregul_pjmaintenance")
    protected String eqptballonregulPjmaintenance;
	@Column(name = "eqptballonregul_pjfichetechnique")
    @XmlElement(name = "eqptballonregul_pjfichetechnique")
    protected String eqptballonregulPjfichetechnique;
	@Column(name = "eqptballonregul_pjplanfabrication")
    @XmlElement(name = "eqptballonregul_pjplanfabrication")
    protected String eqptballonregulPjplanfabrication;
	@Column(name = "id_chg")
	@XmlTransient
	private Integer idChg;

    /**
     * Gets the value of the eqptballonregulEqptsocleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptballonregul_eqptsocle_id")
    public String getEqptballonregulEqptsocleId() {
    	if (eqptballonregulEqptsocleId == null) {
    		manageNullException("eqptballonregul_eqptsocle_id");
    	}
        return eqptballonregulEqptsocleId;
    }

    /**
     * Sets the value of the eqptballonregulEqptsocleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptballonregulEqptsocleId(String value) {
        this.eqptballonregulEqptsocleId = value;
    }

    /**
     * Gets the value of the eqptballonregulDescriptif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptballonregul_descriptif")
    public String getEqptballonregulDescriptif() {
    	if (eqptballonregulDescriptif == null) {
    		manageNullException("eqptballonregul_descriptif");
    	}
        return eqptballonregulDescriptif;
    }

    /**
     * Sets the value of the eqptballonregulDescriptif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptballonregulDescriptif(String value) {
        this.eqptballonregulDescriptif = value;
    }

    /**
     * Gets the value of the eqptballonregulType property.
     * 
     * @return
     *     possible object is
     *     {@link TypesBallonsRegulationListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptballonregul_type")
    public String getEqptballonregulType() {
        return TypesBallonsRegulationListe.getValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_type", eqptballonregulType);
    }

    /**
     * Sets the value of the eqptballonregulType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypesBallonsRegulationListe }
     *     
     */
    public void setEqptballonregulType(String value) {
        this.eqptballonregulType = TypesBallonsRegulationListe.fromValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_type", value);
    }

    /**
     * Gets the value of the eqptballonregulPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptballonregul_position")
    public String getEqptballonregulPosition() {
    	if (eqptballonregulPosition == null) {
    		manageNullException("eqptballonregul_position");
    	}
        return eqptballonregulPosition;
    }

    /**
     * Sets the value of the eqptballonregulPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptballonregulPosition(String value) {
        this.eqptballonregulPosition = value;
    }

    /**
     * Gets the value of the eqptballonregulDimension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptballonregulDimension() {
        return eqptballonregulDimension;
    }

    /**
     * Sets the value of the eqptballonregulDimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptballonregulDimension(String value) {
        this.eqptballonregulDimension = value;
    }

    /**
     * Gets the value of the eqptballonregulTypevessie property.
     * 
     * @return
     *     possible object is
     *     {@link TypesVessiesListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptballonregul_typevessie")
    public String getEqptballonregulTypevessie() {
        return TypesVessiesListe.getValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_typevessie", eqptballonregulTypevessie);
    }

    /**
     * Sets the value of the eqptballonregulTypevessie property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypesVessiesListe }
     *     
     */
    public void setEqptballonregulTypevessie(String value) {
        this.eqptballonregulTypevessie = TypesVessiesListe.fromValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_typevessie", value);
    }

    /**
     * Gets the value of the eqptballonregulMateriauvessie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptballonregulMateriauvessie() {
        return eqptballonregulMateriauvessie;
    }

    /**
     * Sets the value of the eqptballonregulMateriauvessie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptballonregulMateriauvessie(String value) {
        this.eqptballonregulMateriauvessie = value;
    }

    /**
     * Gets the value of the eqptballonregulPressionnominale property.
     * 
     * @return
     *     possible object is
     *     {@link PressionsNominalesListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptballonregul_pressionnominale")
    public String getEqptballonregulPressionnominale() {
        return PressionsNominalesListe.getValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_pressionnominale", eqptballonregulPressionnominale, true);
    }

    /**
     * Sets the value of the eqptballonregulPressionnominale property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressionsNominalesListe }
     *     
     */
    public void setEqptballonregulPressionnominale(String value) {
        this.eqptballonregulPressionnominale = PressionsNominalesListe.fromValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_pressionnominale", value);
    }

    /**
     * Gets the value of the eqptballonregulTrouhomme property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptballonregul_trouhomme")
    public String getEqptballonregulTrouhomme() {
        return OuiNonListe.getValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_trouhomme", eqptballonregulTrouhomme, false);
    }

    /**
     * Sets the value of the eqptballonregulTrouhomme property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuiNonListe }
     *     
     */
    public void setEqptballonregulTrouhomme(String value) {
        this.eqptballonregulTrouhomme = OuiNonListe.fromValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_trouhomme", value);
    }

    /**
     * Gets the value of the eqptballonregulVolume property.
     * 
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptballonregul_volume")
    public BigDecimal getEqptballonregulVolume() {
    	if (eqptballonregulVolume == null) {
    		manageNullException("eqptballonregul_volume");
    	}
        return eqptballonregulVolume;
    }

    /**
     * Sets the value of the eqptballonregulVolume property.
     * 
     */
    public void setEqptballonregulVolume(BigDecimal value) {
        this.eqptballonregulVolume = value;
    }

    /**
     * Gets the value of the eqptballonregulDiametrebridesortie property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptballonregul_diametrebridesortie")
    public BigDecimal getEqptballonregulDiametrebridesortie() {
    	if (eqptballonregulDiametrebridesortie == null) {
    		manageNullException("eqptballonregul_diametrebridesortie");
    	}
        return eqptballonregulDiametrebridesortie;
    }

    /**
     * Sets the value of the eqptballonregulDiametrebridesortie property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptballonregulDiametrebridesortie(BigDecimal value) {
        this.eqptballonregulDiametrebridesortie = value;
    }

    /**
     * Gets the value of the eqptballonregulVannevidange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptballonregulVannevidange() {
        return eqptballonregulVannevidange;
    }

    /**
     * Sets the value of the eqptballonregulVannevidange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptballonregulVannevidange(String value) {
        this.eqptballonregulVannevidange = value;
    }

    /**
     * Gets the value of the eqptballonregulPresencecompresseur property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptballonregul_presencecompresseur")
    public String getEqptballonregulPresencecompresseur() {
        return OuiNonListe.getValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_presencecompresseur", eqptballonregulPresencecompresseur, false);
    }

    /**
     * Sets the value of the eqptballonregulPresencecompresseur property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuiNonListe }
     *     
     */
    public void setEqptballonregulPresencecompresseur(String value) {
        this.eqptballonregulPresencecompresseur = OuiNonListe.fromValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_presencecompresseur", value);
    }

    /**
     * Gets the value of the eqptballonregulPressionepreuve property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEqptballonregulPressionepreuve() {
        return eqptballonregulPressionepreuve;
    }

    /**
     * Sets the value of the eqptballonregulPressionepreuve property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptballonregulPressionepreuve(BigDecimal value) {
        this.eqptballonregulPressionepreuve = value;
    }

    /**
     * Gets the value of the eqptballonregulDiametre property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEqptballonregulDiametre() {
        return eqptballonregulDiametre;
    }

    /**
     * Sets the value of the eqptballonregulDiametre property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEqptballonregulDiametre(Integer value) {
        this.eqptballonregulDiametre = value;
    }

    /**
     * Gets the value of the eqptballonregulTypegarnitureniveau property.
     * 
     * @return
     *     possible object is
     *     {@link TypesGarnituresNiveauListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptballonregul_typegarnitureniveau")
    public String getEqptballonregulTypegarnitureniveau() {
        return TypesGarnituresNiveauListe.getValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_typegarnitureniveau", eqptballonregulTypegarnitureniveau, false);
    }

    /**
     * Sets the value of the eqptballonregulTypegarnitureniveau property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypesGarnituresNiveauListe }
     *     
     */
    public void setEqptballonregulTypegarnitureniveau(String value) {
        this.eqptballonregulTypegarnitureniveau = TypesGarnituresNiveauListe.fromValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_typegarnitureniveau", value);
    }

    /**
     * Gets the value of the eqptballonregulSeuilenclenchement property.
     * 
     * @return
     *     possible object is
     *     {@link SeuilsEnclenchementListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptballonregul_seuilenclenchement")
    public String getEqptballonregulSeuilenclenchement() {
        return SeuilsEnclenchementListe.getValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_seuilenclenchement", eqptballonregulSeuilenclenchement, false);
    }

    /**
     * Sets the value of the eqptballonregulSeuilenclenchement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeuilsEnclenchementListe }
     *     
     */
    public void setEqptballonregulSeuilenclenchement(String value) {
        this.eqptballonregulSeuilenclenchement = SeuilsEnclenchementListe.fromValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_seuilenclenchement", value);
    }

    /**
     * Gets the value of the eqptballonregulAccespossible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptballonregulAccespossible() {
        return eqptballonregulAccespossible;
    }

    /**
     * Sets the value of the eqptballonregulAccespossible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptballonregulAccespossible(String value) {
        this.eqptballonregulAccespossible = value;
    }

    /**
     * Gets the value of the eqptballonregulClapetperce property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptballonregul_clapetperce")
    public String getEqptballonregulClapetperce() {
        return OuiNonListe.getValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_clapetperce", eqptballonregulClapetperce, false);
    }

    /**
     * Sets the value of the eqptballonregulClapetperce property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuiNonListe }
     *     
     */
    public void setEqptballonregulClapetperce(String value) {
        this.eqptballonregulClapetperce = OuiNonListe.fromValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_clapetperce", value);
    }

    /**
     * Gets the value of the eqptballonregulDispositifcontrole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptballonregulDispositifcontrole() {
        return eqptballonregulDispositifcontrole;
    }

    /**
     * Sets the value of the eqptballonregulDispositifcontrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptballonregulDispositifcontrole(String value) {
        this.eqptballonregulDispositifcontrole = value;
    }

    /**
     * Gets the value of the eqptballonregulPressionmax property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEqptballonregulPressionmax() {
        return eqptballonregulPressionmax;
    }

    /**
     * Sets the value of the eqptballonregulPressionmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEqptballonregulPressionmax(Integer value) {
        this.eqptballonregulPressionmax = value;
    }

    /**
     * Gets the value of the eqptballonregulPressionmin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEqptballonregulPressionmin() {
        return eqptballonregulPressionmin;
    }

    /**
     * Sets the value of the eqptballonregulPressionmin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEqptballonregulPressionmin(Integer value) {
        this.eqptballonregulPressionmin = value;
    }

    /**
     * Gets the value of the eqptballonregulPresencesoupapecharge property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptballonregul_presencesoupapecharge")
    public String getEqptballonregulPresencesoupapecharge() {
        return OuiNonListe.getValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_presencesoupapecharge", eqptballonregulPresencesoupapecharge, false);
    }

    /**
     * Sets the value of the eqptballonregulPresencesoupapecharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuiNonListe }
     *     
     */
    public void setEqptballonregulPresencesoupapecharge(String value) {
        this.eqptballonregulPresencesoupapecharge = OuiNonListe.fromValue(PatrimoineDAO.PAT_EQPT_BALLONREGULATION, "eqptballonregul_presencesoupapecharge", value);
    }

    /**
     * Gets the value of the eqptballonregulPjmaintenance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptballonregulPjmaintenance() {
        return eqptballonregulPjmaintenance;
    }

    /**
     * Sets the value of the eqptballonregulPjmaintenance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptballonregulPjmaintenance(String value) {
        this.eqptballonregulPjmaintenance = value;
    }

    /**
     * Gets the value of the eqptballonregulPjfichetechnique property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptballonregulPjfichetechnique() {
        return eqptballonregulPjfichetechnique;
    }

    /**
     * Sets the value of the eqptballonregulPjfichetechnique property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptballonregulPjfichetechnique(String value) {
        this.eqptballonregulPjfichetechnique = value;
    }

    /**
     * Gets the value of the eqptballonregulPjplanfabrication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptballonregulPjplanfabrication() {
        return eqptballonregulPjplanfabrication;
    }

    /**
     * Sets the value of the eqptballonregulPjplanfabrication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptballonregulPjplanfabrication(String value) {
        this.eqptballonregulPjplanfabrication = value;
    }

	public void setIdChg(Integer idChg) {
		this.idChg = idChg;
	}

    private void manageNullException(String champ) {
    	throw new IllegalArgumentException("Table " + PatrimoineDAO.PAT_EQPT_BALLONREGULATION + " - Champs " + champ + " - Valeur 'Null' ou non permise par le XSD.");
	}

}
