//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:47:34 AM CET 
//


package bpm.gateway.core.veolia.patrimoine;

import java.math.BigDecimal;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeEquipementComptage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeEquipementComptage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eqptcomptage_eqptsocle_id" type="{}equipementIDType"/>
 *         &lt;element name="eqptcomptage_descriptif" type="{}stringRestricted3000Type"/>
 *         &lt;element name="eqptcomptage_type" type="{}typesCompteursListe"/>
 *         &lt;element name="eqptcomptage_debitnominal" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eqptcomptage_diametrenominal" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eqptcomptage_pressionnominale" type="{}pressionsNominalesListe"/>
 *         &lt;element name="eqptcomptage_typecomptage" type="{}typesComptagesListe" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_coefetalonnage" type="{}decimalDeuxChiffres" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_indexpose" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_indexmax" type="{}indexMaximumListe" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_agenceeau" type="{}ouiNonListe" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_referenceagenceeau" type="{}stringRestricted255Type" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_comptagestrategique" type="{}ouiNonListe"/>
 *         &lt;element name="eqptcomptage_typecomptagestrategique" type="{}typesComptagesStrategiquesliste" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_presencecapteur" type="{}ouiNonListe" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_longueurentrebride" type="{}decimalDeuxChiffres" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_teteemettrice" type="{}tetesEmettricesListe" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_typeteteemettrice" type="{}typetetesEmettricesListe" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_passagereduit" type="{}stringRestricted255Type" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_exigencelongueurdroite" type="{}stringRestricted255Type" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_typesignal" type="{}typesSignauxListe" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_afficheurtransmetteur" type="{}afficheursTransmetteursListe" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_position" type="{}positionsComptagesListe" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_presencebatterie" type="{}ouiNonListe" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_typebatterie" type="{}stringRestricted255Type" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_precision" type="{}stringRestricted255Type" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_capteurintegre" type="{}ouiNonListe" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_pjmaintenance" type="{}stringRestricted3000Type" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_pjetalonnage" type="{}stringRestricted3000Type" minOccurs="0"/>
 *         &lt;element name="eqptcomptage_pjfichetechnique" type="{}stringRestricted3000Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@Access(AccessType.FIELD)
@Table (name = PatrimoineDAO.PAT_EQPT_COMPTAGE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeEquipementComptage", propOrder = {
    "eqptcomptageEqptsocleId",
    "eqptcomptageDescriptif",
    "eqptcomptageType",
    "eqptcomptageDebitnominal",
    "eqptcomptageDiametrenominal",
    "eqptcomptagePressionnominale",
    "eqptcomptageTypecomptage",
    "eqptcomptageCoefetalonnage",
    "eqptcomptageIndexpose",
    "eqptcomptageIndexmax",
    "eqptcomptageAgenceeau",
    "eqptcomptageReferenceagenceeau",
    "eqptcomptageComptagestrategique",
    "eqptcomptageTypecomptagestrategique",
    "eqptcomptagePresencecapteur",
    "eqptcomptageLongueurentrebride",
    "eqptcomptageTeteemettrice",
    "eqptcomptageTypeteteemettrice",
    "eqptcomptagePassagereduit",
    "eqptcomptageExigencelongueurdroite",
    "eqptcomptageTypesignal",
    "eqptcomptageAfficheurtransmetteur",
    "eqptcomptagePosition",
    "eqptcomptagePresencebatterie",
    "eqptcomptageTypebatterie",
    "eqptcomptagePrecision",
    "eqptcomptageCapteurintegre",
    "eqptcomptagePjmaintenance",
    "eqptcomptagePjetalonnage",
    "eqptcomptagePjfichetechnique"
})
public class TypeEquipementComptage {

	@Id
	@Column(name = "eqptcomptage_id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@XmlTransient
    protected int id;
	@Transient
    @XmlElement(name = "eqptcomptage_eqptsocle_id", required = true)
    protected String eqptcomptageEqptsocleId;
	@Transient
    @XmlElement(name = "eqptcomptage_descriptif", required = true)
    protected String eqptcomptageDescriptif;
	@Transient
    @XmlElement(name = "eqptcomptage_type", required = true)
    protected TypesCompteursListe eqptcomptageType;
	@Transient
    @XmlElement(name = "eqptcomptage_debitnominal")
    protected BigDecimal eqptcomptageDebitnominal;
	@Transient
    @XmlElement(name = "eqptcomptage_diametrenominal")
    protected Integer eqptcomptageDiametrenominal;
	@Transient
    @XmlElement(name = "eqptcomptage_pressionnominale", required = true)
    protected PressionsNominalesListe eqptcomptagePressionnominale;
	@Transient
    @XmlElement(name = "eqptcomptage_typecomptage")
    protected TypesComptagesListe eqptcomptageTypecomptage;
	@Column(name = "eqptcomptage_coefetalonnage")
    @XmlElement(name = "eqptcomptage_coefetalonnage")
    protected BigDecimal eqptcomptageCoefetalonnage;
	@Column(name = "eqptcomptage_indexpose")
    @XmlElement(name = "eqptcomptage_indexpose")
    protected Integer eqptcomptageIndexpose;
	@Transient
    @XmlElement(name = "eqptcomptage_indexmax")
    protected IndexMaximumListe eqptcomptageIndexmax;
	@Transient
    @XmlElement(name = "eqptcomptage_agenceeau")
    protected OuiNonListe eqptcomptageAgenceeau;
	@Column(name = "eqptcomptage_referenceagenceeau")
    @XmlElement(name = "eqptcomptage_referenceagenceeau")
    protected String eqptcomptageReferenceagenceeau;
	@Transient
    @XmlElement(name = "eqptcomptage_comptagestrategique", required = true)
    protected OuiNonListe eqptcomptageComptagestrategique;
	@Transient
    @XmlElement(name = "eqptcomptage_typecomptagestrategique")
    protected TypesComptagesStrategiquesliste eqptcomptageTypecomptagestrategique;
	@Transient
    @XmlElement(name = "eqptcomptage_presencecapteur")
    protected OuiNonListe eqptcomptagePresencecapteur;
	@Column(name = "eqptcomptage_longueurentrebride")
    @XmlElement(name = "eqptcomptage_longueurentrebride")
    protected BigDecimal eqptcomptageLongueurentrebride;
	@Column(name = "eqptcomptage_teteemettrice")
    @XmlElement(name = "eqptcomptage_teteemettrice")
    protected String eqptcomptageTeteemettrice;
	@Transient
    @XmlElement(name = "eqptcomptage_typeteteemettrice")
    protected TypetetesEmettricesListe eqptcomptageTypeteteemettrice;
	@Column(name = "eqptcomptage_passagereduit")
    @XmlElement(name = "eqptcomptage_passagereduit")
    protected String eqptcomptagePassagereduit;
	@Column(name = "eqptcomptage_exigencelongueurdroite")
    @XmlElement(name = "eqptcomptage_exigencelongueurdroite")
    protected String eqptcomptageExigencelongueurdroite;
	@Column(name = "eqptcomptage_typesignal")
    @XmlElement(name = "eqptcomptage_typesignal")
    protected String eqptcomptageTypesignal;
	@Transient
    @XmlElement(name = "eqptcomptage_afficheurtransmetteur")
    protected AfficheursTransmetteursListe eqptcomptageAfficheurtransmetteur;
	@Transient
    @XmlElement(name = "eqptcomptage_position")
    protected PositionsComptagesListe eqptcomptagePosition;
	@Transient
    @XmlElement(name = "eqptcomptage_presencebatterie")
    protected OuiNonListe eqptcomptagePresencebatterie;
	@Column(name = "eqptcomptage_typebatterie")
    @XmlElement(name = "eqptcomptage_typebatterie")
    protected String eqptcomptageTypebatterie;
	@Column(name = "eqptcomptage_precision")
    @XmlElement(name = "eqptcomptage_precision")
    protected String eqptcomptagePrecision;
	@Transient
    @XmlElement(name = "eqptcomptage_capteurintegre")
    protected OuiNonListe eqptcomptageCapteurintegre;
	@Column(name = "eqptcomptage_pjmaintenance")
    @XmlElement(name = "eqptcomptage_pjmaintenance")
    protected String eqptcomptagePjmaintenance;
	@Column(name = "eqptcomptage_pjetalonnage")
    @XmlElement(name = "eqptcomptage_pjetalonnage")
    protected String eqptcomptagePjetalonnage;
	@Column(name = "eqptcomptage_pjfichetechnique")
    @XmlElement(name = "eqptcomptage_pjfichetechnique")
    protected String eqptcomptagePjfichetechnique;
	@Column(name = "id_chg")
	@XmlTransient
	private Integer idChg;

    /**
     * Gets the value of the eqptcomptageEqptsocleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_eqptsocle_id")
    public String getEqptcomptageEqptsocleId() {
    	if (eqptcomptageEqptsocleId == null) {
    		manageNullException("eqptcomptage_eqptsocle_id");
    	}
        return eqptcomptageEqptsocleId;
    }

    /**
     * Sets the value of the eqptcomptageEqptsocleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptcomptageEqptsocleId(String value) {
        this.eqptcomptageEqptsocleId = value != null ? value : "";
    }

    /**
     * Gets the value of the eqptcomptageDescriptif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_descriptif")
    public String getEqptcomptageDescriptif() {
    	if (eqptcomptageDescriptif == null) {
    		manageNullException("eqptcomptage_descriptif");
    	}
        return eqptcomptageDescriptif;
    }

    /**
     * Sets the value of the eqptcomptageDescriptif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptcomptageDescriptif(String value) {
        this.eqptcomptageDescriptif = value != null ? value : "";
    }

    /**
     * Gets the value of the eqptcomptageType property.
     * 
     * @return
     *     possible object is
     *     {@link TypesCompteursListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_type")
    public String getEqptcomptageType() {
        return TypesCompteursListe.getValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_type", eqptcomptageType);
    }

    /**
     * Sets the value of the eqptcomptageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypesCompteursListe }
     *     
     */
    public void setEqptcomptageType(String value) {
        this.eqptcomptageType = TypesCompteursListe.fromValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_type", value);
    }

    /**
     * Gets the value of the eqptcomptageDebitnominal property.
     * 
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_debitnominal")
    public BigDecimal getEqptcomptageDebitnominal() {
    	if (eqptcomptageDebitnominal == null) {
    		manageNullException("eqptcomptage_debitnominal");
    	}
        return eqptcomptageDebitnominal;
    }

    /**
     * Sets the value of the eqptcomptageDebitnominal property.
     * 
     */
    public void setEqptcomptageDebitnominal(BigDecimal value) {
        this.eqptcomptageDebitnominal = value;
    }

    /**
     * Gets the value of the eqptcomptageDiametrenominal property.
     * 
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_diametrenominal")
    public int getEqptcomptageDiametrenominal() {
    	if (eqptcomptageDiametrenominal == null) {
    		manageNullException("eqptcomptage_diametrenominal");
    	}
        return eqptcomptageDiametrenominal;
    }

    /**
     * Sets the value of the eqptcomptageDiametrenominal property.
     * 
     */
    public void setEqptcomptageDiametrenominal(int value) {
        this.eqptcomptageDiametrenominal = value;
    }

    /**
     * Gets the value of the eqptcomptagePressionnominale property.
     * 
     * @return
     *     possible object is
     *     {@link PressionsNominalesListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_pressionnominale")
    public String getEqptcomptagePressionnominale() {
        return PressionsNominalesListe.getValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_pressionnominale", eqptcomptagePressionnominale, true);
    }

    /**
     * Sets the value of the eqptcomptagePressionnominale property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressionsNominalesListe }
     *     
     */
    public void setEqptcomptagePressionnominale(String value) {
        this.eqptcomptagePressionnominale = PressionsNominalesListe.fromValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_pressionnominale", value);
    }

    /**
     * Gets the value of the eqptcomptageTypecomptage property.
     * 
     * @return
     *     possible object is
     *     {@link TypesComptagesListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_typecomptage")
    public String getEqptcomptageTypecomptage() {
        return TypesComptagesListe.getValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_typecomptage", eqptcomptageTypecomptage, false);
    }

    /**
     * Sets the value of the eqptcomptageTypecomptage property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypesComptagesListe }
     *     
     */
    public void setEqptcomptageTypecomptage(String value) {
        this.eqptcomptageTypecomptage = TypesComptagesListe.fromValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_typecomptage", value);
    }

    /**
     * Gets the value of the eqptcomptageCoefetalonnage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEqptcomptageCoefetalonnage() {
        return eqptcomptageCoefetalonnage;
    }

    /**
     * Sets the value of the eqptcomptageCoefetalonnage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptcomptageCoefetalonnage(BigDecimal value) {
        this.eqptcomptageCoefetalonnage = value;
    }

    /**
     * Gets the value of the eqptcomptageIndexpose property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEqptcomptageIndexpose() {
        return eqptcomptageIndexpose;
    }

    /**
     * Sets the value of the eqptcomptageIndexpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEqptcomptageIndexpose(Integer value) {
        this.eqptcomptageIndexpose = value;
    }

    /**
     * Gets the value of the eqptcomptageIndexmax property.
     * 
     * @return
     *     possible object is
     *     {@link IndexMaximumListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_indexmax")
    public Long getEqptcomptageIndexmax() {
        return IndexMaximumListe.getValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_indexmax", eqptcomptageIndexmax, false);
    }

    /**
     * Sets the value of the eqptcomptageIndexmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexMaximumListe }
     *     
     */
    public void setEqptcomptageIndexmax(Long value) {
        this.eqptcomptageIndexmax = IndexMaximumListe.fromValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_indexmax", value);
    }

    /**
     * Gets the value of the eqptcomptageAgenceeau property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_agenceeau")
    public String getEqptcomptageAgenceeau() {
        return OuiNonListe.getValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_agenceeau", eqptcomptageAgenceeau, false);
    }

    /**
     * Sets the value of the eqptcomptageAgenceeau property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuiNonListe }
     *     
     */
    public void setEqptcomptageAgenceeau(String value) {
        this.eqptcomptageAgenceeau = OuiNonListe.fromValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_agenceeau", value);
    }

    /**
     * Gets the value of the eqptcomptageReferenceagenceeau property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptcomptageReferenceagenceeau() {
        return eqptcomptageReferenceagenceeau;
    }

    /**
     * Sets the value of the eqptcomptageReferenceagenceeau property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptcomptageReferenceagenceeau(String value) {
        this.eqptcomptageReferenceagenceeau = value;
    }

    /**
     * Gets the value of the eqptcomptageComptagestrategique property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_comptagestrategique")
    public String getEqptcomptageComptagestrategique() {
        return OuiNonListe.getValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_comptagestrategique", eqptcomptageComptagestrategique, true);
    }

    /**
     * Sets the value of the eqptcomptageComptagestrategique property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuiNonListe }
     *     
     */
    public void setEqptcomptageComptagestrategique(String value) {
        this.eqptcomptageComptagestrategique = OuiNonListe.fromValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_comptagestrategique", value);
    }

    /**
     * Gets the value of the eqptcomptageTypecomptagestrategique property.
     * 
     * @return
     *     possible object is
     *     {@link TypesComptagesStrategiquesliste }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_typecomptagestrategique")
    public String getEqptcomptageTypecomptagestrategique() {
        return TypesComptagesStrategiquesliste.getValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_typecomptagestrategique", eqptcomptageTypecomptagestrategique, false);
    }

    /**
     * Sets the value of the eqptcomptageTypecomptagestrategique property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypesComptagesStrategiquesliste }
     *     
     */
    public void setEqptcomptageTypecomptagestrategique(String value) {
        this.eqptcomptageTypecomptagestrategique = TypesComptagesStrategiquesliste.fromValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_typecomptagestrategique", value);
    }

    /**
     * Gets the value of the eqptcomptagePresencecapteur property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_presencecapteur")
    public String getEqptcomptagePresencecapteur() {
        return OuiNonListe.getValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_presencecapteur", eqptcomptagePresencecapteur, false);
    }

    /**
     * Sets the value of the eqptcomptagePresencecapteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuiNonListe }
     *     
     */
    public void setEqptcomptagePresencecapteur(String value) {
        this.eqptcomptagePresencecapteur = OuiNonListe.fromValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_presencecapteur", value);
    }

    /**
     * Gets the value of the eqptcomptageLongueurentrebride property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEqptcomptageLongueurentrebride() {
        return eqptcomptageLongueurentrebride;
    }

    /**
     * Sets the value of the eqptcomptageLongueurentrebride property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptcomptageLongueurentrebride(BigDecimal value) {
        this.eqptcomptageLongueurentrebride = value;
    }

    /**
     * Gets the value of the eqptcomptageTeteemettrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptcomptageTeteemettrice() {
        return eqptcomptageTeteemettrice;
    }

    /**
     * Sets the value of the eqptcomptageTeteemettrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptcomptageTeteemettrice(String value) {
        this.eqptcomptageTeteemettrice = value;
    }

    /**
     * Gets the value of the eqptcomptageTypeteteemettrice property.
     * 
     * @return
     *     possible object is
     *     {@link TypetetesEmettricesListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_typeteteemettrice")
    public String getEqptcomptageTypeteteemettrice() {
        return TypetetesEmettricesListe.getValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_typeteteemettrice", eqptcomptageTypeteteemettrice, false);
    }

    /**
     * Sets the value of the eqptcomptageTypeteteemettrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypetetesEmettricesListe }
     *     
     */
    public void setEqptcomptageTypeteteemettrice(String value) {
        this.eqptcomptageTypeteteemettrice = TypetetesEmettricesListe.fromValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_typeteteemettrice", value);
    }

    /**
     * Gets the value of the eqptcomptagePassagereduit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptcomptagePassagereduit() {
        return eqptcomptagePassagereduit;
    }

    /**
     * Sets the value of the eqptcomptagePassagereduit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptcomptagePassagereduit(String value) {
        this.eqptcomptagePassagereduit = value;
    }

    /**
     * Gets the value of the eqptcomptageExigencelongueurdroite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptcomptageExigencelongueurdroite() {
        return eqptcomptageExigencelongueurdroite;
    }

    /**
     * Sets the value of the eqptcomptageExigencelongueurdroite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptcomptageExigencelongueurdroite(String value) {
        this.eqptcomptageExigencelongueurdroite = value;
    }

    /**
     * Gets the value of the eqptcomptageTypesignal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptcomptageTypesignal() {
        return eqptcomptageTypesignal;
    }

    /**
     * Sets the value of the eqptcomptageTypesignal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptcomptageTypesignal(String value) {
        this.eqptcomptageTypesignal = value;
    }

    /**
     * Gets the value of the eqptcomptageAfficheurtransmetteur property.
     * 
     * @return
     *     possible object is
     *     {@link AfficheursTransmetteursListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_afficheurtransmetteur")
    public String getEqptcomptageAfficheurtransmetteur() {
        return AfficheursTransmetteursListe.getValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_afficheurtransmetteur", eqptcomptageAfficheurtransmetteur, false);
    }

    /**
     * Sets the value of the eqptcomptageAfficheurtransmetteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link AfficheursTransmetteursListe }
     *     
     */
    public void setEqptcomptageAfficheurtransmetteur(String value) {
        this.eqptcomptageAfficheurtransmetteur = AfficheursTransmetteursListe.fromValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_afficheurtransmetteur", value);
    }

    /**
     * Gets the value of the eqptcomptagePosition property.
     * 
     * @return
     *     possible object is
     *     {@link PositionsListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_position")
    public String getEqptcomptagePosition() {
        return PositionsComptagesListe.getValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_position", eqptcomptagePosition, false);
    }

    /**
     * Sets the value of the eqptcomptagePosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionsListe }
     *     
     */
    public void setEqptcomptagePosition(String value) {
        this.eqptcomptagePosition = PositionsComptagesListe.fromValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_position", value);
    }

    /**
     * Gets the value of the eqptcomptagePresencebatterie property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_presencebatterie")
    public String getEqptcomptagePresencebatterie() {
        return OuiNonListe.getValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_presencebatterie", eqptcomptagePresencebatterie, false);
    }

    /**
     * Sets the value of the eqptcomptagePresencebatterie property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuiNonListe }
     *     
     */
    public void setEqptcomptagePresencebatterie(String value) {
        this.eqptcomptagePresencebatterie = OuiNonListe.fromValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_presencebatterie", value);
    }

    /**
     * Gets the value of the eqptcomptageTypebatterie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptcomptageTypebatterie() {
        return eqptcomptageTypebatterie;
    }

    /**
     * Sets the value of the eqptcomptageTypebatterie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptcomptageTypebatterie(String value) {
        this.eqptcomptageTypebatterie = value;
    }

    /**
     * Gets the value of the eqptcomptagePrecision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptcomptagePrecision() {
        return eqptcomptagePrecision;
    }

    /**
     * Sets the value of the eqptcomptagePrecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptcomptagePrecision(String value) {
        this.eqptcomptagePrecision = value;
    }

    /**
     * Gets the value of the eqptcomptageCapteurintegre property.
     * 
     * @return
     *     possible object is
     *     {@link OuiNonListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcomptage_capteurintegre")
    public String getEqptcomptageCapteurintegre() {
        return OuiNonListe.getValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_capteurintegre", eqptcomptageCapteurintegre, false);
    }

    /**
     * Sets the value of the eqptcomptageCapteurintegre property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuiNonListe }
     *     
     */
    public void setEqptcomptageCapteurintegre(String value) {
        this.eqptcomptageCapteurintegre = OuiNonListe.fromValue(PatrimoineDAO.PAT_EQPT_COMPTAGE, "eqptcomptage_capteurintegre", value);
    }

    /**
     * Gets the value of the eqptcomptagePjmaintenance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptcomptagePjmaintenance() {
        return eqptcomptagePjmaintenance;
    }

    /**
     * Sets the value of the eqptcomptagePjmaintenance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptcomptagePjmaintenance(String value) {
        this.eqptcomptagePjmaintenance = value;
    }

    /**
     * Gets the value of the eqptcomptagePjetalonnage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptcomptagePjetalonnage() {
        return eqptcomptagePjetalonnage;
    }

    /**
     * Sets the value of the eqptcomptagePjetalonnage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptcomptagePjetalonnage(String value) {
        this.eqptcomptagePjetalonnage = value;
    }

    /**
     * Gets the value of the eqptcomptagePjfichetechnique property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqptcomptagePjfichetechnique() {
        return eqptcomptagePjfichetechnique;
    }

    /**
     * Sets the value of the eqptcomptagePjfichetechnique property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptcomptagePjfichetechnique(String value) {
        this.eqptcomptagePjfichetechnique = value;
    }

	public void setIdChg(Integer idChg) {
		this.idChg = idChg;
	}

    private void manageNullException(String champ) {
    	throw new IllegalArgumentException("Table " + PatrimoineDAO.PAT_EQPT_COMPTAGE + " - Champs " + champ + " - Valeur 'Null' ou non permise par le XSD.");
	}

}
