//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:47:34 AM CET 
//


package bpm.gateway.core.veolia.patrimoine;

import java.math.BigDecimal;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeEquipementCanalComptage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeEquipementCanalComptage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eqptcanalcomptage_eqptsocle_id" type="{}equipementIDType"/>
 *         &lt;element name="eqptcanalcomptage_descriptif" type="{}stringRestricted3000Type"/>
 *         &lt;element name="eqptcanalcomptage_debitnominal" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eqptcanalcomptage_hauteur" type="{}decimalDeuxChiffres"/>
 *         &lt;element name="eqptcanalcomptage_largeur" type="{}decimalDeuxChiffres"/>
 *         &lt;element name="eqptcanalcomptage_longueur" type="{}decimalDeuxChiffres"/>
 *         &lt;element name="eqptcanalcomptage_typecanal" type="{}typesCanauxListe"/>
 *         &lt;element name="eqptcanalcomptage_mesure" type="{}equipementIDType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@Access(AccessType.FIELD)
@Table (name = PatrimoineDAO.PAT_EQPT_CANALCOMPTAGE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeEquipementCanalComptage", propOrder = {
    "eqptcanalcomptageEqptsocleId",
    "eqptcanalcomptageDescriptif",
    "eqptcanalcomptageDebitnominal",
    "eqptcanalcomptageHauteur",
    "eqptcanalcomptageLargeur",
    "eqptcanalcomptageLongueur",
    "eqptcanalcomptageTypecanal",
    "eqptcanalcomptageMesure"
})
public class TypeEquipementCanalComptage {

	@Id
	@Column(name = "eqptcanalcomptage_id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@XmlTransient
    protected int id;
	@Transient
    @XmlElement(name = "eqptcanalcomptage_eqptsocle_id", required = true)
    protected String eqptcanalcomptageEqptsocleId;
	@Transient
    @XmlElement(name = "eqptcanalcomptage_descriptif", required = true, defaultValue = "NR")
    protected String eqptcanalcomptageDescriptif;
	@Transient
    @XmlElement(name = "eqptcanalcomptage_debitnominal")
    protected Integer eqptcanalcomptageDebitnominal;
	@Transient
    @XmlElement(name = "eqptcanalcomptage_hauteur", required = true)
    protected BigDecimal eqptcanalcomptageHauteur;
	@Transient
    @XmlElement(name = "eqptcanalcomptage_largeur", required = true)
    protected BigDecimal eqptcanalcomptageLargeur;
	@Transient
    @XmlElement(name = "eqptcanalcomptage_longueur", required = true)
    protected BigDecimal eqptcanalcomptageLongueur;
	@Transient
    @XmlElement(name = "eqptcanalcomptage_typecanal", required = true)
    protected TypesCanauxListe eqptcanalcomptageTypecanal;
	@Transient
    @XmlElement(name = "eqptcanalcomptage_mesure", required = true)
    protected String eqptcanalcomptageMesure;
	@Column(name = "id_chg")
	@XmlTransient
	private Integer idChg;

    /**
     * Gets the value of the eqptcanalcomptageEqptsocleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcanalcomptage_eqptsocle_id")
    public String getEqptcanalcomptageEqptsocleId() {
    	if (eqptcanalcomptageEqptsocleId == null) {
    		manageNullException("eqptcanalcomptage_eqptsocle_id");
    	}
        return eqptcanalcomptageEqptsocleId;
    }

    /**
     * Sets the value of the eqptcanalcomptageEqptsocleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptcanalcomptageEqptsocleId(String value) {
        this.eqptcanalcomptageEqptsocleId = value;
    }

    /**
     * Gets the value of the eqptcanalcomptageDescriptif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcanalcomptage_descriptif")
    public String getEqptcanalcomptageDescriptif() {
    	if (eqptcanalcomptageDescriptif == null) {
    		manageNullException("eqptcanalcomptage_descriptif");
    	}
        return eqptcanalcomptageDescriptif;
    }

    /**
     * Sets the value of the eqptcanalcomptageDescriptif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptcanalcomptageDescriptif(String value) {
        this.eqptcanalcomptageDescriptif = value;
    }

    /**
     * Gets the value of the eqptcanalcomptageDebitnominal property.
     * 
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcanalcomptage_debitnominal")
    public int getEqptcanalcomptageDebitnominal() {
    	if (eqptcanalcomptageDebitnominal == null) {
    		manageNullException("eqptcanalcomptage_debitnominal");
    	}
        return eqptcanalcomptageDebitnominal;
    }

    /**
     * Sets the value of the eqptcanalcomptageDebitnominal property.
     * 
     */
    public void setEqptcanalcomptageDebitnominal(int value) {
        this.eqptcanalcomptageDebitnominal = value;
    }

    /**
     * Gets the value of the eqptcanalcomptageHauteur property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcanalcomptage_hauteur")
    public BigDecimal getEqptcanalcomptageHauteur() {
    	if (eqptcanalcomptageHauteur == null) {
    		manageNullException("eqptcanalcomptage_hauteur");
    	}
        return eqptcanalcomptageHauteur;
    }

    /**
     * Sets the value of the eqptcanalcomptageHauteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptcanalcomptageHauteur(BigDecimal value) {
        this.eqptcanalcomptageHauteur = value;
    }

    /**
     * Gets the value of the eqptcanalcomptageLargeur property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcanalcomptage_largeur")
    public BigDecimal getEqptcanalcomptageLargeur() {
    	if (eqptcanalcomptageLargeur == null) {
    		manageNullException("eqptcanalcomptage_largeur");
    	}
        return eqptcanalcomptageLargeur;
    }

    /**
     * Sets the value of the eqptcanalcomptageLargeur property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptcanalcomptageLargeur(BigDecimal value) {
        this.eqptcanalcomptageLargeur = value;
    }

    /**
     * Gets the value of the eqptcanalcomptageLongueur property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcanalcomptage_longueur")
    public BigDecimal getEqptcanalcomptageLongueur() {
    	if (eqptcanalcomptageLongueur == null) {
    		manageNullException("eqptcanalcomptage_longueur");
    	}
        return eqptcanalcomptageLongueur;
    }

    /**
     * Sets the value of the eqptcanalcomptageLongueur property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptcanalcomptageLongueur(BigDecimal value) {
        this.eqptcanalcomptageLongueur = value;
    }

    /**
     * Gets the value of the eqptcanalcomptageTypecanal property.
     * 
     * @return
     *     possible object is
     *     {@link TypesCanauxListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcanalcomptage_typecanal")
    public String getEqptcanalcomptageTypecanal() {
        return TypesCanauxListe.getValue(PatrimoineDAO.PAT_EQPT_CANALCOMPTAGE, "eqptcanalcomptage_typecanal", eqptcanalcomptageTypecanal);
    }

    /**
     * Sets the value of the eqptcanalcomptageTypecanal property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypesCanauxListe }
     *     
     */
    public void setEqptcanalcomptageTypecanal(String value) {
        this.eqptcanalcomptageTypecanal = TypesCanauxListe.fromValue(PatrimoineDAO.PAT_EQPT_CANALCOMPTAGE, "eqptcanalcomptage_typecanal", value);
    }

    /**
     * Gets the value of the eqptcanalcomptageMesure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptcanalcomptage_mesure")
    public String getEqptcanalcomptageMesure() {
    	if (eqptcanalcomptageMesure == null) {
    		manageNullException("eqptcanalcomptage_mesure");
    	}
        return eqptcanalcomptageMesure;
    }

    /**
     * Sets the value of the eqptcanalcomptageMesure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptcanalcomptageMesure(String value) {
        this.eqptcanalcomptageMesure = value;
    }

	public void setIdChg(Integer idChg) {
		this.idChg = idChg;
	}

    private void manageNullException(String champ) {
    	throw new IllegalArgumentException("Table " + PatrimoineDAO.PAT_EQPT_CANALCOMPTAGE + " - Champs " + champ + " - Valeur 'Null' ou non permise par le XSD.");
	}

}
