//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:47:34 AM CET 
//


package bpm.gateway.core.veolia.patrimoine;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeEquipementModuleLamellaire complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeEquipementModuleLamellaire">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eqptmodulelamell_eqptsocle_id" type="{}equipementIDType"/>
 *         &lt;element name="eqptmodulelamell_descriptif" type="{}stringRestricted3000Type"/>
 *         &lt;element name="eqptmodulelamell_debitfonctionnement" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eqptmodulelamell_sectionpasage" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="eqptmodulelamell_surface" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eqptmodulelamell_materiau" type="{}stringRestricted255Type"/>
 *         &lt;element name="eqptmodulelamell_vitessepassage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eqptmodulelamell_inclinaisonlamelle" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eqptmodulelamell_dimensionlamelle" type="{}stringRestricted255Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@Access(AccessType.FIELD)
@Table (name = PatrimoineDAO.PAT_EQPT_MODULELAMELLAIRE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeEquipementModuleLamellaire", propOrder = {
    "eqptmodulelamellEqptsocleId",
    "eqptmodulelamellDescriptif",
    "eqptmodulelamellDebitfonctionnement",
    "eqptmodulelamellSectionpasage",
    "eqptmodulelamellSurface",
    "eqptmodulelamellMateriau",
    "eqptmodulelamellVitessepassage",
    "eqptmodulelamellInclinaisonlamelle",
    "eqptmodulelamellDimensionlamelle"
})
public class TypeEquipementModuleLamellaire {

	@Id
	@Column(name = "eqptmodulelamell_id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@XmlTransient
    protected int id;
	@Transient
    @XmlElement(name = "eqptmodulelamell_eqptsocle_id", required = true)
    protected String eqptmodulelamellEqptsocleId;
	@Transient
    @XmlElement(name = "eqptmodulelamell_descriptif", required = true, defaultValue = "NR")
    protected String eqptmodulelamellDescriptif;
	@Transient
    @XmlElement(name = "eqptmodulelamell_debitfonctionnement")
    protected Integer eqptmodulelamellDebitfonctionnement;
	@Column(name = "eqptmodulelamell_sectionpasage")
    @XmlElement(name = "eqptmodulelamell_sectionpasage")
    protected Integer eqptmodulelamellSectionpasage;
	@Transient
    @XmlElement(name = "eqptmodulelamell_surface")
    protected Integer eqptmodulelamellSurface;
	@Transient
    @XmlElement(name = "eqptmodulelamell_materiau", required = true)
    protected String eqptmodulelamellMateriau;
	@Transient
    @XmlElement(name = "eqptmodulelamell_vitessepassage")
    protected Integer eqptmodulelamellVitessepassage;
	@Transient
    @XmlElement(name = "eqptmodulelamell_inclinaisonlamelle")
    protected Integer eqptmodulelamellInclinaisonlamelle;
	@Transient
    @XmlElement(name = "eqptmodulelamell_dimensionlamelle", required = true)
    protected String eqptmodulelamellDimensionlamelle;
	@Column(name = "id_chg")
	@XmlTransient
	private Integer idChg;

    /**
     * Gets the value of the eqptmodulelamellEqptsocleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptmodulelamell_eqptsocle_id")
    public String getEqptmodulelamellEqptsocleId() {
    	if (eqptmodulelamellEqptsocleId == null) {
    		manageNullException("eqptmodulelamell_eqptsocle_id");
    	}
        return eqptmodulelamellEqptsocleId;
    }

    /**
     * Sets the value of the eqptmodulelamellEqptsocleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptmodulelamellEqptsocleId(String value) {
        this.eqptmodulelamellEqptsocleId = value;
    }

    /**
     * Gets the value of the eqptmodulelamellDescriptif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptmodulelamell_descriptif")
    public String getEqptmodulelamellDescriptif() {
    	if (eqptmodulelamellDescriptif == null) {
    		manageNullException("eqptmodulelamell_descriptif");
    	}
        return eqptmodulelamellDescriptif;
    }

    /**
     * Sets the value of the eqptmodulelamellDescriptif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptmodulelamellDescriptif(String value) {
        this.eqptmodulelamellDescriptif = value;
    }

    /**
     * Gets the value of the eqptmodulelamellDebitfonctionnement property.
     * 
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptmodulelamell_debitfonctionnement")
    public int getEqptmodulelamellDebitfonctionnement() {
    	if (eqptmodulelamellDebitfonctionnement == null) {
    		manageNullException("eqptmodulelamell_debitfonctionnement");
    	}
        return eqptmodulelamellDebitfonctionnement;
    }

    /**
     * Sets the value of the eqptmodulelamellDebitfonctionnement property.
     * 
     */
    public void setEqptmodulelamellDebitfonctionnement(int value) {
        this.eqptmodulelamellDebitfonctionnement = value;
    }

    /**
     * Gets the value of the eqptmodulelamellSectionpasage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEqptmodulelamellSectionpasage() {
        return eqptmodulelamellSectionpasage;
    }

    /**
     * Sets the value of the eqptmodulelamellSectionpasage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEqptmodulelamellSectionpasage(Integer value) {
        this.eqptmodulelamellSectionpasage = value;
    }

    /**
     * Gets the value of the eqptmodulelamellSurface property.
     * 
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptmodulelamell_surface")
    public int getEqptmodulelamellSurface() {
    	if (eqptmodulelamellSurface == null) {
    		manageNullException("eqptmodulelamell_surface");
    	}
        return eqptmodulelamellSurface;
    }

    /**
     * Sets the value of the eqptmodulelamellSurface property.
     * 
     */
    public void setEqptmodulelamellSurface(int value) {
        this.eqptmodulelamellSurface = value;
    }

    /**
     * Gets the value of the eqptmodulelamellMateriau property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptmodulelamell_materiau")
    public String getEqptmodulelamellMateriau() {
    	if (eqptmodulelamellMateriau == null) {
    		manageNullException("eqptmodulelamell_materiau");
    	}
        return eqptmodulelamellMateriau;
    }

    /**
     * Sets the value of the eqptmodulelamellMateriau property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptmodulelamellMateriau(String value) {
        this.eqptmodulelamellMateriau = value;
    }

    /**
     * Gets the value of the eqptmodulelamellVitessepassage property.
     * 
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptmodulelamell_vitessepassage")
    public int getEqptmodulelamellVitessepassage() {
    	if (eqptmodulelamellVitessepassage == null) {
    		manageNullException("eqptmodulelamellVitessepassage");
    	}
        return eqptmodulelamellVitessepassage;
    }

    /**
     * Sets the value of the eqptmodulelamellVitessepassage property.
     * 
     */
    public void setEqptmodulelamellVitessepassage(int value) {
        this.eqptmodulelamellVitessepassage = value;
    }

    /**
     * Gets the value of the eqptmodulelamellInclinaisonlamelle property.
     * 
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptmodulelamell_inclinaisonlamelle")
    public int getEqptmodulelamellInclinaisonlamelle() {
    	if (eqptmodulelamellInclinaisonlamelle == null) {
    		manageNullException("eqptmodulelamell_inclinaisonlamelle");
    	}
        return eqptmodulelamellInclinaisonlamelle;
    }

    /**
     * Sets the value of the eqptmodulelamellInclinaisonlamelle property.
     * 
     */
    public void setEqptmodulelamellInclinaisonlamelle(int value) {
        this.eqptmodulelamellInclinaisonlamelle = value;
    }

    /**
     * Gets the value of the eqptmodulelamellDimensionlamelle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptmodulelamell_dimensionlamelle")
    public String getEqptmodulelamellDimensionlamelle() {
    	if (eqptmodulelamellDimensionlamelle == null) {
    		manageNullException("eqptmodulelamell_dimensionlamelle");
    	}
        return eqptmodulelamellDimensionlamelle;
    }

    /**
     * Sets the value of the eqptmodulelamellDimensionlamelle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptmodulelamellDimensionlamelle(String value) {
        this.eqptmodulelamellDimensionlamelle = value;
    }

	public void setIdChg(Integer idChg) {
		this.idChg = idChg;
	}

    private void manageNullException(String champ) {
    	throw new IllegalArgumentException("Table " + PatrimoineDAO.PAT_EQPT_MODULELAMELLAIRE + " - Champs " + champ + " - Valeur 'Null' ou non permise par le XSD.");
	}

}
