//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:47:34 AM CET 
//


package bpm.gateway.core.veolia.patrimoine;

import java.math.BigDecimal;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeEquipementEchangeurChaleur complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeEquipementEchangeurChaleur">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eqptechangechal_eqptsocle_id" type="{}equipementIDType"/>
 *         &lt;element name="eqptechangechal_descriptif" type="{}stringRestricted3000Type"/>
 *         &lt;element name="eqptechangechal_puissance" type="{}decimalDeuxChiffres"/>
 *         &lt;element name="eqptechangechal_pressionnominale" type="{}pressionsNominalesListe" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@Access(AccessType.FIELD)
@Table (name = PatrimoineDAO.PAT_EQPT_ECHANGEURCHALEUR)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeEquipementEchangeurChaleur", propOrder = {
    "eqptechangechalEqptsocleId",
    "eqptechangechalDescriptif",
    "eqptechangechalPuissance",
    "eqptechangechalPressionnominale"
})
public class TypeEquipementEchangeurChaleur {

	@Id
	@Column(name = "eqptechangechal_id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@XmlTransient
    protected int id;
	@Transient
    @XmlElement(name = "eqptechangechal_eqptsocle_id", required = true)
    protected String eqptechangechalEqptsocleId;
	@Transient
    @XmlElement(name = "eqptechangechal_descriptif", required = true, defaultValue = "NR")
    protected String eqptechangechalDescriptif;
	@Transient
    @XmlElement(name = "eqptechangechal_puissance", required = true)
    protected BigDecimal eqptechangechalPuissance;
	@Transient
    @XmlElement(name = "eqptechangechal_pressionnominale")
    protected PressionsNominalesListe eqptechangechalPressionnominale;
	@Column(name = "id_chg")
	@XmlTransient
	private Integer idChg;

    /**
     * Gets the value of the eqptechangechalEqptsocleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptechangechal_eqptsocle_id")
    public String getEqptechangechalEqptsocleId() {
    	if (eqptechangechalEqptsocleId == null) {
    		manageNullException("eqptechangechal_eqptsocle_id");
    	}
        return eqptechangechalEqptsocleId;
    }

    /**
     * Sets the value of the eqptechangechalEqptsocleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptechangechalEqptsocleId(String value) {
        this.eqptechangechalEqptsocleId = value;
    }

    /**
     * Gets the value of the eqptechangechalDescriptif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptechangechal_descriptif")
    public String getEqptechangechalDescriptif() {
    	if (eqptechangechalDescriptif == null) {
    		manageNullException("eqptechangechal_descriptif");
    	}
        return eqptechangechalDescriptif;
    }

    /**
     * Sets the value of the eqptechangechalDescriptif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqptechangechalDescriptif(String value) {
        this.eqptechangechalDescriptif = value;
    }

    /**
     * Gets the value of the eqptechangechalPuissance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptechangechal_puissance")
    public BigDecimal getEqptechangechalPuissance() {
    	if (eqptechangechalPuissance == null) {
    		manageNullException("eqptechangechal_puissance");
    	}
        return eqptechangechalPuissance;
    }

    /**
     * Sets the value of the eqptechangechalPuissance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEqptechangechalPuissance(BigDecimal value) {
        this.eqptechangechalPuissance = value;
    }

    /**
     * Gets the value of the eqptechangechalPressionnominale property.
     * 
     * @return
     *     possible object is
     *     {@link PressionsNominalesListe }
     *     
     */
	@Access(AccessType.PROPERTY)
	@Column(name = "eqptechangechal_pressionnominale")
    public String getEqptechangechalPressionnominale() {
        return PressionsNominalesListe.getValue(PatrimoineDAO.PAT_EQPT_ECHANGEURCHALEUR, "eqptechangechal_pressionnominale", eqptechangechalPressionnominale, false);
    }

    /**
     * Sets the value of the eqptechangechalPressionnominale property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressionsNominalesListe }
     *     
     */
    public void setEqptechangechalPressionnominale(String value) {
        this.eqptechangechalPressionnominale = PressionsNominalesListe.fromValue(PatrimoineDAO.PAT_EQPT_ECHANGEURCHALEUR, "eqptechangechal_pressionnominale", value);
    }

	public void setIdChg(Integer idChg) {
		this.idChg = idChg;
	}

    private void manageNullException(String champ) {
    	throw new IllegalArgumentException("Table " + PatrimoineDAO.PAT_EQPT_ECHANGEURCHALEUR + " - Champs " + champ + " - Valeur 'Null' ou non permise par le XSD.");
	}

}
