#!/bin/sh  
### BEGIN INIT INFO
# Provides:          aklabox
# Required-Start:    $remote_fs $syslog mysql
# Required-Stop:     $remote_fs $syslog mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: This script starts and stops the aklabox daemon
# Description:       This script starts and stops the aklabox daemon
#                    Ce script demarre et arrete le serveur aklabox
### END INIT INFO

# Author: BPM Conseil
# Installation:
#                    Copier le script dans le dossier /etc/init.d
#
#                    Lancer la commande "update-rc.d aklabox defaults"
#                    pour inscrire le service aklabox sur le serveur.
#
#                    AklaBox peut ensuite etre demarre avec la commande
#                    "service aklabox start|stop|restart"

#-----------------CONFIGURATION AKLABOX -----------------#
#Prog name showed in logs
prog="AklaBox 17.06"

#Aklabox path
aklaboxPath="/aklabox/aklabox"

#Path and file name for PID
CATALINA_PID="/var/run/aklabox/aklabox.pid"
CATALINA_FOLDER="/var/run/aklabox/"

#User which launch Aklabox
USER=root

#Time limit to start in seconds
limit=300

#--------------------------------------------------------#

RETVAL=0

start() {
	# Check if atd is already running
	if [ ! -f $CATALINA_PID ]; then
		echo -n $"Starting $prog : "
		
		# Suppression du fichier Catalina.out
		echo
		echo "Deleting catalina.out"
		cp $aklaboxPath/logs/catalina.out $aklaboxPath/logs/catalina.out.$(date +"%Y_%m_%d_%H_%M_%S").log
		rm -rf $aklaboxPath/logs/catalina.out
		
		# La suppression du répertoire Work n'est pas nécessaire dans un usage normal.
		#Supprimer le répertoire en cas de problème au démarrage du serveur.
		rm -rf $aklaboxPath/work
		
		# Create pid folder if not exist
		if [ ! -d "$CATALINA_FOLDER" ]; then
			echo
			echo "Create AklaBox PID folder"
			mkdir $CATALINA_FOLDER
		fi
		
		if [ "$USER" = "root" ]; then
			cd $aklaboxPath
			./start-aklabox.sh start '' $CATALINA_PID
		else
			sudo -u $USER -H sh -c "cd $aklaboxPath; ./start-aklabox.sh start '' $CATALINA_PID"
		fi
		
		RETVAL=$?
		
		echo
		echo  -n $"Please wait few seconds to let $prog tomcat start correctly"
		echo
		
		export SEC=$limit
		Started="KO"
		WellStarted="KO"
		while (true); do
			if [ -n "`cat ${aklaboxPath}/logs/catalina.out | grep "^INFOS: Server startup in"`" ]; then
				WellStarted="ok"
			fi
			echo -n "."
			sleep 1
			SEC="`expr $SEC - 1`"
			if [ "$WellStarted" = "ok" ]; then
				Started="ok"
				break
			fi
			if [ "$SEC" = "0" ]; then
				echo 
				echo -n $" Time limit to start excedeed"
				echo 
				echo ""
				
				stop
				
				exit $RETVAL
			fi
		done
	
		if [ "$Started" = "KO" ]; then
			echo -n $" Failed to start"
			echo 
			echo ""
			exit $RETVAL
		fi
		echo
		echo ""
	else 
		echo
	    echo  $"$prog is already running..."
    fi
	
	echo
	echo "$prog started."
	
	return $RETVAL
}

stopold() {
    echo -n $"Stopping $prog : "
	if [ ! -f $CATALINA_PID ]; then
		echo
		echo $"$prog is already stopped..."
	else
		if [ "$USER" = "root" ]; then
			cd $aklaboxPath
			./stop-aklabox.sh $CATALINA_PID
			RETVAL=$?
		else
			sudo -u $USER -H sh -c "cd $aklaboxPath; ./stop-aklabox.sh $CATALINA_PID"	
			RETVAL=$?
		fi
		
		if [ $RETVAL -eq 0 ] ; then
			rm -f $CATALINA_PID
			echo
			echo $"$prog is now stopped ..."
		else
			echo
			echo $"A problem occured when stopping $prog ..."
		fi
	fi
	return $RETVAL
}

stop() {
    pkill java
	rm -rf /var/run/aklabox/aklabox.pid
}

restart() {
        stop
        start
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
reload|restart)
        restart
        ;;
*)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac
exit $?

