//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.17 at 04:24:12 PM CET 
//


package bpm.gateway.core.tsbn.referentiels;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LIB_SECTEUR" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DATE_DEB" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DATE_FIN" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class SECTEUR {

    @XmlAttribute(name = "TYPE")
    protected String type;
    @XmlAttribute(name = "LIB_SECTEUR")
    protected String libsecteur;
    @XmlAttribute(name = "DATE_DEB")
    protected String datedeb;
    @XmlAttribute(name = "DATE_FIN")
    protected String datefin;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the libsecteur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibsecteur() {
        return libsecteur;
    }

    /**
     * Sets the value of the libsecteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibsecteur(String value) {
        this.libsecteur = value;
    }

    /**
     * Gets the value of the datedeb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatedeb() {
        return datedeb;
    }

    /**
     * Sets the value of the datedeb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatedeb(String value) {
        this.datedeb = value;
    }

    /**
     * Gets the value of the datefin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatefin() {
        return datefin;
    }

    /**
     * Sets the value of the datefin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatefin(String value) {
        this.datefin = value;
    }

}
