//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.18 at 03:51:39 PM CEST 
//


package bpm.gateway.core.tsbn.atih;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FINESS" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *         &lt;element name="ORDRE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="EXTRACT" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *         &lt;element name="DATEDEBUT" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *         &lt;element name="DATEFIN" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "finess",
    "ordre",
    "extract",
    "datedebut",
    "datefin"
})
public class ETABLISSEMENT {

    @XmlElement(name = "FINESS", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String finess;
    @XmlElement(name = "ORDRE")
    protected int ordre;
    @XmlElement(name = "EXTRACT", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String extract;
    @XmlElement(name = "DATEDEBUT", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String datedebut;
    @XmlElement(name = "DATEFIN", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String datefin;

    /**
     * Gets the value of the finess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFINESS() {
        return finess;
    }

    /**
     * Sets the value of the finess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFINESS(String value) {
        this.finess = value;
    }

    /**
     * Gets the value of the ordre property.
     * 
     */
    public int getORDRE() {
        return ordre;
    }

    /**
     * Sets the value of the ordre property.
     * 
     */
    public void setORDRE(int value) {
        this.ordre = value;
    }

    /**
     * Gets the value of the extract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXTRACT() {
        return extract;
    }

    /**
     * Sets the value of the extract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXTRACT(String value) {
        this.extract = value;
    }

    /**
     * Gets the value of the datedebut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATEDEBUT() {
        return datedebut;
    }

    /**
     * Sets the value of the datedebut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATEDEBUT(String value) {
        this.datedebut = value;
    }

    /**
     * Gets the value of the datefin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATEFIN() {
        return datefin;
    }

    /**
     * Sets the value of the datefin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATEFIN(String value) {
        this.datefin = value;
    }

}
