package bpm.birt.fusioncharts.core.swf;

public final class Charts { 	
//	public static final String AREA_2D = "Area2D.swf";
//	public static final String BAR_2D = "Bar2D.swf";
//	public static final String BUBBLE = "Bubble.swf";
//	public static final String COLUMN_2D = "Column2D.swf";
//	public static final String COLUMN_3D = "Column3D.swf";
//	public static final String DOUGHNUT_2D = "Doughnut2D.swf";
//	public static final String DOUGHNUT_3D = "Doughnut3D.swf";
//	public static final String LINE = "Line.swf";
//	public static final String MARIMEKKO = "Marimekko.swf";
//	public static final String MS_AREA = "MSArea.swf";
//	public static final String MS_BAR_2D = "MSBar2D.swf";
//	public static final String MS_BAR_3D = "MSBar3D.swf";
//	public static final String MS_COLUMN_2D = "MSColumn2D.swf";
//	public static final String MS_COLUMN_3D = "MSColumn3D.swf";
//	public static final String MS_COLUMN_3D_LINE_DY = "MSColumn3DLineDY.swf";
//	public static final String MS_COLUMN_LINE_3D = "MSColumnLine3D.swf";
//	public static final String MS_COMBI_2D = "MSCombi2D.swf";
//	public static final String MS_COMBI_3D = "MSCombi3D.swf";
//	public static final String MS_COMBI_DY_2D = "MSCombiDY2D.swf";
//	public static final String MS_LINE = "MSLine.swf";
//	public static final String MS_STACKED_COLUMN_2D = "MSStackedColumn2D.swf";
//	public static final String MS_STACKED_COLUMN_2D_LINE_DY = "MSStackedColumn2DLineDY.swf";
//	public static final String PARETO_2D = "Pareto2D.swf";
//	public static final String PARETO_3D = "Pareto3D.swf";
//	public static final String PIE_2D = "Pie2D.swf";
//	public static final String PIE_3D = "Pie3D.swf";
//	public static final String RADAR = "Radar.swf";
//	public static final String SCATTER = "Scatter.swf";
//	public static final String SCROLL_AREA_2D = "ScrollArea2D.swf";
//	public static final String SCROLL_COLUMN_2D = "ScrollColumn2D.swf";
//	public static final String SCROLL_COMBI_2D = "ScrollCombi2D.swf";
//	public static final String SCROLL_COMBI_DY_2D = "ScrollCombiDY2D.swf";
//	public static final String SCROLL_LINE_2D = "ScrollLine2D.swf";
//	public static final String SCROLL_STACKED_COLUMN_2D = "ScrollStackedColumn2D.swf";
//	public static final String SS_GRID = "SSGrid.swf";
//	public static final String STACKED_AREA_2D = "StackedArea2D.swf";
//	public static final String STACKED_BAR_2D = "StackedBar2D.swf";
//	public static final String STACKED_BAR_3D = "StackedBar3D.swf";
//	public static final String STACKED_COLUMN_2D = "StackedColumn2D.swf";
//	public static final String STACKED_COLUMN_2D_LINE = "StackedColumn2DLine.swf";
//	public static final String STACKED_COLUMN_3D = "StackedColumn3D.swf";
//	public static final String STACKED_COLUMN_3D_LINE = "StackedColumn3DLine.swf";
//	public static final String STACKED_COLUMN_3D_LINE_DY = "StackedColumn3DLineDY.swf";
//	public static final String ZOOM_LINE = "ZoomLine.swf";
//	
	public static final String FUSION_CHART_JS = "FusionCharts.js";
}
