//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.16 at 11:44:33 AM CEST 
//


package bpm.gateway.core.tsbn.appels;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id_agent" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="id_struct_tgt" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="id_struct_dec" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="id_agent_dec" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="mod_tsf" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tba" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="tna" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="dur_dec" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="app_ori" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class AppTrsf {
	
	@XmlTransient
	private int id;

    @XmlAttribute(name = "id_agent", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object idAgent;
    @XmlAttribute(name = "id_struct_tgt", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object idStructTgt;
    @XmlAttribute(name = "id_struct_dec")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object idStructDec;
    @XmlAttribute(name = "id_agent_dec")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object idAgentDec;
    @XmlAttribute(name = "mod_tsf", required = true)
    protected String modTsf;
    @XmlAttribute(name = "tba", required = true)
    protected float tba;
    @XmlAttribute(name = "tna")
    protected Float tna;
    @XmlAttribute(name = "dur_dec")
    protected Float durDec;
    @XmlAttribute(name = "app_ori", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object appOri;

    public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

    /**
     * Gets the value of the idAgent property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIdAgent() {
        return idAgent != null ? ((Agents) idAgent).getIdAgent() : null;
    }

    /**
     * Sets the value of the idAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIdAgent(Object value) {
    	if(!(value instanceof String)) {
    		this.idAgent = value;
    	}
    }

    /**
     * Gets the value of the idStructTgt property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIdStructTgt() {
        return idStructTgt != null ? ((Structures) idStructTgt).getIdStruct() : null;
    }

    /**
     * Sets the value of the idStructTgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIdStructTgt(Object value) {
    	if(!(value instanceof String)) {
    		this.idStructTgt = value;
    	}
    }

    /**
     * Gets the value of the idStructDec property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIdStructDec() {
        return idStructDec != null ? ((Structures) idStructDec).getIdStruct() : null;
    }

    /**
     * Sets the value of the idStructDec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIdStructDec(Object value) {
    	if(!(value instanceof String)) {
    		this.idStructDec = value;
    	}
    }

    /**
     * Gets the value of the idAgentDec property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIdAgentDec() {
        return idAgentDec != null ? ((Agents) idAgentDec).getIdAgent() : null;
    }

    /**
     * Sets the value of the idAgentDec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIdAgentDec(Object value) {
    	if(!(value instanceof String)) {
    		this.idAgentDec = value;
    	}
    }

    /**
     * Gets the value of the modTsf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModTsf() {
        return modTsf;
    }

    /**
     * Sets the value of the modTsf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModTsf(String value) {
        this.modTsf = value;
    }

    /**
     * Gets the value of the tba property.
     * 
     */
    public float getTba() {
        return tba;
    }

    /**
     * Sets the value of the tba property.
     * 
     */
    public void setTba(float value) {
        this.tba = value;
    }

    /**
     * Gets the value of the tna property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Float getTna() {
        return tna;
    }

    /**
     * Sets the value of the tna property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTna(Float value) {
        this.tna = value;
    }

    /**
     * Gets the value of the durDec property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Float getDurDec() {
        return durDec;
    }

    /**
     * Sets the value of the durDec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDurDec(Float value) {
        this.durDec = value;
    }

    /**
     * Gets the value of the appOri property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAppOri() {
        return appOri != null ? ((Appel) appOri).getIdAppel() : null;
    }

    /**
     * Sets the value of the appOri property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAppOri(Object value) {
    	if(!(value instanceof String)) {
    		this.appOri = value;
    	}
    }

	public void setIdSamu(String idSamu) {
		//Do nothing
	}

}
