//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.16 at 11:44:33 AM CEST 
//


package bpm.gateway.core.tsbn.appels;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Communes" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="ID_COM" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                 &lt;attribute name="LIB_COM" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CP_COM" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id_secteur" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="lib_secteur" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id_secteur_pere" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="typ_sec" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="typ_dec" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "communes"
})
public class Secteurs {

    @XmlElement(name = "Communes")
    protected List<Communes> communes;
    @XmlAttribute(name = "id_secteur", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String idSecteur;
    @XmlAttribute(name = "lib_secteur", required = true)
    protected String libSecteur;
    @XmlAttribute(name = "id_secteur_pere")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object idSecteurPere;
    @XmlAttribute(name = "typ_sec", required = true)
    protected String typSec;
    @XmlAttribute(name = "typ_dec")
    protected String typDec;

    /**
     * Gets the value of the communes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the communes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommunes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Communes }
     * 
     * 
     */
    public List<Communes> getCommunes() {
        if (communes == null) {
            communes = new ArrayList<Communes>();
        }
        return this.communes;
    }

    //Not used, for hibernate
    public void setCommunes(List<Communes> communes) {
    	this.communes = communes;
    }

    /**
     * Gets the value of the idSecteur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSecteur() {
        return idSecteur;
    }

    /**
     * Sets the value of the idSecteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdSecteur(String value) {
        this.idSecteur = value;
    }

    /**
     * Gets the value of the libSecteur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibSecteur() {
        return libSecteur;
    }

    /**
     * Sets the value of the libSecteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibSecteur(String value) {
        this.libSecteur = value;
    }

    /**
     * Gets the value of the idSecteurPere property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public String getIdSecteurPere() {
        return idSecteurPere != null ? ((Secteurs) idSecteurPere).getIdSecteur() : null;
    }

    /**
     * Sets the value of the idSecteurPere property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIdSecteurPere(Object value) {
        this.idSecteurPere = value;
    }
    
    //Not used, for hibernate
    public void setIdSecteurPere(String value) { }

    /**
     * Gets the value of the typSec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypSec() {
        return typSec;
    }

    /**
     * Sets the value of the typSec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypSec(String value) {
        this.typSec = value;
    }

    /**
     * Gets the value of the typDec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypDec() {
        return typDec;
    }

    /**
     * Sets the value of the typDec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypDec(String value) {
        this.typDec = value;
    }

	public void setIdSamu(String idSamu) {
		if (communes != null) {
			for (Communes commune : communes) {
				commune.setIdSamu(idSamu);
			}
		}
		
		String currentId = getIdSecteur();
		
		String prefix = idSamu + "-";
		if (!currentId.startsWith(prefix)) {
			setIdSecteur(prefix + currentId);
		}
	}

}
