//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.20 at 09:49:13 AM CEST 
//

package bpm.connector.seveneleven.model;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for PaymentGatewayResponse complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentGatewayResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="transactionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="approvalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="referenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="terminalNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="amount" type="{}Price"/>
 *         &lt;element name="paymentServiceTypeEnumId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="PRDS_PAY_EXTERNAL"/>
 *               &lt;enumeration value="PRDS_PAY_CREDIT"/>
 *               &lt;enumeration value="PRDS_PAY_REFUND"/>
 *               &lt;enumeration value="PRDS_PAY_CAPTURE"/>
 *               &lt;enumeration value="PRDS_PAY_RELEASE"/>
 *               &lt;enumeration value="PRDS_PAY_REAUTH"/>
 *               &lt;enumeration value="PRDS_PAY_AUTH_VERIFY"/>
 *               &lt;enumeration value="PRDS_PAY_AUTH"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="batchNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="traceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="merchantNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="attributeList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attribute" type="{}Attribute" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentGatewayResponse", propOrder = {

})
@Entity
@Table(name = "payment_gateway_response")
public class PaymentGatewayResponse {

	@Id
	@GeneratedValue
	private Integer id;

	@XmlElement(required = true, type = String.class)
	@XmlJavaTypeAdapter(TimestampAdapter.class)
	@XmlSchemaType(name = "dateTime")
	protected Timestamp transactionDate;
	@XmlElement(required = true)
	protected String approvalCode;
	@XmlElement(required = true)
	protected String referenceNumber;
	@XmlElement(required = true)
	protected String terminalNumber;

	@XmlElement(required = true)
	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "priceId")
	protected Price amount;

	protected String paymentServiceTypeEnumId;
	protected String batchNumber;
	protected String traceNumber;
	protected String merchantNumber;

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "attributeListId")
	protected PaymentGatewayResponse.AttributeList attributeList;

	/**
	 * Gets the value of the transactionDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public Timestamp getTransactionDate() {
		return transactionDate;
	}

	/**
	 * Sets the value of the transactionDate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTransactionDate(Timestamp value) {
		this.transactionDate = value;
	}

	/**
	 * Gets the value of the approvalCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getApprovalCode() {
		return approvalCode;
	}

	/**
	 * Sets the value of the approvalCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setApprovalCode(String value) {
		this.approvalCode = value;
	}

	/**
	 * Gets the value of the referenceNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReferenceNumber() {
		return referenceNumber;
	}

	/**
	 * Sets the value of the referenceNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReferenceNumber(String value) {
		this.referenceNumber = value;
	}

	/**
	 * Gets the value of the terminalNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTerminalNumber() {
		return terminalNumber;
	}

	/**
	 * Sets the value of the terminalNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTerminalNumber(String value) {
		this.terminalNumber = value;
	}

	/**
	 * Gets the value of the amount property.
	 * 
	 * @return possible object is {@link Price }
	 * 
	 */
	public Price getAmount() {
		return amount;
	}

	/**
	 * Sets the value of the amount property.
	 * 
	 * @param value
	 *            allowed object is {@link Price }
	 * 
	 */
	public void setAmount(Price value) {
		this.amount = value;
	}

	/**
	 * Gets the value of the paymentServiceTypeEnumId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPaymentServiceTypeEnumId() {
		return paymentServiceTypeEnumId;
	}

	/**
	 * Sets the value of the paymentServiceTypeEnumId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPaymentServiceTypeEnumId(String value) {
		this.paymentServiceTypeEnumId = value;
	}

	/**
	 * Gets the value of the batchNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBatchNumber() {
		return batchNumber;
	}

	/**
	 * Sets the value of the batchNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBatchNumber(String value) {
		this.batchNumber = value;
	}

	/**
	 * Gets the value of the traceNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTraceNumber() {
		return traceNumber;
	}

	/**
	 * Sets the value of the traceNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTraceNumber(String value) {
		this.traceNumber = value;
	}

	/**
	 * Gets the value of the merchantNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMerchantNumber() {
		return merchantNumber;
	}

	/**
	 * Sets the value of the merchantNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMerchantNumber(String value) {
		this.merchantNumber = value;
	}

	/**
	 * Gets the value of the attributeList property.
	 * 
	 * @return possible object is {@link PaymentGatewayResponse.AttributeList }
	 * 
	 */
	public PaymentGatewayResponse.AttributeList getAttributeList() {
		return attributeList;
	}

	/**
	 * Sets the value of the attributeList property.
	 * 
	 * @param value
	 *            allowed object is {@link PaymentGatewayResponse.AttributeList }
	 * 
	 */
	public void setAttributeList(PaymentGatewayResponse.AttributeList value) {
		this.attributeList = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="attribute" type="{}Attribute" maxOccurs="unbounded"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "id", "attribute" })
	@Entity
	@Table(name = "payment_gateway_response_attribute_list")
	public static class AttributeList {

		@Id
		@GeneratedValue
		@Column(name = "attributeListId")
		private Integer id;

		@XmlElement(required = true)
		@OneToMany(cascade = CascadeType.ALL)
		@JoinColumn(name = "attributeListId")
		protected List<Attribute> attribute;

		/**
		 * Gets the value of the attribute property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the attribute property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getAttribute().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Attribute }
		 * 
		 * 
		 */
		public List<Attribute> getAttribute() {
			if (attribute == null) {
				attribute = new ArrayList<Attribute>();
			}
			return this.attribute;
		}

	}

}
