//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.20 at 09:49:13 AM CEST 
//

package bpm.connector.seveneleven.model;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="returnTransactionId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="terminalId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="referenceId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cashierPartyId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="managerPartyId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="customerPartyId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="transactionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="statusId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="COMPLETED"/>
 *               &lt;enumeration value="CANCELLED"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="returnItemList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="returnItem" type="{}ReturnItem" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="adjustmentList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="adjustment" type="{}ReturnAdjustment" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="documentId" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="60"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "returns")
@Entity
@Table(name = "returns")
public class Returns {

	@Id
	@XmlElement(required = true)
	protected String returnTransactionId;

	protected String terminalId;
	protected String referenceId;
	protected String cashierPartyId;
	protected String managerPartyId;

	@XmlElement(required = true)
	protected String customerPartyId;

	@XmlElement(required = true, type = String.class)
	@XmlJavaTypeAdapter(TimestampAdapter.class)
	@XmlSchemaType(name = "dateTime")
	protected Timestamp transactionDate;

	@XmlElement(required = true)
	protected String statusId;

	@XmlElement(required = true)
	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "returnItemListId")
	protected Returns.ReturnItemList returnItemList;

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "adjustmentListId")
	protected Returns.AdjustmentList adjustmentList;

	@XmlAttribute(name = "documentId", required = true)
	protected String documentId;

	/**
	 * Gets the value of the returnTransactionId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReturnTransactionId() {
		return returnTransactionId;
	}

	/**
	 * Sets the value of the returnTransactionId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReturnTransactionId(String value) {
		this.returnTransactionId = value;
	}

	/**
	 * Gets the value of the terminalId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTerminalId() {
		return terminalId;
	}

	/**
	 * Sets the value of the terminalId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTerminalId(String value) {
		this.terminalId = value;
	}

	/**
	 * Gets the value of the referenceId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReferenceId() {
		return referenceId;
	}

	/**
	 * Sets the value of the referenceId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReferenceId(String value) {
		this.referenceId = value;
	}

	/**
	 * Gets the value of the cashierPartyId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCashierPartyId() {
		return cashierPartyId;
	}

	/**
	 * Sets the value of the cashierPartyId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCashierPartyId(String value) {
		this.cashierPartyId = value;
	}

	/**
	 * Gets the value of the managerPartyId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getManagerPartyId() {
		return managerPartyId;
	}

	/**
	 * Sets the value of the managerPartyId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setManagerPartyId(String value) {
		this.managerPartyId = value;
	}

	/**
	 * Gets the value of the customerPartyId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCustomerPartyId() {
		return customerPartyId;
	}

	/**
	 * Sets the value of the customerPartyId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCustomerPartyId(String value) {
		this.customerPartyId = value;
	}

	/**
	 * Gets the value of the transactionDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public Timestamp getTransactionDate() {
		return transactionDate;
	}

	/**
	 * Sets the value of the transactionDate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTransactionDate(Timestamp value) {
		this.transactionDate = value;
	}

	/**
	 * Gets the value of the statusId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStatusId() {
		return statusId;
	}

	/**
	 * Sets the value of the statusId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStatusId(String value) {
		this.statusId = value;
	}

	/**
	 * Gets the value of the returnItemList property.
	 * 
	 * @return possible object is {@link Returns.ReturnItemList }
	 * 
	 */
	public Returns.ReturnItemList getReturnItemList() {
		return returnItemList;
	}

	/**
	 * Sets the value of the returnItemList property.
	 * 
	 * @param value
	 *            allowed object is {@link Returns.ReturnItemList }
	 * 
	 */
	public void setReturnItemList(Returns.ReturnItemList value) {
		this.returnItemList = value;
	}

	/**
	 * Gets the value of the adjustmentList property.
	 * 
	 * @return possible object is {@link Returns.AdjustmentList }
	 * 
	 */
	public Returns.AdjustmentList getAdjustmentList() {
		return adjustmentList;
	}

	/**
	 * Sets the value of the adjustmentList property.
	 * 
	 * @param value
	 *            allowed object is {@link Returns.AdjustmentList }
	 * 
	 */
	public void setAdjustmentList(Returns.AdjustmentList value) {
		this.adjustmentList = value;
	}

	/**
	 * Gets the value of the documentId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDocumentId() {
		return documentId;
	}

	/**
	 * Sets the value of the documentId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDocumentId(String value) {
		this.documentId = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="adjustment" type="{}ReturnAdjustment" maxOccurs="unbounded"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "adjustment" })
	@Entity
	@Table(name = "returns_adjustment_list")
	public static class AdjustmentList {

		@Id
		@GeneratedValue
		@Column(name = "adjustmentListId")
		private Integer id;

		@XmlElement(required = true)
		@OneToMany(cascade = CascadeType.ALL)
		@JoinColumn(name = "adjustmentListId")
		protected List<ReturnAdjustment> adjustment;

		/**
		 * Gets the value of the adjustment property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the adjustment property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getAdjustment().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link ReturnAdjustment }
		 * 
		 * 
		 */
		public List<ReturnAdjustment> getAdjustment() {
			if (adjustment == null) {
				adjustment = new ArrayList<ReturnAdjustment>();
			}
			return this.adjustment;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="returnItem" type="{}ReturnItem" maxOccurs="unbounded"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "returnItem" })
	@Entity
	@Table(name = "return_item_list")
	public static class ReturnItemList {

		@Id
		@GeneratedValue
		@Column(name = "returnItemListId")
		private Integer id;

		@XmlElement(required = true)
		@OneToMany(cascade = CascadeType.ALL)
		@JoinColumn(name = "returnItemListId")
		protected List<ReturnItem> returnItem;

		/**
		 * Gets the value of the returnItem property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the returnItem property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getReturnItem().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link ReturnItem }
		 * 
		 * 
		 */
		public List<ReturnItem> getReturnItem() {
			if (returnItem == null) {
				returnItem = new ArrayList<ReturnItem>();
			}
			return this.returnItem;
		}

	}

}
