//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.20 at 09:49:13 AM CEST 
//


package bpm.connector.seveneleven.model;

import java.math.BigDecimal;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReturnAdjustment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReturnAdjustment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="adjustmentTypeId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *               &lt;enumeration value="RET_PROMOTION_ADJ"/>
 *               &lt;enumeration value="RET_REPLACE_ADJ"/>
 *               &lt;enumeration value="RET_DISCOUNT_ADJ"/>
 *               &lt;enumeration value="RET_FEE_ADJ"/>
 *               &lt;enumeration value="RET_MISC_ADJ"/>
 *               &lt;enumeration value="RET_SALES_TAX_ADJ"/>
 *               &lt;enumeration value="RET_SHIPPING_ADJ"/>
 *               &lt;enumeration value="RET_SURCHARGE_ADJ"/>
 *               &lt;enumeration value="RET_ADD_FEATURE_ADJ"/>
 *               &lt;enumeration value="RET_WARRANTY_ADJ"/>
 *               &lt;enumeration value="RET_MKTG_PKG_ADJ"/>
 *               &lt;enumeration value="RET_MAN_ADJ"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="comments" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="amount" type="{}Price" minOccurs="0"/>
 *         &lt;element name="percentage" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="productPromo" type="{}Promo" minOccurs="0"/>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReturnAdjustment", propOrder = {

})
@Entity
@Table(name = "return_adjustment")
public class ReturnAdjustment {

	@Id
	@GeneratedValue
	private Integer id;
	
    @XmlElement(required = true)
    protected String adjustmentTypeId;
    protected String comments;

	@ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name="priceId")
    protected Price amount;
    
    protected BigDecimal percentage;

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name="promoProductId")
    protected Promo productPromo;
    
    protected BigDecimal quantity;

    /**
     * Gets the value of the adjustmentTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdjustmentTypeId() {
        return adjustmentTypeId;
    }

    /**
     * Sets the value of the adjustmentTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdjustmentTypeId(String value) {
        this.adjustmentTypeId = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Price }
     *     
     */
    public Price getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Price }
     *     
     */
    public void setAmount(Price value) {
        this.amount = value;
    }

    /**
     * Gets the value of the percentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPercentage() {
        return percentage;
    }

    /**
     * Sets the value of the percentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPercentage(BigDecimal value) {
        this.percentage = value;
    }

    /**
     * Gets the value of the productPromo property.
     * 
     * @return
     *     possible object is
     *     {@link Promo }
     *     
     */
    public Promo getProductPromo() {
        return productPromo;
    }

    /**
     * Sets the value of the productPromo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Promo }
     *     
     */
    public void setProductPromo(Promo value) {
        this.productPromo = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantity(BigDecimal value) {
        this.quantity = value;
    }

}
