//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.20 at 09:49:13 AM CEST 
//

package bpm.connector.seveneleven.model;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="salesList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}sales" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="returnList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}returns" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="dateCreated" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="facilityId" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="20"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute ref="{}version"/>
 *       &lt;attribute name="action" default="LIST">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="CREATE"/>
 *             &lt;enumeration value="LIST"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="documentId" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="60"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "transactionList")
@Entity
@Table(name = "transaction_list")
public class TransactionList {

	@Id
	@GeneratedValue
	private Integer id;

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "salesListId")
	protected TransactionList.SalesList salesList;

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "returnListId")
	protected TransactionList.ReturnList returnList;

	@XmlAttribute(name = "dateCreated", required = true)
	@XmlJavaTypeAdapter(TimestampAdapter.class)
	@XmlSchemaType(name = "dateTime")
	protected Timestamp dateCreated;

	@XmlAttribute(name = "facilityId", required = true)
	protected String facilityId;

	@XmlAttribute(name = "version")
	public final static String VERSION = "1.0.4";

	@XmlAttribute(name = "transaction_action")
	protected String action;

	@XmlAttribute(name = "documentId", required = true)
	protected String documentId;

	/**
	 * Gets the value of the salesList property.
	 * 
	 * @return possible object is {@link TransactionList.SalesList }
	 * 
	 */
	public TransactionList.SalesList getSalesList() {
		return salesList;
	}

	/**
	 * Sets the value of the salesList property.
	 * 
	 * @param value
	 *            allowed object is {@link TransactionList.SalesList }
	 * 
	 */
	public void setSalesList(TransactionList.SalesList value) {
		this.salesList = value;
	}

	/**
	 * Gets the value of the returnList property.
	 * 
	 * @return possible object is {@link TransactionList.ReturnList }
	 * 
	 */
	public TransactionList.ReturnList getReturnList() {
		return returnList;
	}

	/**
	 * Sets the value of the returnList property.
	 * 
	 * @param value
	 *            allowed object is {@link TransactionList.ReturnList }
	 * 
	 */
	public void setReturnList(TransactionList.ReturnList value) {
		this.returnList = value;
	}

	/**
	 * Gets the value of the dateCreated property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public Timestamp getDateCreated() {
		return dateCreated;
	}

	/**
	 * Sets the value of the dateCreated property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDateCreated(Timestamp value) {
		this.dateCreated = value;
	}

	/**
	 * Gets the value of the facilityId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFacilityId() {
		return facilityId;
	}

	/**
	 * Sets the value of the facilityId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFacilityId(String value) {
		this.facilityId = value;
	}

	/**
	 * Gets the value of the action property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAction() {
		if (action == null) {
			return "LIST";
		}
		else {
			return action;
		}
	}

	/**
	 * Sets the value of the action property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAction(String value) {
		this.action = value;
	}

	/**
	 * Gets the value of the documentId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDocumentId() {
		return documentId;
	}

	/**
	 * Sets the value of the documentId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDocumentId(String value) {
		this.documentId = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element ref="{}returns" maxOccurs="unbounded"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "returns" })
	@Entity
	@Table(name = "transaction_return_list")
	public static class ReturnList {

		@Id
		@GeneratedValue
		@Column(name = "returnListId")
		private Integer id;

		@XmlElement(required = true)
		@OneToMany(cascade = CascadeType.ALL)
		@JoinColumn(name = "returnListId")
		protected List<Returns> returns;

		/**
		 * Gets the value of the returns property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the returns property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getReturns().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Returns }
		 * 
		 * 
		 */
		public List<Returns> getReturns() {
			if (returns == null) {
				returns = new ArrayList<Returns>();
			}
			return this.returns;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element ref="{}sales" maxOccurs="unbounded"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "sales" })
	@Entity
	@Table(name = "transaction_sales_list")
	public static class SalesList {

		@Id
		@GeneratedValue
		@Column(name = "salesListId")
		private Integer id;

		@XmlElement(required = true)
		@OneToMany(cascade = CascadeType.ALL)
		@JoinColumn(name = "salesListId")
		protected List<Sales> sales;

		/**
		 * Gets the value of the sales property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the sales property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getSales().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Sales }
		 * 
		 * 
		 */
		public List<Sales> getSales() {
			if (sales == null) {
				sales = new ArrayList<Sales>();
			}
			return this.sales;
		}

	}

}
