package bpm.gateway.core.veolia.patrimoine.xls;

import bpm.gateway.core.veolia.VEHelper;

public enum ListeSiteCommune {

	MACHECOUL("Machecoul"),
	COULON("Coulon"),
	L_Aiguillon_sur_Mer("L'Aiguillon-sur-Mer"),
	L_Aiguillon_sur_Vie("L'Aiguillon-sur-Vie"),
	Aizenay("Aizenay"),
	Angles("Angles"),
	Antigny("Antigny"),
	Apremont("Apremont"),
	Aubigny_Aubigny_Les_Clouzeaux("Aubigny - Aubigny - Les Clouzeaux"),
	Auzay_Auchay_sur_Vendee("Auzay - Auchay sur Vendée"),
	Avrille("Avrillé"),
	Barbatre("Barbâtre"),
	La_Barre_de_Monts("La Barre-de-Monts"),
	Bazoges_en_Paillers("Bazoges-en-Paillers"),
	Bazoges_en_Pareds("Bazoges-en-Pareds"),
	Beaufou("Beaufou"),
	Beaulieu_sous_la_Roche("Beaulieu-sous-la-Roche"),
	Beaurepaire("Beaurepaire"),
	Beauvoir_sur_Mer("Beauvoir-sur-Mer"),
	Belleville_sur_Vie_Bellivigny("Belleville-sur-Vie - Bellivigny"),
	Benet("Benet"),
	La_Bernardiere("La Bernardière"),
	Le_Bernard("Le Bernard"),
	Bessay("Bessay"),
	Bois_de_Cene("Bois-de-Céné"),
	La_Boissiere_de_Montaigu("La Boissière-de-Montaigu"),
	La_Boissiere_des_Landes("La Boissière-des-Landes"),
	Bouffere("Boufféré"),
	Bouille_Courdault("Bouillé-Courdault"),
	Bouin("Bouin"),
	Boulogne_Essarts_en_Bocage("Boulogne - Essarts en Bocage"),
	Le_Boupere("Le Boupère"),
	Bourneau("Bourneau"),
	Bournezeau("Bournezeau"),
	Bretignolles_sur_Mer("Bretignolles-sur-Mer"),
	La_Bretonniere_la_Claye("La_Bretonnière-la-Claye"),
	Breuil_Barret("Breuil-Barret"),
	Les_Brouzils("Les Brouzils"),
	La_Bruffiere("La Bruffière"),
	La_Caillere_Saint_Hilaire("La Caillère-Saint-Hilaire"),
	Cezais("Cezais"),
	Chaille_les_Marais("Chaillé-les-Marais"),
	Chaille_sous_les_Ormeaux_Rives_de_l_Yon("Chaillé-sous-les-Ormeaux - Rives de l'Yon"),
	Chaix_Auchay_sur_Vendee("Chaix - Auchay sur Vendée"),
	La_Chaize_Giraud("La Chaize-Giraud"),
	La_Chaize_le_Vicomte("La Chaize-le-Vicomte"),
	Challans("Challans"),
	Chambretaud("Chambretaud"),
	Champagne_les_Marais("Champagné-les-Marais"),
	Le_Champ_Saint_Pere("Le Champ-Saint-Père"),
	Chantonnay("Chantonnay"),
	La_Chapelle_Achard_Les_Achards("La Chapelle-Achard - Les Achards"),
	La_Chapelle_aux_Lys("La Chapelle-aux-Lys"),
	La_Chapelle_Hermier("La Chapelle-Hermier"),
	La_Chapelle_Palluau("La Chapelle-Palluau"),
	La_Chapelle_Themer("La Chapelle-Thémer"),
	Chasnais("Chasnais"),
	La_Chataigneraie("La Châtaigneraie"),
	Chateau_d_Olonne("Château-d'Olonne"),
	Chateau_Guibert("Château-Guibert"),
	Chateauneuf("Châteauneuf"),
	Les_Chatelliers_Chateaumur_Sevremont("Les Châtelliers-Châteaumur  - Sèvremont"),
	Chauche("Chauché"),
	Chavagnes_en_Paillers("Chavagnes-en-Paillers"),
	Chavagnes_les_Redoux("Chavagnes-les-Redoux"),
	Cheffois("Cheffois"),
	Les_Clouzeaux_Aubigny_Les_Clouzeaux("Les Clouzeaux  - Aubigny - Les Clouzeaux"),
	Coex("Coëx"),
	Commequiers("Commequiers"),
	La_Copechagniere("La Copechagnière"),
	Corpe("Corpe"),
	La_Couture("La Couture"),
	Cugand("Cugand"),
	Curzon("Curzon"),
	Damvix("Damvix"),
	Doix_Doix_les_Fontaines("Doix - Doix les Fontaines"),
	Dompierre_sur_Yon("Dompierre-sur-Yon"),
	Les_Epesses("Les Epesses"),
	L_Epine("L'Épine"),
	Les_Essarts_Essarts_en_Bocage("Les Essarts  - Essarts en Bocage"),
	Falleron("Falleron"),
	Faymoreau("Faymoreau"),
	Le_Fenouiller("Le Fenouiller"),
	La_Ferriere("La Ferrière"),
	La_Flocelliere_Sevremont("La Flocellière - Sèvremont"),
	Fontaines_Doix_les_Fontaines("Fontaines  - Doix les Fontaines"),
	Fontenay_le_Comte("Fontenay-le-Comte"),
	Fougere("Fougeré"),
	Foussais_Payre("Foussais-Payré"),
	Froidfond("Froidfond"),
	La_Garnache("La Garnache"),
	La_Gaubretiere("La Gaubretière"),
	La_Genetouze("La Génétouze"),
	Le_Girouard("Le Girouard"),
	Givrand("Givrand"),
	Le_Givre("Le Givre"),
	Grand_Landes("Grand'Landes"),
	Grosbreuil("Grosbreuil"),
	Grues("Grues"),
	Le_Gue_de_Velluire("Le Gué-de-Velluire"),
	La_Gueriniere("La Guérinière"),
	La_Guyonniere("La Guyonnière"),
	L_Herbergement("L'Herbergement"),
	Les_Herbiers("Les Herbiers"),
	L_Hermenault("L'Hermenault"),
	L_Ile_d_Elle("L'Île-d'Elle"),
	L_Ile_d_Olonne("L'Île-d'Olonne"),
	L_Ile_d_Yeu("L'Île-d'Yeu"),
	Jard_sur_Mer("Jard-sur-Mer"),
	La_Jaudonniere("La Jaudonnière"),
	La_Jonchere("La Jonchère"),
	Lairoux("Lairoux"),
	Landeronde("Landeronde"),
	Les_Landes_Genusson("Les Landes-Genusson"),
	Landevieille("Landevieille"),
	Le_Langon("Le Langon"),
	Liez("Liez"),
	Loge_Fougereuse("Loge-Fougereuse"),
	Longeves("Longèves"),
	Longeville_sur_Mer("Longeville-sur-Mer"),
	Lucon("Luçon"),
	Les_Lucs_sur_Boulogne("Les Lucs-sur-Boulogne"),
	Mache("Maché"),
	Les_Magnils_Reigniers("Les Magnils-Reigniers"),
	Maille("Maillé"),
	Maillezais("Maillezais"),
	Mallievre("Mallièvre"),
	Mareuil_sur_Lay_Dissais("Mareuil-sur-Lay-Dissais"),
	Marillet("Marillet"),
	Marsais_Sainte_Radegonde("Marsais-Sainte-Radégonde"),
	Martinet("Martinet"),
	Le_Mazeau("Le Mazeau"),
	La_Meilleraie_Tillay("La Meilleraie-Tillay"),
	Menomblet("Menomblet"),
	La_Merlatiere("La Merlatière"),
	Mervent("Mervent"),
	Mesnard_la_Barotiere("Mesnard-la-Barotière"),
	Monsireigne("Monsireigne"),
	Montaigu("Montaigu"),
	Montournais("Montournais"),
	Montreuil("Montreuil"),
	Moreilles("Moreilles"),
	Mormaison_Montreverd("Mormaison - Montréverd"),
	Mortagne_sur_Sevre("Mortagne-sur-Sèvre"),
	La_Mothe_Achard_Les_Achards("La Mothe-Achard - Les Achards"),
	Mouchamps("Mouchamps"),
	Mouilleron_en_Pareds_Mouilleron_Saint_Germain("Mouilleron-en-Pareds - Mouilleron Saint Germain"),
	Mouilleron_le_Captif("Mouilleron-le-Captif"),
	Moutiers_les_Mauxfaits("Moutiers-les-Mauxfaits"),
	Moutiers_sur_le_Lay("Moutiers-sur-le-Lay"),
	Mouzeuil_Saint_Martin("Mouzeuil-Saint-Martin"),
	Nalliers("Nalliers"),
	Nesmy("Nesmy"),
	Nieul_le_Dolent("Nieul-le-Dolent"),
	Nieul_sur_l_Autise("Nieul-sur-l'Autise"),
	Noirmoutier_en_l_Ile("Noirmoutier-en-l'Île"),
	Notre_Dame_de_Monts("Notre-Dame-de-Monts"),
	L_Oie_Essarts_en_Bocage("L'Oie  - Essarts en Bocage"),
	Olonne_sur_Mer("Olonne-sur-Mer"),
	L_Orbrie("L'Orbrie"),
	Oulmes("Oulmes"),
	Palluau("Palluau"),
	Peault("Péault"),
	Le_Perrier("Le Perrier"),
	Petosse("Petosse"),
	Les_Pineaux("Les Pineaux"),
	Pissotte("Pissotte"),
	Le_Poire_sur_Velluire("Le Poiré-sur-Velluire"),
	Le_Poire_sur_Vie("Le Poiré-sur-Vie"),
	Poiroux("Poiroux"),
	La_Pommeraie_sur_Sevre_Sevremont("La Pommeraie-sur-Sèvre  - Sèvremont"),
	Pouille("Pouillé"),
	Pouzauges("Pouzauges"),
	Puy_de_Serre("Puy-de-Serre"),
	Puyravault("Puyravault"),
	La_Rabateliere("La Rabatelière"),
	Reaumur("Réaumur"),
	La_Reorthe("La Réorthe"),
	Notre_Dame_de_Riez("Notre-Dame-de-Riez"),
	Rocheserviere("Rocheservière"),
	La_Roche_sur_Yon("La Roche-sur-Yon"),
	Rochetrejoux("Rochetrejoux"),
	Rosnay("Rosnay"),
	Les_Sables_d_Olonne("Les Sables-d'Olonne"),
	Saint_Andre_Goule_d_Oie("Saint-André-Goule-d'Oie"),
	Saint_Andre_Treize_Voies_Montreverd("Saint-André-Treize-Voies  - Montréverd"),
	Saint_Aubin_des_Ormeaux("Saint-Aubin-des-Ormeaux"),
	Saint_Aubin_la_Plaine("Saint-Aubin-la-Plaine"),
	Saint_Avaugourd_des_Landes("Saint-Avaugourd-des-Landes"),
	Saint_Benoist_sur_Mer("Saint-Benoist-sur-Mer"),
	Sainte_Cecile("Sainte-Cécile"),
	Saint_Christophe_du_Ligneron("Saint-Christophe-du-Ligneron"),
	Saint_Cyr_des_Gats("Saint-Cyr-des-Gâts"),
	Saint_Cyr_en_Talmondais("Saint-Cyr-en-Talmondais"),
	Saint_Denis_du_Payre("Saint-Denis-du-Payré"),
	Saint_Denis_la_Chevasse("Saint-Denis-la-Chevasse"),
	Saint_Etienne_de_Brillouet("Saint-Étienne-de-Brillouet"),
	Saint_Etienne_du_Bois("Saint-Étienne-du-Bois"),
	Sainte_Flaive_des_Loups("Sainte-Flaive-des-Loups"),
	Sainte_Florence_Essarts_en_Bocage("Sainte-Florence  - Essarts en Bocage"),
	Saint_Florent_des_Bois_Rives_de_l_Yon("Saint-Florent-des-Bois  - Rives de l'Yon"),
	Sainte_Foy("Sainte-Foy"),
	Saint_Fulgent("Saint-Fulgent"),
	Sainte_Gemme_la_Plaine("Sainte-Gemme-la-Plaine"),
	Saint_Georges_de_Montaigu("Saint-Georges-de-Montaigu"),
	Saint_Georges_de_Pointindoux("Saint-Georges-de-Pointindoux"),
	Saint_Germain_l_Aiguiller_Mouilleron_Saint_Germain("Saint-Germain-l'Aiguiller  - Mouilleron Saint Germain"),
	Saint_Germain_de_Princay("Saint-Germain-de-Prinçay"),
	Saint_Gervais("Saint-Gervais"),
	Saint_Gilles_Croix_de_Vie("Saint-Gilles-Croix-de-Vie"),
	Sainte_Hermine("Sainte-Hermine"),
	Saint_Hilaire_de_Loulay("Saint-Hilaire-de-Loulay"),
	Saint_Hilaire_de_Riez("Saint-Hilaire-de-Riez"),
	Saint_Hilaire_des_Loges("Saint-Hilaire-des-Loges"),
	Saint_Hilaire_de_Voust("Saint-Hilaire-de-Voust"),
	Saint_Hilaire_la_Foret("Saint-Hilaire-la-Forêt"),
	Saint_Hilaire_le_Vouhis("Saint-Hilaire-le-Vouhis"),
	Saint_Jean_de_Beugne("Saint-Jean-de-Beugné"),
	Saint_Jean_de_Monts("Saint-Jean-de-Monts"),
	Saint_Juire_Champgillon("Saint-Juire-Champgillon"),
	Saint_Julien_des_Landes("Saint-Julien-des-Landes"),
	Saint_Laurent_de_la_Salle("Saint-Laurent-de-la-Salle"),
	Saint_Laurent_sur_Sevre("Saint-Laurent-sur-Sèvre"),
	Saint_Maixent_sur_Vie("Saint-Maixent-sur-Vie"),
	Saint_Malo_du_Bois("Saint-Malô-du-Bois"),
	Saint_Mars_la_Reorthe("Saint-Mars-la-Réorthe"),
	Brem_sur_Mer("Brem-sur-Mer"),
	Saint_Martin_de_Fraigneau("Saint-Martin-de-Fraigneau"),
	Saint_Martin_des_Fontaines("Saint-Martin-des-Fontaines"),
	Saint_Martin_des_Noyers("Saint-Martin-des-Noyers"),
	Saint_Martin_des_Tilleuls("Saint-Martin-des-Tilleuls"),
	Saint_Martin_Lars_en_Sainte_Hermine("Saint-Martin-Lars-en-Sainte-Hermine"),
	Saint_Mathurin("Saint-Mathurin"),
	Saint_Maurice_des_Noues("Saint-Maurice-des-Noues"),
	Saint_Maurice_le_Girard("Saint-Maurice-le-Girard"),
	Saint_Mesmin("Saint-Mesmin"),
	Saint_Michel_en_l_Herm("Saint-Michel-en-l'Herm"),
	Saint_Michel_le_Cloucq("Saint-Michel-le-Cloucq"),
	Saint_Michel_Mont_Mercure_Sevremont("Saint-Michel-Mont-Mercure  - Sèvremont"),
	Saint_Paul_en_Pareds("Saint-Paul-en-Pareds"),
	Saint_Paul_Mont_Penit("Saint-Paul-Mont-Penit"),
	Sainte_Pexine("Sainte-Pexine"),
	Saint_Philbert_de_Bouaine("Saint-Philbert-de-Bouaine"),
	Saint_Pierre_du_Chemin("Saint-Pierre-du-Chemin"),
	Saint_Pierre_le_Vieux("Saint-Pierre-le-Vieux"),
	Saint_Prouant("Saint-Prouant"),
	Sainte_Radegonde_des_Noyers("Sainte-Radégonde-des-Noyers"),
	Saint_Reverend("Saint-Révérend"),
	Saint_Sigismond("Saint-Sigismond"),
	Saint_Sulpice_en_Pareds("Saint-Sulpice-en-Pareds"),
	Saint_Sulpice_le_Verdon_Montreverd("Saint-Sulpice-le-Verdon  - Montréverd"),
	Saint_Urbain("Saint-Urbain"),
	Saint_Valerien("Saint-Valérien"),
	Saint_Vincent_Sterlanges("Saint-Vincent-Sterlanges"),
	Saint_Vincent_sur_Graon("Saint-Vincent-sur-Graon"),
	Saint_Vincent_sur_Jard("Saint-Vincent-sur-Jard"),
	Saligny_Bellivigny("Saligny - Bellivigny"),
	Sallertaine("Sallertaine"),
	Serigne("Sérigné"),
	Sigournais("Sigournais"),
	Soullans("Soullans"),
	Le_Tablier("Le Tablier"),
	La_Taillee("La Taillée"),
	Tallud_Sainte_Gemme("Tallud-Sainte-Gemme"),
	Talmont_Saint_Hilaire("Talmont-Saint-Hilaire"),
	La_Tardiere("La Tardière"),
	Thire("Thiré"),
	Thorigny("Thorigny"),
	Thouarsais_Bouildroux("Thouarsais-Bouildroux"),
	Tiffauges("Tiffauges"),
	La_Tranche_sur_Mer("La Tranche-sur-Mer"),
	Treize_Septiers("Treize-Septiers"),
	Treize_Vents("Treize-Vents"),
	Triaize("Triaize"),
	Vaire("Vairé"),
	Velluire("Velluire"),
	Venansault("Venansault"),
	Vendrennes("Vendrennes"),
	La_Verrie("La Verrie"),
	Vix("Vix"),
	Vouille_les_Marais("Vouillé-les-Marais"),
	Vouvant("Vouvant"),
	Xanton_Chassenon("Xanton-Chassenon"),
	La_Faute_sur_Mer("La Faute-sur-Mer");
    private final String value;

    ListeSiteCommune(String v) {
        value = v;
    }
	
    public static String getValue(String table, String champ, ListeSiteCommune v, boolean required) {
    	if (required && v == null) {
    		throw new IllegalArgumentException("Table " + table + " - Champs " + champ + " - Valeur 'Null' ou non permise pour la liste.");
    	}
    	return v != null ? v.value : null;
    }
    
    public static ListeSiteCommune fromValue(String table, String champ, String v) {
    	if (v == null) {
    		System.out.println("Table " + table + " - Champs " + champ + " - Valeur 'Null' non permise.");
    		return null;
    	}
    	
        for (ListeSiteCommune c: ListeSiteCommune.values()) {
        	if (VEHelper.checkEnum(c.value, v)) {
        		return c;
        	}
        }
		System.out.println("Table " + table + " - Champs " + champ + " - Mauvaise valeur '" + v + "'");
		return null;
    }

}
